### ISSUE TITLE
Parallise scans

### ISSUE THREAD

**Issue by jshiell** [jshiell/checkstyle-idea#11]
**What steps will reproduce the problem?**
1. Run a checkstyle scan on a large project (circa 1200 files)
2. It takes AGES, and only one CPU core lights up. Intellij becomes unresponsive.
3.

**What is the expected output? What do you see instead?**
Load spread across CPU cores

**What version of the product are you using? On what operating system?**
Checkstyle plugin 3.1.2
Intellij 10.0.3
Mac OS 10.6.6

**Please provide any additional information below.**
Also, the scan seems to take much longer than running checkstyle from Ant.

**Comment by mmoayyed** [comment]
I am also experiencing similar issues. The check needs to run on a background thread to not hose down the IDE completely.

**Comment by jshiell** [comment]
Hmm. This should be fixed as of 4.20.1(#192) - I had forgotten this variant of the issue even existed, hence it didn't get closed. Which version of the plugin & IDEA are you using?

**Comment by mmoayyed** [comment]
Latest version of the plugin, and IDEA Ultimate 15.0.3 EAP

**Comment by jshiell** [comment]
I presume this occurs on non-EAP versions of this as well? And was it the static file scan or the inspection? Also, what sort of hardware are you running on, what OS and what project size? And do you have any thread dumps?

Certainly as of 4.20.1 the inspection runs on one of IDEA's pooled background threads, as recommended by Jetbrains. The static scan runs on a low priority thread of its own, and predates the inspection work by some way. As far as I can tell both branches are currently running off the main thread, as you'd hope.

I haven't seen any performance issues recently, but then I'm using small projects (as I haven't used it at work for ~2 years) and reasonably high end hardware (Haswell/Skylake i5s, 16Gb of RAM and SSDs).

**Comment by mmoayyed** [comment]
> I presume this occurs on non-EAP versions of this as well? 

Yes.

> And was it the static file scan or the inspection? 

Static

> Also, what sort of hardware are you running on, what OS and what project size? And do you have any thread dumps?

I don't have any dumps. I am on Windows 10 Pro, 8Core i7 3.0 Ghz with 16Gb of Ram, SSD. 

Project I work on: https://github.com/Jasig/cas

Here is how I can easily duplicate this:

1. Start the static scan
2. Note how IDEA becomes sluggish all of a sudden
3. Attempt open an editor, and start typing a few characters into the editor window
4. IDEA/Scan hands forever. 
5. Must restart/kill IDEA in order to continue.

**Comment by mmoayyed** [comment]
I am also on Version: 4.22.1

**Comment by jshiell** [comment]
Smashing, thanks - I'll have a go at reproducing this over Christmas.

**Comment by mmoayyed** [comment]
Much appreciated. If you need to run tests or provide anything else, please LMK.

**Comment by jshiell** [comment]
A start at least - I can reproduce this. Interestingly, if you move the cursor around it stays entirely responsive. If you type something, however, it quickly goes tits up. I manage to get 8 characters typed and then it locked up completely. 

Next step (probably tomorrow) is to try rewriting this so it uses the IDEA thread pool rather than a new thread, which is a good thing in any case. And check to see where and why it's locking, as since it's only write ops that seem to be triggering it it may be related to a write lock somewhere.

**Comment by jshiell** [comment]
I've been doing some work today, and think I've nailed it. I can now scan and happily type away in the CAS project with no apparently slowdown. The problem seems to be a combination of some really awful code I wrote last decade, and bad scoping for the read action, which lead to the scan being included in the locked region.

I've uploaded a [test build to Dropbox](https://dl.dropboxusercontent.com/u/5423904/checkstyle-idea-4.22.2.zip) - could please give this a try and let me know if it solves the problem? If so I'll do a bit more testing and get it released ASAP. Thank you!

**Comment by mmoayyed** [comment]
Sure thing. Much appreciated. I'll report back soon.

**Comment by mmoayyed** [comment]
Works fine. Thanks. Would you be able to publish an update?

**Comment by jshiell** [comment]
Released as 4.22.2. There are a couple more fixes in there (cancellation and checkin handler had some problems) so please update your local copy.

Thanks for your help with this :smile:

**Comment by mmoayyed** [comment]
Thanks. For some reason IDEA is not picking up the update. Does it usually take a bit for it to appear?

**Comment by jshiell** [comment]
AFAIK they should be up almost instantly, caches permitting. Do you still have the test version installed? As that had the same version number as the new build, so will need to be deleted before the new version is seen as an update.

Alternately, you can download it from [GitHub](https://github.com/jshiell/checkstyle-idea/releases/tag/4.22.2) or the [IDEA plugins site](https://plugins.jetbrains.com/plugin/1065?pr=).

**Comment by mmoayyed** [comment]
Found it. For reason IDEA was not picking up the update yesterday. Thanks.
