### ISSUE TITLE
Exception when add SuppressionFilter in Intellij Idea 14

### ISSUE THREAD

**Issue by Joeyfish** [jshiell/checkstyle-idea#119]
In Intellij Idea 14, after set SuppressionFilter, get file not found exception.

OS - mac osx 10.10
JDK - 1.7

**Comment by jsurls** [comment]
Finally got a chance to test it now that I'm no longer on vacation. Seems to be working in 4.11.2. No issues. Thanks for fixing it.

**Comment by jshiell** [comment]
No worries, thanks for your help!
