### ISSUE TITLE
Allow loading checkstyle configuration from jar files

### ISSUE THREAD

**Issue by twbecker** [jshiell/checkstyle-idea#125]
We have our checkstyle configuration packaged into a jar so it can be easily shared with other projects.  It would be nice if the plugin could load the config directly from that jar.  Currently we have to have a local checkout of the checkstyle project so we can point the plugin at the actual file.  Great job on the plugin BTW, we appreciate your efforts!

**Comment by twbecker** [comment]
Is UI still pending on this?  I downloaded the test build but I'm not seeing any changes in the settings.

**Comment by jshiell** [comment]
It should now allow you to browse inside JAR files when you're adding a rules file.

**Comment by twbecker** [comment]
Ahh so it does!  So reading the config file from the jar seems to work.  But we also have a suppressions file in the jar, and have referenced it from our checkstyle config like this:

    <module name="SuppressionFilter">
      
      <property name="file" value="${checkstyle.suppressions.file}" default="suppressions.xml"/>
    </module>

When run via the maven plugin, this works fine even without the checkstyle.suppressions.file property set.  But Checkstyle-IDEA insists we set it.  I think we are relying on it being found as a classpath resource as described here under Suppression Filter:  http://checkstyle.sourceforge.net/config.html

**Comment by jshiell** [comment]
Ah, it's entirely possible that's a case I've missed. I'll try have a look at that later this week - thanks for the feedback!

**Comment by jshiell** [comment]
I've [updated the test build](https://dl.dropboxusercontent.com/u/5423904/checkstyle-idea-4.12.0.zip) - it should now check for associated files inside the JAR if it cannot find them locally. Caveat: this is lightly tested, even by my evening hacking standards. But it seems to work.

**Comment by twbecker** [comment]
Seems to work fine!

**Comment by jshiell** [comment]
Released as 4.12.0 - many thanks for your help!
