### ISSUE TITLE
Configure code style from checkstyle

### ISSUE THREAD

**Issue by aikidojohn** [jshiell/checkstyle-idea#126]
It would be incredibly useful if there were a way to configure a code style profile from the checkstyle rules. There is a checkstyle plugin for eclipse that does this and I find it incredibly useful. What I end up doing now is exporting the generated formatter profile from eclipse and import it into IntelliJ.

**Comment by dbyron0** [comment]
Probably not particularly helpful, but I'd love to see this as well.

**Comment by helt** [comment]
Should it plug into intellij itself natively or do you recommend forking checkstyle-idea and implementing it in there?

**Comment by jshiell** [comment]
Good news - this was kindly contributed by @dyadix in https://github.com/jshiell/checkstyle-idea/pull/210 (release 4.24.0). Apologies for forgetting to close this issue!
