### ISSUE TITLE
Plugin ignores //CHECKSTYLE:OFF as first line

### ISSUE THREAD

**Issue by benson-basis** [jshiell/checkstyle-idea#128]
I have the check enabled for copyright. For a few files that 'come from someone else', my first line is //CHECKSTYLE:OFF. Running checkstyle from Maven works fine, but I get complaints from the inspection.

**Comment by jshiell** [comment]
Can you please attach your rules file and any supported files (i.e. suppressions and such)?

**Comment by benson-basis** [comment]
No suppressions are configured. here's the module from the rule file. I can post the entire rule file if you really want it.

```
 <module name="RegexpHeader">
        <property name="header" value="/\*.* This data and information is proprietary to, and a valuable trade secret.* of, Basis Technology Corp\.  It is given in confidence by Basis Technology.* and may only be used as permitted under the license agreement under which.* it has been distributed, and in no other way\..* Copyright \(c\) (20..|20..-....) Basis Technology Corporation All rights reserved\..* The technical data and information provided herein are provided with.* `limited rights', and the computer software provided herein is provided.* with `restricted rights' as those terms are defined in DAR and ASPR.** 7-104\.9\(a\).\n"/>
        <property name="fileExtensions" value="java"/>
    </module>
```

**Comment by jshiell** [comment]
I can't get that block to work (CheckStyle is saying it's an invalid Regex, so I'm guessing GitHub has fscked escaping or something similar).

However, ignoring that bit, it's working perfectly for me with the following config:
```
...
    <module name="SuppressionCommentFilter"/>
    
    <module name="TreeWalker">
        
        <module name="FileContentsHolder"/>
...
```

Any idea where my test case differs from your own?

**Comment by tsjensen** [comment]
No feedback for 2 years ... I think we can close this one.  🕸 🕷 🕸

**Comment by jshiell** [comment]
Works for me :-)
