### ISSUE TITLE
Exception to VisibilityModifier ignored by inspection

### ISSUE THREAD

**Issue by benson-basis** [jshiell/checkstyle-idea#129]
My checkstyle.xml has the following. Still, the inspection complains about these guys, even though all is well running from Maven.

```
  <module name="VisibilityModifier">
            <property name="protectedAllowed" value="true"/>
            <property name="packageAllowed" value="true"/>
            <!-- Allow public members with 'Rule' on the end of their names to allow for 
                 JUnit rules. Too bad we can't make this see the @nnotations.
             -->
            <property name="publicMemberPattern" value="^.*Rule$"/>
        </module>
```

**Comment by jshiell** [comment]
This is working fine on the latest master build (there's no changes that should alter behaviour between this and release). This is on IDEA 14.0.2, JDK 1.6.0_65 and OS X 10.0.1.

Adding the above module to my rules file, I can then enter:
 ```
    public int boo;
    public int booRule;

    {
        boo = 1;
        booRule = 1;
    }
```

I then see:
    Variable 'boo' must be private and have accessor methods. (32:16)

And no error for booRule, as expected.

Can you please provide plugin version, IDEA version and anything else you think may differ between my setup and your own?

**Comment by jshiell** [comment]
Closed due to no further updates in ... a while.
