### ISSUE TITLE
NumberFormatException in IntelliJ 14.0.3

### ISSUE THREAD

**Issue by mhurd** [jshiell/checkstyle-idea#130]
Hi,

We've been getting tonnes of these errors in IntelliJ from the CheckStyle Plugin, is this a bug or dodgy settings on our part?

thanks,
Mike

> The inspection could not be executed.
> org.infernus.idea.checkstyle.exception.CheckStylePluginException: The inspection could not be executed.
>   at org.infernus.idea.checkstyle.CheckStylePlugin.processError(CheckStylePlugin.java:120)
>   at org.infernus.idea.checkstyle.CheckStyleInspection.checkFile(CheckStyleInspection.java:238)
>   at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:149)
>   at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:412)
>   at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
>   at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:313)
>   at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:308)
>   at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:122)
>   at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:210)
>   at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:140)
>   at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
>   at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
>   at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
>   at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
>   at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
>   at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:278)
>   at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
>   at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
>   at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
>   at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
>   at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
>   at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
>   at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
>   at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
>   at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
> Caused by: java.lang.NumberFormatException: For input string: ""
>   at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
>   at java.lang.Integer.parseInt(Integer.java:592)
>   at java.lang.Integer.parseInt(Integer.java:615)
>   at java.text.MessageFormat.makeFormat(MessageFormat.java:1427)
>   at java.text.MessageFormat.applyPattern(MessageFormat.java:479)
>   at java.text.MessageFormat.<init>(MessageFormat.java:362)
>   at java.text.MessageFormat.format(MessageFormat.java:840)
>   at com.puppycrawl.tools.checkstyle.api.LocalizedMessage.getCustomMessage(LocalizedMessage.java:296)
>   at com.puppycrawl.tools.checkstyle.api.LocalizedMessage.getMessage(LocalizedMessage.java:262)
>   at org.infernus.idea.checkstyle.checker.CheckStyleAuditListener$ProcessResultsThread.messageFor(> CheckStyleAuditListener.java:255)
>   at org.infernus.idea.checkstyle.checker.CheckStyleAuditListener$ProcessResultsThread.processEvent(> CheckStyleAuditListener.java:238)
>   at org.infernus.idea.checkstyle.checker.CheckStyleAuditListener$ProcessResultsThread.run(CheckStyleAuditListener.> java:164)
>   at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:896)
>   at org.infernus.idea.checkstyle.checker.CheckStyleAuditListener.auditFinished(CheckStyleAuditListener.java:81)
>   at com.puppycrawl.tools.checkstyle.Checker.fireAuditFinished(Checker.java:466)
>   at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:292)
>   at org.infernus.idea.checkstyle.CheckStyleInspection.scanFile(CheckStyleInspection.java:278)
>   at org.infernus.idea.checkstyle.CheckStyleInspection.checkFile(CheckStyleInspection.java:225)
>   ... 23 more

**Comment by jshiell** [comment]
Looking at the stack trace, I’d guess it’s probably my fault. I’ll have a look, but it probably won’t be until at least tomorrow - sorry!

**Comment by mhurd** [comment]
No rush, thanks for the quick response!

**Comment by jshiell** [comment]
I fear it looks like it's coming from CheckStyle itself - I'm just asking the CheckStyle event for the error message, and it's blowing up while formatting it.

If you're able, could you please attach the rules file? It's possible it's a typo in there, or we might have found a bug in CheckStyle :smile:

**Comment by mhurd** [comment]
Apologies for the delay, here's the XML:

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
          "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
          "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<!--

    Checkstyle configuration that checks the Google coding conventions from:
    
    -  Google Java Style
       https://google-styleguide.googlecode.com/svn-history/r130/trunk/javaguide.html
       
    Checkstyle is very configurable. Be sure to read the documentation at
    http://checkstyle.sf.net (or in your downloaded distribution).

    Most Checks are configurable, be sure to consult the documentation.

    To completely disable a check, just comment it out or delete it from the file.

    Authors: Max Vetrenko, Ruslan Diachenko, Roman Ivanov.
    
 -->
 
<module name = "Checker">
    <property name="charset" value="UTF-8"/>
    
    <property name="severity" value="warning"/>
    
    <!-- Checks for whitespace                               -->
    <!-- See http://checkstyle.sf.net/config_whitespace.html -->
        <module name="FileTabCharacter">
            <property name="eachLine" value="true"/>
        </module>
    
    <module name="TreeWalker">
        <module name="OuterTypeFilename"/>
        <module name="IllegalTokenText">
            <property name="tokens" value="STRING_LITERAL, CHAR_LITERAL"/>
            <property name="format" value="\\u00(08|09|0(a|A)|0(c|C)|0(d|D)|22|27|5(C|c))|\\(0(10|11|12|14|15|42|47)|134)"/>
            <property name="message" value="Avoid using corresponding octal or Unicode escape."/>
        </module>
        <module name="AvoidEscapedUnicodeCharacters">
            <property name="allowEscapesForControlCharacters" value="true"/>
            <property name="allowByTailComment" value="true"/>
            <property name="allowNonPrintableEscapes" value="true"/>
        </module>
        <module name="LineLength">
            <property name="max" value="120"/>
            <property name="ignorePattern" value="^package.*|^import.*|a href|href|http://|https://|ftp://"/>
        </module>
        <module name="AvoidStarImport"/>
        <module name="OneTopLevelClass"/>
        <module name="NoLineWrap"/>
        <module name="EmptyBlock">
            <property name="option" value="TEXT"/>
            <property name="tokens" value="LITERAL_TRY, LITERAL_CATCH, LITERAL_FINALLY, LITERAL_IF, LITERAL_ELSE, LITERAL_SWITCH"/>
        </module>
        <module name="NeedBraces"/>
        <module name="LeftCurly">
            <property name="maxLineLength" value="120"/>
        </module>
        <module name="RightCurly"/>
        <module name="RightCurly">
            <property name="option" value="alone"/>
            <property name="tokens" value="CLASS_DEF, METHOD_DEF, CTOR_DEF, LITERAL_FOR, LITERAL_WHILE, LITERAL_DO, STATIC_INIT, INSTANCE_INIT"/>
        </module>
        <module name="WhitespaceAround">
            <property name="allowEmptyConstructors" value="true"/>
            <property name="allowEmptyMethods" value="true"/>
            <property name="allowEmptyTypes" value="true"/>
            <property name="allowEmptyLoops" value="true"/>
            <message key="ws.notFollowed"
             value="WhitespaceAround: ''{0}'' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3)"/>
             <message key="ws.notPreceded"
             value="WhitespaceAround: ''{0}'' is not preceded with whitespace."/>
        </module>
        <module name="OneStatementPerLine"/>
        <module name="MultipleVariableDeclarations"/>
        <module name="ArrayTypeStyle"/>
        <module name="MissingSwitchDefault"/>
        <module name="FallThrough"/>
        <module name="UpperEll"/>
        <module name="ModifierOrder"/>
        <module name="EmptyLineSeparator">
            <property name="allowNoEmptyLineBetweenFields" value="true"/>
        </module>
        <module name="SeparatorWrap">
            <property name="tokens" value="DOT"/>
            <property name="option" value="nl"/>
        </module>
        <module name="SeparatorWrap">
            <property name="tokens" value="COMMA"/>
            <property name="option" value="EOL"/>
        </module>
        <module name="PackageName">
            <property name="format" value="^[a-z]+(\.[a-z][a-z0-9]*)*$"/>
            <message key="name.invalidPattern"
             value="Package name ''{0}'' must match pattern ''{1}''."/>
        </module>
        <module name="TypeName">
            <message key="name.invalidPattern"
             value="Type name ''{0}'' must match pattern ''{1}''."/>
        </module>
        <module name="MemberName">
            <property name="format" value="^[a-z][a-z0-9][a-zA-Z0-9]*$"/>
            <message key="name.invalidPattern"
             value="Member name ''{0}'' must match pattern ''{1}''."/>
        </module>
        <module name="ParameterName">
            <property name="format" value="^[a-z][a-z0-9][a-zA-Z0-9]*$"/>
            <message key="name.invalidPattern"
             value="Parameter name ''{0}'' must match pattern ''{1}''."/>
        </module>
        <module name="LocalVariableName">
            <property name="tokens" value="VARIABLE_DEF"/>
            <property name="format" value="^[a-z][a-z0-9][a-zA-Z0-9]*$"/>
            <property name="allowOneCharVarInForLoop" value="true"/>
            <message key="name.invalidPattern"
             value="Local variable name ''{0}'' must match pattern ''{1}''."/>
        </module>
        <module name="ClassTypeParameterName">
            <property name="format" value="(^[A-Z][0-9]?)$|([A-Z][a-zA-Z0-9]*[T]$)"/>
            <message key="name.invalidPattern"
             value="Class type name ''{0}'' must match pattern ''{1}''."/>
        </module>
        <module name="MethodTypeParameterName">
            <property name="format" value="(^[A-Z][0-9]?)$|([A-Z][a-zA-Z0-9]*[T]$)"/>
            <message key="name.invalidPattern"
             value="Method type name ''{0}'' must match pattern ''{1}''."/>
        </module>
        <module name="NoFinalizer"/>
        <module name="GenericWhitespace">
            <message key="ws.followed"
             value="GenericWhitespace ''{0}'' is followed by whitespace."/>
             <message key="ws.preceded"
             value="GenericWhitespace ''{0}'' is preceded with whitespace."/>
             <message key="ws.illegalFollow"
             value="GenericWhitespace ''{0}'' should followed by whitespace."/>
             <message key="ws.notPreceded"
             value="GenericWhitespace ''{0}'' is not preceded with whitespace."/>
        </module>
        <module name="Indentation">
            <property name="basicOffset" value="4"/>
        </module>
        <module name="OverloadMethodsDeclarationOrder"/>
        <module name="VariableDeclarationUsageDistance"/>
        <module name="CustomImportOrder">
            <property name="thirdPartyPackageRegExp" value=".*"/>
            <property name="specialImportsRegExp" value="com.google"/>
            <property name="sortImportsInGroupAlphabetically" value="true"/>
            <property name="customImportOrderRules" value="STATIC###SPECIAL_IMPORTS###THIRD_PARTY_PACKAGE###STANDARD_JAVA_PACKAGE"/>
        </module>
        <module name="MethodParamPad"/>
        <module name="OperatorWrap">
            <property name="option" value="NL"/>
            <property name="tokens" value="BAND, BOR, BSR, BXOR, DIV, EQUAL, GE, GT, LAND, LE, LITERAL_INSTANCEOF, LOR, LT, MINUS, MOD, NOT_EQUAL, PLUS, QUESTION, SL, SR, STAR "/>
        </module>
        <module name="AnnotationLocation">
            <property name="tokens" value="CLASS_DEF, INTERFACE_DEF, ENUM_DEF, METHOD_DEF, CTOR_DEF"/>
        </module>
        <module name="AnnotationLocation">
            <property name="tokens" value="VARIABLE_DEF"/>
            <property name="allowSamelineMultipleAnnotations" value="true"/>
        </module>
        <module name="NonEmptyAtclauseDescription"/>
        <module name="JavadocTagContinuationIndentation"/>
        <module name="SummaryJavadocCheck">
            <property name="forbiddenSummaryFragments" value="^@return the *|^This method returns |^A [{]@code [a-zA-Z0-9]+[}]( is a )"/>
        </module>
        <module name="JavadocParagraph"/>
        <module name="AtclauseOrder">
            <property name="tagOrder" value="@param, @return, @throws, @deprecated"/>
            <property name="target" value="CLASS_DEF, INTERFACE_DEF, ENUM_DEF, METHOD_DEF, CTOR_DEF, VARIABLE_DEF"/>
        </module>
        <module name="MethodName">
            <property name="format" value="^[a-z][a-z0-9][a-zA-Z0-9_]*$"/>
            <message key="name.invalidPattern"
             value="Method name ''{0}'' must match pattern ''{1}''."/>
        </module>
        <module name="SingleLineJavadoc"/>
    </module>
</module>
```

**Comment by jshiell** [comment]
Cheers :smile:

However, the plot now thickens. This is working perfectly for me, both in real-time and static scans. I pasted it into a new XML file, charset UTF-8, and can't get it to break.

I'm using IDEA 14.0.3 on OS X 10.10.2 and the latest plugin version (which uses CheckStyle 6.1.1). Any suggestions on where your setup is different might help pinpoint the issue.

Also, does the file run with CheckStyle on the command line? And if so, which version? Thanks!

**Comment by mhurd** [comment]
Hi, I'm using the same except I'm running on Windows 7. I get the same thing if I try from the command line too. What about end-of-line characters?

```
PS C:\Users\mhurd\Downloads> java -jar checkstyle-6.3-all.jar -c ..\Desktop\checkstyle-config.xml ..\workspace\UKDevelopment\FOO\trunk\AuthenticationService\src\main\
java\com\foo\bar\implementation\kb5\KerberosV5Auth.java
Exception in thread "main" java.lang.IllegalArgumentException: can't parse argument number:
        at java.text.MessageFormat.makeFormat(Unknown Source)
        at java.text.MessageFormat.applyPattern(Unknown Source)
        at java.text.MessageFormat.<init>(Unknown Source)
        at java.text.MessageFormat.format(Unknown Source)
        at com.puppycrawl.tools.checkstyle.api.LocalizedMessage.getCustomMessage(LocalizedMessage.java:304)
        at com.puppycrawl.tools.checkstyle.api.LocalizedMessage.getMessage(LocalizedMessage.java:270)
        at com.puppycrawl.tools.checkstyle.api.AuditEvent.getMessage(AuditEvent.java:109)
        at com.puppycrawl.tools.checkstyle.DefaultLogger.addError(DefaultLogger.java:101)
        at com.puppycrawl.tools.checkstyle.Checker.fireErrors(Checker.java:530)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:288)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:128)
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        ... 11 more
PS C:\Users\mhurd\Downloads>
```

**Comment by jshiell** [comment]
I fear I don't have a Windows box to test on at present. Although the good news for me is that it's a CheckStyle thing rather than in the plugin. But that's not a lot of help to the issue at hand.

I've [stuck my copy of the file on DropBox](https://dl.dropboxusercontent.com/u/5423904/issue-130.xml) - if you could try that, that would show it as either a file issue (if my copy works) or a platform issue (if it fails in the same way).

**Comment by mhurd** [comment]
Unfortunately I can't access Dropbox from work, can you email it to me at 'mhurd at bgc partners . com' - spaces removed / @ replaced obviously :-)

**Comment by mhurd** [comment]
Thanks, got it - it fails in the same way:

```
PS C:\Users\mhurd\Downloads> java -jar checkstyle-6.3-all.jar -c ..\Desktop\issue-130.xml ..\workspace\UKDevelopment\GMO\trunk\AuthenticationService\src\main\java\com\esp
eed\gmo\implementation\kb5\KerberosV5Auth.java
Exception in thread "main" java.lang.IllegalArgumentException: can't parse argument number:
        at java.text.MessageFormat.makeFormat(Unknown Source)
        at java.text.MessageFormat.applyPattern(Unknown Source)
        at java.text.MessageFormat.<init>(Unknown Source)
        at java.text.MessageFormat.format(Unknown Source)
        at com.puppycrawl.tools.checkstyle.api.LocalizedMessage.getCustomMessage(LocalizedMessage.java:304)
        at com.puppycrawl.tools.checkstyle.api.LocalizedMessage.getMessage(LocalizedMessage.java:270)
        at com.puppycrawl.tools.checkstyle.api.AuditEvent.getMessage(AuditEvent.java:109)
        at com.puppycrawl.tools.checkstyle.DefaultLogger.addError(DefaultLogger.java:101)
        at com.puppycrawl.tools.checkstyle.Checker.fireErrors(Checker.java:530)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:288)
        at com.puppycrawl.tools.checkstyle.Main.main(Main.java:128)
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        ... 11 more
```

**Comment by jshiell** [comment]
Bugger. Which leaves it pointing at a platform difference. Apologies, but I'm not sure I can be of much more help.

I'd be tempted to [raise an issue with the CheckStyle project](https://github.com/checkstyle/checkstyle/issues) themselves. You've got a reproducible test case with the command line, so hopefully they can pinpoint it fairly quickly. Or you could start chopping the file down until you can find what's breaking it.

I did find [something similar from an Eclipse-CS user](http://sourceforge.net/p/eclipse-cs/bugs/380/). I'm not sure if it'll apply in your case, but might be worth checking.

**Comment by mhurd** [comment]
Ok, thanks for taking a look though :-) I'll raise an issue with them directly then - much appreciated. Take care!

**Comment by jshiell** [comment]
No worries, you too! Fingers crossed it gets sorted nice & quickly.
