### ISSUE TITLE
Can't install in Android studio

### ISSUE THREAD

**Issue by xu6148152** [jshiell/checkstyle-idea#132]
Android Studio give the hint that Plugin CheckStyle-idea is incompatible with current installation

My Android studio version is 1.1.0
CheckStyle version is 4.13.1

**Comment by jshiell** [comment]
The latest versions of CS-IDEA required IDEA 14 (build 139.658) or above, so if Android Studio is based off an older SDK then it won't work.

Until Android Studio is updated I should imagine versions based off the IDEA 13 SDK will continue to work (i.e. 4.12 and below).
