### ISSUE TITLE
error:Plugin CheckStyle-IDEA is incompatible with current  installation

### ISSUE THREAD

**Issue by audiebantzhan** [jshiell/checkstyle-idea#135]
Android Studio 1.1.0

**Comment by jshiell** [comment]
The latest versions of CS-IDEA required IDEA 14 (build 139.658) or above, so if Android Studio is based off an older SDK then it won't work.

Until Android Studio is updated I should imagine versions based off the IDEA 13 SDK will continue to work (i.e. 4.12 and below).
