### ISSUE TITLE
Checkstyle-idea keeps locks on dependency jar-files

### ISSUE THREAD

**Issue by hutteman** [jshiell/checkstyle-idea#141]
In an environment where dependency jar-files are checked into source control, SVN updates (either from inside IDEA, or using an external svn client while IDEA is still running) fail when the Checkstyle-idea plugin is enabled in IDEA. Apparently the plugin keeps these files open, making it impossible to overwrite them.

I've noticed this occurs even when opening a second project in IDEA that does not use this dependency jar-file, and subsequently closing the first project, that did. Even though after this no project is open that has this jar as a dependency, the jar-file remains locked and cannot be overwritten. The only way around this is to close IDEA, and use an external svn client to update the project (after doing an svn cleanup).

Disabling the Checkstyle-idea plugin fixes this issue.

**Comment by jshiell** [comment]
Thanks for the report. I'm guessing it'll be the classpath parsing - we need to query the project classpath for the exception checks to work, so I'll have to find out where it's not cleaning up properly.

**Comment by jshiell** [comment]
Are you using Windows by some chance? Just interested as I've never noticed this on Linux and/or OS X, and they tend to be less fussy about file locks.

In any case, what I currently believe is causing this is that cached checkers are never cleaned up, and the cache is an application level service, i.e. it lives until IntelliJ shuts down. I'm currently looking at adding a cleanup task to ensure that expired checkers are removed from the cache.

**Comment by hutteman** [comment]
Yes, I am using Windows

**Comment by jshiell** [comment]
I've changed the checker cache so it should purge files now, which will make the class loaders (and hence the file locks) eligible for garbage collection. This has been released in 4.14.2.

Hopefully this will fix this issue - if not, please reopen it and I'll take another look.

**Comment by hutteman** [comment]
This issue has not been resolved; I'm running version 4.15.0 and it's still keeping a lock on all .jar files in windows.

**Comment by nicity** [comment]
Btw, To avoid jar locking under Windows IntelliJ IDEA copies jars to special directory and uses the copy for reading. Relevant code is in com.intellij.openapi.vfs.impl.jar.JarFileSystemImpl.getMirroredFile

**Comment by jshiell** [comment]
That's awesome - that's very much for the tip!






On Thu, Jun 18, 2015 at 5:19 AM -0700, "nicity" <notifications@github.com> wrote:












Btw, To avoid jar locking under Windows IntelliJ IDEA copies jars to special directory and uses the copy for reading. Relevant code is in com.intellij.openapi.vfs.impl.jar.JarFileSystemImpl.getMirroredFile

**Comment by jshiell** [comment]
I've knocked together a test build using *getMirroredFile* - you can find it [on DropBox](https://dl.dropboxusercontent.com/u/5423904/checkstyle-idea-4.16.1.zip).

**Disclaimer** - this was put together with my laptop on a beach, so I'm missing complex projects/my collection of test configurations to test with. So it hasn't been well tested.

**Comment by jshiell** [comment]
I'm going to assume it's fixed for the present, feel free to reopen if it's (again) not the case :smile:
