### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by DFieldFL** [jshiell/checkstyle-idea#145]
I got this error when I upgrade to 4.14.0. Looks like there isn't a release for this version in github but this version do exist on the plugins page https://plugins.jetbrains.com/plugin/1065

Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA] [Plugin: CheckStyle-IDEA]

**Comment by jshiell** [comment]
Dup of 142.

**Comment by jshiell** [comment]
#142 for the purposes of a link.

**Comment by DFieldFL** [comment]
Sorry for not providing more information, but I am running Ubuntu 14.10. #142 issue appears to be related to OSX. Do I need to install the bundled Intellij for Ubuntu as well.

I am currently not running with the bundled version and I have oracle-7-install (from ppa:webupd8team/java)

**Comment by jshiell** [comment]
Ah sorry - I've received a few of these today and this is the first non OS X one!

Yes, please use either the bundled version, or a system JDK 8. Technically I could still build it with JDK 7, but I'd really like to start using JDK 8 language features. If, however, there's a lot of people still using JDK 7 for IDEA I may reconsider.

Thanks for the feedback :smile:

**Comment by DFieldFL** [comment]
sounds good thanks!

**Comment by DFieldFL** [comment]
I tried looking for a bundled JDK 8 but could not find one. Have you come across one at all?

**Comment by jshiell** [comment]
I just had a poke around, and I couldn't find one either. I'm not sure if this is because Jetbrains haven't linked it (they don't have a link on the download page for the OS X one) or if there isn't one for 14.1. Either way, it's somewhat inconvenient.

Without that, I guess the only current option using a system OpenJDK or Oracle JDK. Sorry about that.

**Comment by ECODevOps** [comment]
> Yes, please use either the bundled version, or a system JDK 8. Technically I could still build it with JDK 7, but I'd really like to start using JDK 8 language features. If, however, there's a lot of people still using JDK 7 for IDEA I may reconsider.

Is there any reason why the plugin couldn't be built with -source 1.8 -target 1.7?

**Comment by jqassar** [comment]
> Yes, please use either the bundled version, or a system JDK 8. Technically I could still build it with JDK 7, but I'd really like to start using JDK 8 language features. If, however, there's a lot of people still using JDK 7 for IDEA I may reconsider.

Is there any reason why the plugin couldn't be built with -source 1.8 -target 1.7?

**Comment by jshiell** [comment]
http://stackoverflow.com/questions/16143684/can-java-8-code-be-compiled-to-run-on-java-7-jvm

**Comment by jqassar** [comment]
Ah, fair enough.  Far be it from me to get between anyone and lambda expressions.

**Comment by flstaats** [comment]
I just tried to upgrade to Intellij IDEA 14.1.3 (from 14.0) and discovered that the the latest checkstyle plug-in is giving me this error.  I will not have the option of upgrading my projects to Java 8 until the end of the year at the earliest (corporate environment dependent on tools that are stuck at Java 7 until we upgrade the whole platform... about 3-5 developer years worth of real work.)  What is the latest version of the checksytyle-idea plug-in that supports projects with Java 7?

**Comment by jshiell** [comment]
@flstaats you don't need to upgrade your projects, just the JVM IDEA runs on.

**Comment by leiferksn** [comment]
perhaps a useful link: http://mcaf.ee/63wbi1

by configuring IDEA_JDK_64 environment variable to point to jdk 1.8, I was able to avoid this error.

**Comment by jshiell** [comment]
Thanks @leiferksn!

**Comment by smuryginim** [comment]
This very bad that there is no support for older versions(((

**Comment by jshiell** [comment]
Why? It's just your IDEA JDK - you can continue to develop projects on any version of the JDK you like. And Java is clunky enough without having to suffer pre-8 versions of the language.

**Comment by smuryginim** [comment]
Actually I tried to set up only IDEA jvm 
https://intellij-support.jetbrains.com/hc/en-us/articles/206827547-Selecting-the-JDK-version-the-IDE-will-run-under (by setting IDEA_JDK_64 environment variable), but now I have error when trying to start idea (Failed to create jvm: error code -6) and I can't find any explanation on that in the web

**Comment by jshiell** [comment]
If you're on a Mac or (I think) Windows there are downloads with bundled JDKs. Otherwise, you'd need to raise a support request with Jetbrains, given they do support JDK8 as a runtime platform.
