### ISSUE TITLE
Unable to load project because of PluginException

### ISSUE THREAD

**Issue by stovocor** [jshiell/checkstyle-idea#146]
After installing the latest version of the CheckStyle plugin, my project fails to load with this error:

````Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA] [Plugin: CheckStyle-IDEA]````

**Comment by jshiell** [comment]
Assuming you're using OS X, dup of #142. Otherwise, you'll need to run IDEA on top of JDK 8.

**Comment by stovocor** [comment]
Thanks for the hint, I was running IDEA with JDK 7.

**Comment by jshiell** [comment]
No worries - this one is popping up a lot at present :smile:
