### ISSUE TITLE
v4.14.0 causes InteliJ StartupAbortedException

### ISSUE THREAD

**Issue by sbiggs-isl** [jshiell/checkstyle-idea#147]
I had a previous version installed (not sure of version number but I usually keep up-to-date so I reckon I was on 4.13.2). I applied the upgrade to 4.14.0. Next time I started IntelliJ I got the attached error message.
![checkstyle-error](https://cloud.githubusercontent.com/assets/11867275/7062460/6337c7ca-de95-11e4-9156-cc6461d2f528.png)
Trying to open my project again, I get the same error message. If I uninstall the checkstyle plugin it works fine again. If I re-install v4.14.0 it breaks again. If I revert to the previous version (4.13.2) it works fine. Details of my hardware and OS can be provided on request - just tell me which bits of info you need.

**Comment by jshiell** [comment]
This is because the latest version of the plugin is compiled with JDK 8. If you're on a Mac, please look at #142 for hints on solving this. Otherwise, please run IntelliJ on JDK 8.

**Comment by sbiggs-isl** [comment]
Ok, yeah, I'm still on JDK 7 for now. Sorry for the bother.

S




On 09/04/15 08:55, James Shiell wrote:

This is because the latest version of the plugin is compiled with JDK 8. If you're on a Mac, please look at #142<https://github.com/jshiell/checkstyle-idea/issues/142> for hints on solving this. Otherwise, please run IntelliJ on JDK 8.

**Comment by jshiell** [comment]
No worries - it turns out I rather underestimated the number of people this would affect! Sorry about that :smile:

**Comment by sbiggs-isl** [comment]
No worries. I should have looked at the existing issues more carefully and I would have seen that #142 covers the same thing!

S




On 09/04/15 09:01, James Shiell wrote:

No worries - it turns out I rather underestimated the number of people this would affect! Sorry about that [https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png]
