### ISSUE TITLE
Can not load Java 7 project after IDEA 14.1.1 update 

### ISSUE THREAD

**Issue by darwin604** [jshiell/checkstyle-idea#148]
After updating to IDEA 14.1.1 from 14.1.0 I am now unable to load any of my projects with the CheckStyle plugin enabled. From the error output it appears to be a Java version incompatibility. Not sure if this has any bearing on the issue but the projects are configured to use the Java 1.7 SDK. Please see the screenshot attached for more info. This has been confirmed on both OSX Yosemite and Windows 7 machines using CheckStyle IDEA v4.14.0

![screen shot 2015-04-09 at 11 55 01 am](https://cloud.githubusercontent.com/assets/4223591/7074581/7bfa8304-deb0-11e4-8f99-f76ec9b8ba2c.png)

**Comment by jshiell** [comment]
Dup of #142 (includes solution) :smile:

**Comment by jshiell** [comment]
The Windows solution is just to run IDEA on JDK 8.

**Comment by darwin604** [comment]
I've been running it using JDK8 on my machine but it appears that IDEA's JDK is different. Odd that it doesn't use this by default. At any rate, this seems to have fixed it. Thanks!
