### ISSUE TITLE
Several temporary files created

### ISSUE THREAD

**Issue by curobosqui** [jshiell/checkstyle-idea#149]
I'm using Android Studio 1.0.2 and CheckStyle plugin version 4.11.2 using a rule xml file stored in an intranet server.

I'm noticing that there are a lot of files in Android Studio's temp directory. In my PC in the following directory:
c:\Users\<username>\.AndroidStudio\system\tmp

I have 1000 files created in the span of 2 hours, called checkStyle<numbers>.xml that all contain the rules file. Is there a way to prevent this large amount of files?

Are they created each time the server is queried for the rules? Is there a way to limit how often the server is checked for the rules file?

**Comment by jshiell** [comment]
I presume you're accessing the file over HTTP? 

I'm not quite sure what's happening at present. What should happen is that the real file is queried at most once a minute, and locally cached for that minute. The reason we get new files is that every time we query the server we're using File.createTempFile to write the contents. Although I wouldn't have expected 1000. To be perfectly honest, the HTTP access is a bit ratty - it was a feature request for someone, and it's not something I've ever used (and hence has been neglected).

I'll have a look at changing it to use a consistent temporary file, so you don't get spammed with them.

**Comment by jshiell** [comment]
That fix will be released in 4.14.1, which should be next week. Thanks for the report.

**Comment by curobosqui** [comment]
Yes, the rule file is accessed via HTTP.

btw, on my original message the file name for the temp files should be checkStyle&lt;numbers&gt;.xml, the part between angle brackets was lost because I used it as html, my bad.
