### ISSUE TITLE
Invalid version number exception at loading a project at IDEA 14.1.1

### ISSUE THREAD

**Issue by hneemann** [jshiell/checkstyle-idea#151]
The only way to open the project again is to disable the plugin.

This is the upcoming error message:

Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA] [Plugin: CheckStyle-IDEA]

**Comment by jshiell** [comment]
Dup of #142 if you're on OS X (solutions discussed over there). Otherwise, please run IDEA on JDK8.
