### ISSUE TITLE
Checkstyle plugin crashes with error: Unsupported major.minor version 52.0 

### ISSUE THREAD

**Issue by gmbett** [jshiell/checkstyle-idea#152]
Using Android Studio 1.2 Beta 3, I can't open any project if the Checkstyle plugin is enabled:
![error](https://cloud.githubusercontent.com/assets/3603795/7132953/5638548e-e28e-11e4-9080-e20fc4c05271.png)

**Comment by jshiell** [comment]
You will need to run IDEA/Android Studio on Java 8.

**Comment by Splaktar** [comment]
You link the IDEA version with bundled JDK8 in the README, but I don't see an Android Studio version with the bundled JDK8.

It looks like Android Studio requires another process for launching with JDK8: http://tools.android.com/tech-docs/configuration

**Comment by jshiell** [comment]
How are you setting STUDIO_JDK? I'd expect it to work happily after a reboot (as it'd need to be visible to the login environment) as long as it's in .bash_profile/.zshrc/whatever's appropriate to your shell.

**Comment by Splaktar** [comment]
`export STUDIO_JDK=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk` in `.bash_profile`.

**Comment by jshiell** [comment]
I'm not sure that's correct - I'd expect the path to include Contents/Home, e.g.:
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home
```
You can use /usr/libexec/java_home to automate this, e.g. to give you the latest installed 1.8.x JVM:
```
export STUDIO_JDK=$(/usr/libexec/java_home -v '1.8*')
```

**Comment by Splaktar** [comment]
I had tried with `/Contents/Home` at first, but it didn't work. Also the example on android.com was without it as well. It worked fine from the CLI after I manually exported it before launch, just not from the OS X launcher.

Thanks for the `java_home` tip!

**Comment by jshiell** [comment]
Ah, I did not know that. Thank you. However, my understanding is that that should work with the OS X launcher, so the only other suggestion I can make is editing Contents/Info.plist in the OS X application to use the appropriate JDK. In IntelliJ you can edit JVMOptions/JVMVersion to 1.8* to accomplish this.

**Comment by akuttyd** [comment]
Is this resolved because I am getting the same issue . I tried doing the same thing as per @jshiell . I got it to work last week but then with the latest android studio update it has got corrupted and i am getting the same issue as logged.

**Comment by jshiell** [comment]
It's as resolved as it's going to get. You'll need to run Android Studio on JDK8 (or ideally with the bundled JDK if Jetbrains offer it).

**Comment by akuttyd** [comment]
@jshiell . I changed the JVM version to <key>JVMVersion</key>
      <string>1.6*,1.7+,1.8*</string>. It is giving me the same issue

**Comment by jshiell** [comment]
Sorry, I don't use Android Studio so I can't comment further than the suggestions above.

**Comment by akuttyd** [comment]
@jshiell Thanks for the help

**Comment by williamhqs** [comment]
I am using zsh, no matter bash/zsh, just add the environment variable, and **start Android studio from terminal**.

1. Use `/usr/libexec/java_home` to make sure your java directory is correctly as you expect.

2. Add to your .zshrc/.bash_profile environment variable.
```
export STUDIO_JDK=$(/usr/libexec/java_home -v '1.8*')
```

3. `open /Applications/Android\ Studio.app`

**Comment by edmundjohnson** [comment]
Thank you for the tips.  I got the same problem on upgrade to Android Studio 2.1.3. I edited "Android Studio.app/Contents/Info.plist" and changed JVMOptions/JVMVersion from "1.6*,1.7+" to "1.8*".  Now fixed.
