### ISSUE TITLE
com.intellij.ide.plugins.PluginManager$StartupAbortedException

### ISSUE THREAD

**Issue by ademcaliskan** [jshiell/checkstyle-idea#154]
Activating Plugin for the IDE aborts loading Projects while opening Projects. 

Error message:

Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA] [Plugin: CheckStyle-IDEA]

**Comment by jshiell** [comment]
Dup of #142. TL;DR you need to run IDEA on JDK 8.
