### ISSUE TITLE
Latest IDEA 14.1.2 EAP results in major.minor version error on startup

### ISSUE THREAD

**Issue by ctash** [jshiell/checkstyle-idea#155]
I updated to the latest EAP (build 141.588.1), and when I went to open my project I got the following error:
"Unsupported major.minor version 52.0"

![screenshot 2015-04-17 12 50 25](https://cloud.githubusercontent.com/assets/1537885/7207773/07f5ea10-e50a-11e4-8573-81753b9d3725.png)

**Comment by ctash** [comment]
It's also possible that this is due to switching the project over from Java 7 to 8.

**Comment by jshiell** [comment]
Dup of #142. TL;DR you need to run IDEA on JDK 8 - the project JDK has no effect on this.
