### ISSUE TITLE
CheckStyle rules file could not be loaded

### ISSUE THREAD

**Issue by karpoftea** [jshiell/checkstyle-idea#158]
Previously (sorry I dont remmember plugin version) I used file (http://rghost.ru/7LNwFVmyb) for checkstyle, but now I got: "The CheckStyle rules file could not be loaded. cannot initialize module TreeWalker - Unable to instatiate RedundantThrows"
gist with stackstrace: https://gist.github.com/karpoftea/ce96c1c2f65fe358d8a6
IDEA 14.1.2
CheckStyle 6.6

**Comment by mkordas** [comment]
RedundantThrows was removed with version 6.2 (https://github.com/checkstyle/checkstyle/issues/473). You need to remove that check from config.

**Comment by jshiell** [comment]
Thanks @mkordas!

**Comment by karpoftea** [comment]
thx!
