### ISSUE TITLE
Incompatible with Android Studio 1.2

### ISSUE THREAD

**Issue by marcoRS** [jshiell/checkstyle-idea#159]
Hello, I'm unable to install this plugin in Android Studio 1.2 . I get the following:

![screen shot 2015-04-30 at 12 12 29 pm](https://cloud.githubusercontent.com/assets/507510/7420561/572eee9c-ef32-11e4-9046-97d70b93bd11.png)

**Comment by jshiell** [comment]
Dup of #142. TL;DR you need to run Android Studio on JDK8. 

https://intellij-support.jetbrains.com/entries/23455956-Selecting-the-JDK-version-the-IDE-will-run-under
