### ISSUE TITLE
Problem with IntelliJ Idea 14.1.2 Ultimate

### ISSUE THREAD

**Issue by tunix** [jshiell/checkstyle-idea#160]
Whenever I try to open my project, it raises this problem.

![screen shot 2015-05-01 at 19 30 52](https://cloud.githubusercontent.com/assets/47731/7433316/ae50ec6e-f038-11e4-98fc-bffe4ae3560e.png)

**Comment by mkordas** [comment]
Duplicate of #142.

**Comment by tunix** [comment]
Ah, thanks! :)

**Comment by jshiell** [comment]
Thanks @mkordas  :smile:
