### ISSUE TITLE
IntelliJ 14.2 support

### ISSUE THREAD

**Issue by diogogmt** [jshiell/checkstyle-idea#161]
I'm not able to use the plugin with IntelliJ 14.2
The exception attached as an image is raised when I open any project
![screen shot 2015-05-04 at 12 55 53 pm](https://cloud.githubusercontent.com/assets/794765/7457750/ef734234-f25c-11e4-840d-908b7fbf29a8.png)

**Comment by jshiell** [comment]
Dup of #142 - TL;DR you need to run IDEA on Java 8.
