### ISSUE TITLE
Unsupported Intellij 14.1.3 ?

### ISSUE THREAD

**Issue by BalicantaYao** [jshiell/checkstyle-idea#165]
My Intellij version is **14.1.3**

After I install the checkstyle-idea , open Intellij will got bellow error

![error](https://cloud.githubusercontent.com/assets/7930390/7699505/eebd9ebc-fe4a-11e4-8306-5559e2a27ed8.png)

**Comment by jshiell** [comment]
Dup of #142. TL;DR run IDEA on JDK8.
