### ISSUE TITLE
Plugin exception while starting intellij

### ISSUE THREAD

**Issue by suyogkotecha** [jshiell/checkstyle-idea#167]
Hello,
I installed this plugin, but when restarted the IDE, I got plugin exception.
![screen shot 2015-06-01 at 2 32 57 pm](https://cloud.githubusercontent.com/assets/1765181/7923809/287114ca-086b-11e5-97ea-6f71c98856b8.png)
![screen shot 2015-06-01 at 2 33 11 pm](https://cloud.githubusercontent.com/assets/1765181/7923808/286dd850-086b-11e5-880d-eae540ea400a.png)

**Comment by jshiell** [comment]
Dup of #142 - you need to run IDEA on JDK8.
