### ISSUE TITLE
Cannot Load Project…Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA]

### ISSUE THREAD

**Issue by fantouch** [jshiell/checkstyle-idea#171]
![screen shot 2015-06-18 at 11 27 58](https://cloud.githubusercontent.com/assets/1577828/8223625/197765ce-15ad-11e5-9c83-416765da32e1.png)

**Comment by fantouch** [comment]
CheckStyle Version 4.16.0

**Comment by fantouch** [comment]
I try Java8, and found that font anti-aliasing was lost, UI looks so ugly.   
It seems that only Apple's Java6 support font anti-aliasing on my Retina iMac.
Finally I uninstall CheckStyle-IDEA

**Comment by jshiell** [comment]
Or you could read the docs and see that there’s a version of IDEA with a patched JDK to fix sub-pixel AA.

https://download.jetbrains.com/idea/ideaIU-14.1.3-custom-jdk-bundled.dmg
