### ISSUE TITLE
Do not check generated files

### ISSUE THREAD

**Issue by WonderCsabo** [jshiell/checkstyle-idea#172]
Generated files are not need to be checked, since they are not part of the source code of the project. Moreover, these files are likely to contain Checkstyle violations, since the code generators do not know anything about the project's Checkstyle rules. So this plugin should not scan generated sources, for example created by annotation processors, or the Android generated Java files etc.

**Comment by jshiell** [comment]
You can accomplish this via a [SuppressionFilter](http://checkstyle.sourceforge.net/config.html#SuppressionFilter) or a [SuppressionCommentFilter](http://checkstyle.sourceforge.net/config.html#SuppressionCommentFilter). AFAIK there's no way of detecting generated sources in a generic manner.

**Comment by WonderCsabo** [comment]
Well, this is possible without any further config in Maven, or eclipse-cs, so that is why i thought this is a reasonable request.

**Comment by WonderCsabo** [comment]
BTW, i think there must be a way: if the Java file is under the project output folder, then it is generated. I guess you can retrieve the location of the current file and the project output folder, don't you?

**Comment by WonderCsabo** [comment]
I have zero knowledge of the IntelliJ API, but i think `ProjectFileIndex.isInSource()` should tell you a file is generated or not.

**Comment by jshiell** [comment]
The problem with the IntelliJ API is it's an undocumented spaghetti mess, so your guess is as good as any. I'll have a look, and if it is that simple I can probably whip something together.

**Comment by WonderCsabo** [comment]
Thanks. I agree, the documentation is not really good...

**Comment by jshiell** [comment]
From the docs, it looks like you were very close indeed. `ProjectFileIndex.isInSource()` catches library source as well, but `isInSourceContent` appears to just deal with the current project.

I've added this to [a test build](https://dl.dropboxusercontent.com/u/5423904/checkstyle-idea-4.16.1.zip) - if you have the time, I'd greatly appreciated it if you could try it out and see if it solves your problem. Thank you!

**Comment by WonderCsabo** [comment]
Thanks! How can i build a plugin which i can install to my IntelliJ (as i said i am am totally an IntelliJ plugin dev noob)?

**Comment by jshiell** [comment]
If you go to Preferences and then the Plugins panel, there should be an *Install from Disk* button.

If that doesn't work, If you're on OS X, you can just extract the JAR file to `~/Library/Application Support/IntelliJIdea14`. You may not even have to extract it, tbh. It should be similar on Linux/Win, but I'm not sure where the plugin directories are from those OSs.

**Comment by WonderCsabo** [comment]
Sorry I am on write only mode, i just opened the link and I see it is the plugin binary... I will test it tomorrow.

**Comment by WonderCsabo** [comment]
It seems it does not work. :( I have a gradle project, which has generated files under *build/generated/sources/apt/debug*, and Checkstyle-IDEA scans them in the Checkstyle Scan toolbar.

**Comment by jshiell** [comment]
Bugger. Does IDEA set the *build/generated/sources/apt/debug* directory as a source directory in the project settings?

**Comment by WonderCsabo** [comment]
Yeah, it does.

**Comment by jshiell** [comment]
That's the problem, then. The method call just checks whether it's in a directory that IDEA considers a source or test directory. So it's considered a valid source file.

**Comment by WonderCsabo** [comment]
Can't you check the build output?

**Comment by jshiell** [comment]
Not sure, tbh. That stuff is pretty generic these days with the support for multiple build tools. I'll have a look, probably this weekend.

**Comment by WonderCsabo** [comment]
Okay, thanks. Yeah, this plugin must support multiple build tools.

**Comment by jshiell** [comment]
IDEA abstracts all of that, thankfully. So it's just a question of how easily I can drill into output directories. The answer is probably 'yes'. I hope :smile:

**Comment by jshiell** [comment]
[I've uploaded a second test build](https://dl.dropboxusercontent.com/u/5423904/checkstyle-idea-4.17.1.zip) that attempts to filter out files that are in an output directory. 

If this one still doesn't work, do you have a test case project I could play with, so I can stop nagging you on every test build? :smile:

**Comment by WonderCsabo** [comment]
It seems it is still not working. You can try this [test project](https://github.com/excilys/androidannotations/tree/develop/examples/gradle).

**Comment by jshiell** [comment]
Thanks. Looking at the project structure of *functional-test-1-5*, the problem appears to be that IDEA considers the output path to be *target/classes*, while the source is generated to *target/generated-sources*. While Maven knows that the content of *target* is all build related, IDEA doesn't appear to track that (i.e. it's only concerned with certain paths within it).

So assuming I'm not missing something, checking the build paths won't allow us to catch this case.

**Comment by WonderCsabo** [comment]
@jshiell i linked the small Gradle example project, but `functional-test-1-5` is the same in manner of this issue. Well, i always suggested to retrieve the root of the output (`target` or `build`) and assume everything under it generated.

**Comment by jshiell** [comment]
Sorry, the test project didn't import cleanly as I don't have an Android SDK downloaded, and I wanted to give it a quick try before I head out for the afternoon :smile: 

The problem is that while assuming the parent of the output is a *target*/*build* directory will work with default Maven/Gradle setups, it's not guaranteed to work with other builds tool, or even custom Maven layouts. To keep cross compatibility it needs to work with what IDEA provides rather than making assumptions about the build layout.

**Comment by WonderCsabo** [comment]
@jshiell that is correct. The only way is to call the IDEA maven/gradle plugin if needed. :(

**Comment by jshiell** [comment]
Third time's the charm - (test build)[https://dl.dropboxusercontent.com/u/5423904/checkstyle-idea-4.17.1.zip]. This time I played in the debugger and found an API for generated files. It's Java specific (or at least the API naming implies it is), but seems to work with the example Gradle project. Could you give it a bash when you've a tick please, and let me know if it's doing what you're after? Thanks.

**Comment by WonderCsabo** [comment]
I checked in two big projects, a Gradle and a Maven project. It seems it is working (generated classes were skipped, but "normal" classes were checked).
Thanks @jshiell for your toughness on fixing this issue! :+1:

**Comment by jshiell** [comment]
My pleasure - thanks for your help in solving it!
