### ISSUE TITLE
StartupAbortedException with IntelliJ 14.1.4 and CheckStyle-IDEA 4.17.2

### ISSUE THREAD

**Issue by cykedev** [jshiell/checkstyle-idea#174]
Hi,

I'm getting a StartupAbortedException with IntelliJ 14.1.4 and CheckStyle-IDEA 4.17.2.

![image002](https://cloud.githubusercontent.com/assets/6008973/8691805/d94d6ec8-2ac7-11e5-92e4-2740b0375d0d.png)

With 4.13.2 everything works fine ...

Regards
Christian

**Comment by jshiell** [comment]
Dup of #142 - you need to run IDEA on JDK8. For the Mac, there's a bundled installer linked in #142.
