### ISSUE TITLE
IDE crash

### ISSUE THREAD

**Issue by jonathanlermitage** [jshiell/checkstyle-idea#175]
Hi,
IDE regularly crashes if launched in 32-bits mode (it simply exits without any error message).
Also, can't launch IDE in 64-bits mode if plugin installed (incompatible major version).

IntelliJ IDEA 14.1.4 on Windows 7 SP1 x64.

Regards,

**Comment by jshiell** [comment]
Dup of #142 - ensure you're running IDEA on JDK 8. 

No idea what's up with 32bit mode, and given there's no 32bit JVM for OS X I can't see me finding out :smile:
