### ISSUE TITLE
Setting basedir property prevents checks from running

### ISSUE THREAD

**Issue by ARoundSquare** [jshiell/checkstyle-idea#183]
Using a simple checkstyle file

`
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.2//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_2.dtd">
<module name="Checker">
    <property name="basedir" value="${basedir}"/>
    <module name="TreeWalker">
        <module name="AvoidStarImport"/>
        <module name="IllegalImport"/> 
        <module name="RedundantImport"/>
        <module name="UnusedImports"/>
    </module>
</module>
`

Causes the plugin to report "Checkstyle found no problems in the file(s)"

Looking through the plugin logs, the culprit seems to be [here](https://github.com/jshiell/checkstyle-idea/blob/0f37d3dfa3e015be7892955b344750bf6bf59a3b/src/main/java/org/infernus/idea/checkstyle/checker/CheckStyleAuditListener.java#L104)

> 2015-08-31 23:50:55,863 [1770910]   INFO - hecker.CheckStyleAuditListener - Could not find mapping for file: src/Main.java in {/Users/seankim/projects/Foo/src/Main.java=PsiJavaFile:Main.java} 

This is after setting the basedir property to `/Users/seankim/projects/Foo`, but even setting it to just `/` seems to cause it to fail.

**Comment by jshiell** [comment]
At a guess this would be due to `basedir` altering the error messages and hence it being unable to find the file indicated in the message. I'll run it up in a debugger when I get a chance.

Thanks for the report.

**Comment by Moritz90** [comment]
I was wondering why the plugin didn't seem to do anything at all. This explains a lot…

**Comment by jshiell** [comment]
Many apologies - this completely slipped my mind. Mea culpa.

It should be fixed in 4.27.4. Thanks for your reports!
