### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by champgm** [jshiell/checkstyle-idea#188]
I installed this plugin today, but it seems that IntelliJ can't open any projects with it installed. Am I doing something wrong and is there a way to work around this? 

![screen shot 2015-09-30 at 1 30 24 pm](https://cloud.githubusercontent.com/assets/2091382/10202651/89c48494-6777-11e5-8eff-b5738cd2d67d.png)

**Comment by jshiell** [comment]
You need to run IDEA (not your project) on JDK 8. There are links to the 
bunbled Mac builds of IDEA on http://github.com/jshiell/checkstyle-idea

Dup of #142.

**Comment by champgm** [comment]
Got it, thanks!
