### ISSUE TITLE
Release checkstyle 6.11.2 version in order to support Lambda indentation

### ISSUE THREAD

**Issue by uschi2000** [jshiell/checkstyle-idea#189]
Hej,
The latest checkstyle version supports Lambda indentation, would be great to get a release with support for it.
Cheers!
  Robert

**Comment by jshiell** [comment]
I'll try get it sorted this weekend :smile:

**Comment by uschi2000** [comment]
Nice, thanks!

**Comment by jshiell** [comment]
Released as 4.20.0, please shout if you have any problems!

**Comment by uschi2000** [comment]
Smooth, thanks!
