### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by davidlinse** [jshiell/checkstyle-idea#195]
I'm facing some problems with this plugin (especially when changing branches) on IDEA 14.1.5 Ultimate.
Please have a look at this [gist](https://gist.github.com/davidlinse/df49223ce2d478cf5c3d#file-checkstyle-idea-incompatible-class-change-error-txt) for a stacktrace.

The 'Event Log' shows repeating `11:49:06 AM IncompatibleClassChangeError: No message` entries.

regards
~david

**Comment by jshiell** [comment]
Colour me confused. As I understand `java.lang.IncompatibleClassChangeError`, it should only be seen where a class definition changes after compile time. Given the source is entirely static and doesn't use CGLib or such, this seems curious.

One possibility is that the IDEA SDK has changed in some backwards incompatible way. This would not be a complete surprise. I'll try and have a look at this during the weekend.

Another option is pollution from another plugin. Could you please tell me your OS, your IDEA JDK and any other plugins you may have installed? Thank you.

**Comment by jshiell** [comment]
Hmm. Actually the SDK seems unlikely, given the most recent build should have been made against IDEA 14.1.5 Ultimate (141.2735) on OS X. I'll keep thinking.

**Comment by davidlinse** [comment]
I'll have a look tomorrow and send you the requested infos.

regards
~david

**Comment by davidlinse** [comment]
Hi, sorry for the late reply. Here are some more infos
OS: OS X Yosemite 10.10.5

Maven 3 (bundled)
IntelliJ JRE: Using internal JRE 1.8-ea, targeting 1.7
Plugins:
* Ant Support
* Atlassian Connector
* Copyright
* Eclipse Code Formatter
* EditorConfig
* Git
* Gradle / Groovy
*Junit
* Markdown
* Maven Integration + Extension

and a few other.. 
Let me know if i can provide more details or infos.

regards
~david

**Comment by jshiell** [comment]
Sorry to say that, even after all this time, I still haven't managed to reproduce this. Looking into it further it feel to be something internal to the JVM - I can't see anyway this would be related to the plugin class path, and it looks like the JVM lambda parsing is failing horribly when accessing the lambda on that line.
```
return asProblemDescriptors(asyncResultOf(() -> inspectFile(psiFile, manager), NO_PROBLEMS_FOUND), manager);
```
When you say JRE 1.8-ea, is that actually one of the early access builds? If so, I'd strongly recommend updating to 1.8.0_40 or above - there were certainly some lambda bugs in the early release builds that we hit at work, and Jetbrains seem to have settle on 1.8.0_40 b132 for their bundled JVM.

**Comment by davidlinse** [comment]
Ok, I'll update the early access build and check then again.

regards
~david

**Comment by jshiell** [comment]
Closed due to no further updates.
