### ISSUE TITLE
Plugin does not work with IntelliJ 15.0.1 (143.382)

### ISSUE THREAD

**Issue by cheshire** [jshiell/checkstyle-idea#204]
Hi,

I'm running Ubuntu Trusty Tahr + OpenJDK 1.7 + IntelliJ 15.0.1 (143.382)
After installing the plugin and opening the existing project I consistently get the error message:

```
com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA] [Plugin: CheckStyle-IDEA]
```

**Comment by jshiell** [comment]
You'll need to run IDEA on JDK 1.8 - there's lots of info on #142.
