### ISSUE TITLE
Support for IntelliJ 15?

### ISSUE THREAD

**Issue by kryoflux** [jshiell/checkstyle-idea#205]
Just a question really. Is the current checkstyle-idea likely to support IntelliJ 15? It seems to work when I run it explicitly, but for some reason, I can't get the inspection part to work (just doesn't highlight any code).

I wasn't sure if this was a problem with v15 support, or perhaps because I'm running on Windows.

Just evaluating this at the moment, but it looks really great for my team, where I don't want to fail the build on this sort of thing (that seems too much), just to "gently encourage" compliance. :)

Thanks for your effort!

**Comment by jshiell** [comment]
I fear it does already support 15 :smile: - I haven't run into (or had reported) any problems with in on 15.0.2, at the least. And while I'm not running Windows, there's plenty of people running the plugin who do use Windows and I've no current reason to believe it's broken for them. All of which is not to imply it couldn't be a bug, of course!

Quick sanity check - is the inspection active? *Preferences* -> *Editor* -> *Inspections* -> *Checkstyle* -> *Checkstyle real-time scan* will need to be ticked and have an appropriate severity set. Sometimes it seems to get knocked off, so worth a check.

**Comment by kryoflux** [comment]
Hi, thanks for the help. Yes, it's good to check, but it's definitely on.

However, I pushed a few more buttons, and finally got it working. The problem seems to be when I use our own customised inspection profile. If I reset everything back to the defaults, and then only select the checkstyle inspection, it works.

I'll see if I can turn a few off/on to identify the incompatible inspection, if that is what the problem is anyway...

**Comment by kryoflux** [comment]
Okay, I found the problem. For some reason I had the IntelliJ setting "Disable new inspections by default" checked (not sure why, I would usually want them to update). I think that feature must have some kind of (IntelliJ) bug, because even though it looked enabled in the inspection UI (the default), it wasn't in the XML, and was clear it wasn't active.

Turning that feature off fixed it, and it works great now. Thanks!

**Comment by jshiell** [comment]
I didn't even realise that feature existed! My pleasure, glad to be of help :smile:
