### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/beanutils/ConvertUtilsBean

### ISSUE THREAD

**Issue by ethankhall** [jshiell/checkstyle-idea#206]
I get this error when running on IDEA Ultimate 15.0.2.

```
org/apache/commons/beanutils/ConvertUtilsBean
java.lang.NoClassDefFoundError: org/apache/commons/beanutils/ConvertUtilsBean
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.createBeanUtilsBean(AutomaticBean.java:66)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:153)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:131)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.createCreater(CheckerFactoryWorker.java:61)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:49)
```

The dialog says that its happened over 100 times. Let me know if there is anything you want me to do to help debug.

**Comment by jshiell** [comment]
Looks like a dependency of Checkstyle is missing from the plugin package. I'll try get it sorted this weekend.

Thanks for the report!

**Comment by jshiell** [comment]
Hmm, not that easy. Looking at the list for 4.22.2 (which I presume is what you're using) the commons-beanutils JAR is present and at the correct version.

Could you please attach your rules file and I'll try reproduce it locally?

**Comment by ethankhall** [comment]
Oh. It looks like I'm using 4.22.0. Let me try with the latest version

**Comment by ethankhall** [comment]
I've upgraded and didn't see it immediately. I'll poke around for a week to see if it pops back up, until then I'll close the ticket.

**Comment by jshiell** [comment]
Fingers crossed :smile:

**Comment by ethankhall** [comment]
Reporting back: looks like upgrading to the latest version fixed the issue :-)

**Comment by jshiell** [comment]
Excellent news - thanks for the feedback!
