### ISSUE TITLE
Cannot load project after installation of plugin

### ISSUE THREAD

**Issue by dannysuen** [jshiell/checkstyle-idea#207]
![default](https://cloud.githubusercontent.com/assets/806703/12226628/dde4a800-b859-11e5-940b-f91a69deaa0b.jpg)

**Comment by jshiell** [comment]
I'll need some more context, please; there seems to be a scrollbar there - what's the rest of the message?Also, version / OS / JVM please?

**Comment by caseyscarborough** [comment]
This issue happened for me as well:

```
Cannot load project:
com.intellij.ide.plugins.PluginManager$StartupAbortedException:
com.intellij.diagnostic.PluginException:
org/infernus/idea/checkstyle/CheckStylePlugin:
Unsupported major.minor version 52.0
[Plugin: CheckStyle-IDEA] [Plugin: CheckStyle-IDEA]
```

I resolved it by switching IntelliJ to run using JDK 8 per this article:
https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under

**Comment by jshiell** [comment]
Ah yes, well documented at #142 - cheers :-) I'll assume the original was the same issue and close this, since no further info has been forthcoming.
