### ISSUE TITLE
Config is downloaded even when the active configuration file is local

### ISSUE THREAD

**Issue by curobosqui** [jshiell/checkstyle-idea#212]
The scenario: there are several configuration files setup (a local one and a remote http one), and a local one is marked active.

Behavior: The configuration file is still downloaded from the http server even though it's not the active one. (This is evident when the server is down and there's still ConnectionException errors reported.)

Expected behavior: The configuration file is not downloaded if it's not marked active.

Using plugin version 4.23.0 and AndroidStudio 1.5.1

**Comment by jshiell** [comment]
Apologies for the delay.

This turned out to be some old and hairy code which was rather over-paranoid about keeping property values in sync. It should now only do this when in the configuration panel, and should hence only query the active file. 

Fixed in 4.25.2.
