### ISSUE TITLE
Commit Changes: "Scan with Checkstlye" checkbox state is not persisted

### ISSUE THREAD

**Issue by frimtec** [jshiell/checkstyle-idea#216]
The state of the checkbox "Scan with Checkstlye" in the commit dialog is not persisted.
After an IDEA restart the checkbox is always untagged.

Plugin Version: 4.25.1
IDEA Version: 15.0.3

**Comment by jshiell** [comment]
This will be fixed in 4.25.2 - thanks for the report!

**Comment by frimtec** [comment]
Great, many thanks for the prompt fix :-)
