### ISSUE TITLE
Predefine config_loc property

### ISSUE THREAD

**Issue by baron1405** [jshiell/checkstyle-idea#217]
We have a Checkstyle configuration file that is shared between Eclipse and IntelliJ IDEA. The eclipse-cs Checkstyle plugin predefines the config_loc property to be the absolute path to the Checkstyle configuration file being read. That allows doing things like specifying the location of the suppressions.xml file using that property. We use that property for this purpose in our Checkstyle config file. It would be very helpful to have this property predefined by Checkstyle-IDEA. That way there is consistency across two major IDE's allowing easy sharing of the config file without the need to tell developers to set this property when they open a project.

**Comment by jshiell** [comment]
This is a great idea - there's a few of them beyond just `config_loc`, so seems sensible to add them all. I'll try have a look later this weekend - thanks!

> ${basedir} & ${project_loc} - gets mapped to the current project directory
> ${workspace_loc} - gets mapped to the current Eclipse workspace directory
> ${config_loc} & ${samedir} - get mapped to the directory the configuration file lies in

**Comment by jshiell** [comment]
Now present in 4.26.0 - thanks for the suggestion!

**Comment by baron1405** [comment]
Thank you so much for hearing me out and the quick turnaround!

**Comment by tsjensen** [comment]
Thanks, great feature! :+1:
