### ISSUE TITLE
Upgrade to Checkstyle 6.16.1

### ISSUE THREAD

**Issue by kevinconaway** [jshiell/checkstyle-idea#220]
@jshiell Is it possible to update this plugin to the latest version of checkstyle (6.16.1)?

The latest version has fixes for an annoying bug with Lambdas + Indentation:

https://github.com/checkstyle/checkstyle/issues/281

Thanks.

**Comment by jshiell** [comment]
I'll try and get this sorted over the weekend.

**Comment by jshiell** [comment]
I went one better and jumped straight to 6.17! Released as 4.27.0 - enjoy :smile:
