### ISSUE TITLE
After excluding a module, I can't scan the project

### ISSUE THREAD

**Issue by Ricket** [jshiell/checkstyle-idea#221]
I installed Checkstyle-IDEA 4.27.0, went to the main Checkstyle settings and enabled "Scan test classes" and added our custom Checkstyle xml file. We have a multi-module project. I opened the CheckStyle window and clicked the "Check Project" button, and it found many errors in one module which we treat differently from the others (it's an imported third party library, so we don't enforce our style check on it).

So I opened that module group's settings and for each of its modules, selected "Exclude this module from all checks". Then when I run "Check Project" it simply says "No rules file has been configured". I enabled all but one module and still the same thing. When I enable all modules then it returns to the previous behavior of correctly scanning and finding errors.

**Comment by jshiell** [comment]
In order to create a test case, could you please give me an idea of the module layout of your project? Were they manually created modules, or imported from Maven/Gradle/whatever? And what version of IDEA are you using? Thanks.

**Comment by jshiell** [comment]
Closed due to no further updates.
