### ISSUE TITLE
${basedir} behaves differently than in eclipse-cs

### ISSUE THREAD

**Issue by bill-okara** [jshiell/checkstyle-idea#223]
Hi,

First of all, thanks very much for developing this plugin!

When trying to implement the checkstyle ImportControl for a multi-modules project with the following configuration, with Eclipse-cs, when running the checkstyle configuration against a submodule (select submod1, right-click to select checkstyle - run check), the ${basedir} will be correctly pointed to the submod1 (that is, eclipse-cs will correctly locate the '${basedir}/checkstyle/import-control.xml' specified in the checkstyle.xml, by pointing the ${basedir} to submod1)

but with checkstyle-idea, the $(basedir) seems always points to $PRJ_DIR$? should ${basedir} be automatically point to the project module/submodule whenever that module is being processed?

```
/root/projectA
          |-- pom.xml
          |-- checkstyle.xml
          |-- submod1
          |         |-- pom.xml
          |         |-- checkstyle/import-control.xml   // import control specific to submod1 packages
          |-- submod2
          |         |-- pom.xml
          |         |-- checkstyle/import-control.xml  // import control specific to submod2 packages

```         
checkstyle.xml

```
<module name="Checker">
    <module name="TreeWalker">
        <module name="ImportControl">
            <property name="file" value="${basedir}/checkstyle/import-control.xml"/>
        </module>
    </module>
</module>

```

Thanks!
Bill

**Comment by jshiell** [comment]
Thanks very much for your report and your kind words!

If the behaviour differs then I've obviously misinterpreted the docs - mea culpa :smile: I'll correct this, hopefully later this weekend.

**Comment by jshiell** [comment]
IDEA doesn't seem to offer an obvious way to get the module root. As such, it's actually mapping it to the directory of the module file, which should hopefully be sufficient in most cases. I hope.

It'll be in 4.27.1; in the meantime, there [a test build on Dropbox](https://dl.dropboxusercontent.com/u/5423904/CheckStyle-IDEA-4.27.1.zip).

**Comment by bill-okara** [comment]
Thank you very much for the swift fix!

just tested by running the checkstyle config file against different modules and the ${basedir} now points to the loaded module correctly! (behave similarly as in eclipse-cs)

Thanks again!
Bill

**Comment by jshiell** [comment]
My pleasure, thanks for the confirmation!
