### ISSUE TITLE
'The file has been blacklisted for 60s' error

### ISSUE THREAD

**Issue by mmoayyed** [jshiell/checkstyle-idea#224]
Is there a particular reason the rule file goes inactive for 60s when it's maladjusted? Can this timeout be configurable? If I for instance, have a small typo in the config, and can fix it immediately, why should I have to wait for a minute in order to refresh the config?

**Comment by jshiell** [comment]
It's to stop it spamming errors while the file is in an error state.

There's a refresh button on the panel that should trigger an immediate re-read of the configuration files for cases like this. If that's not working, please raise a bug and I'll sort it.

**Comment by mmoayyed** [comment]
You're welcome to change the title of this issue and reopen it, because that refresh icon seems to have no effect. When I click on the icon, nothing really happens. When I attempt to run the check, the CS pane flashes very quickly and I see the same error message. The only workaround is to wait 60 seconds.

**Comment by mmoayyed** [comment]
In summary, if the file is blacklisted it seems like all ops on the file are suspended until the period has passed. 

If the wait period is designed to block spamming errors in the events pane CS inspections run, what would be better is if you disable the inspection and reenable it if possible when the file is back in shape. Remove the block/wait period altogether. I personally find it very annoying and am forced to not use the plugin when I am trying to edit the CS rules file.

**Comment by jshiell** [comment]
Check style isn't designed for use by tools, so we get a lot of entirely legit errors as exceptions. Unfortunately, we also get failures as exceptions. As such, there's no great way to pick out temporary from permanent errors. And given many people use multiple configuration files, it's impossible to just disable the entire check for the duration. So I've no plans to change the behaviour. However, I'll try have a look at the refresh button issues at some point, as that should clear blacklisting.

**Comment by jshiell** [comment]
Resolved in 4.27.2.
