### ISSUE TITLE
No errors in editor with latest IDEA and plugin

### ISSUE THREAD

**Issue by EgorZhuk** [jshiell/checkstyle-idea#229]
Hello @jshiell ,

Thank you for the work you do.

I faced an issue after updating IDEA and plugin to the latest versions - errors disappeared from editor but are still present in checkstyle scan.
[Please see the screenshot](https://yadi.sk/i/ArPkYMAmrmR3D)

**Comment by EgorZhuk** [comment]
Seeems to be local issue.

**Comment by jshiell** [comment]
Thanks for the kind words!
