### ISSUE TITLE
Lexicographical order of imports is case-sensitive when it shouldn't be

### ISSUE THREAD

**Issue by jclc** [jshiell/checkstyle-idea#230]
Using unmodified Google checkstyle, checkstyle-idea thinks "import java.io.IOException;" should be before "import java.io.InputStream;" while Maven's checkstyle plugin detects the correct order.

**Comment by jshiell** [comment]
What does the command line Checkstyle do? The IDEA plugin doesn't apply any logic, it just reports the errors fed back, and hence should match the output of the official (command line) client.

**Comment by jclc** [comment]
`mvn checkstyle:check` passes when the order is non-case-sensitive. When using the order that checkstyle-idea suggests, it fails with:
```
[INFO] --- maven-checkstyle-plugin:2.16:check (default-cli) @ tmc-cli ---
[INFO] There is 1 error reported by Checkstyle 6.2 with /home/ad/fshome2/u2/j/jclakkis/Linux/projects/tmc-cli/src/main/resources/google_checks.xml ruleset.
[ERROR] src/main/java/fi/helsinki/cs/tmc/cli/Application.java[25] (imports) CustomImportOrder: Wrong lexicographical order for 'java.io.InputStream' import.
```

**Comment by jshiell** [comment]
What about the the official client? i.e. http://checkstyle.sourceforge.net/cmdline.html

I've no idea what the Maven plugin does additionally; the IDEA plugin aims to reproduce the official command line behaviour. 

If the official client works as you expect, this is a bug and I'll have a look at it.

**Comment by jclc** [comment]
Apparently the official checkstyle client agrees with checkstyle-idea, it seems that we may have misconfigured our Maven plugin. Sorry for the inconvenience.

**Comment by jshiell** [comment]
No worries whatsoever - just glad you've got a solution!
