### ISSUE TITLE
check style can not work in Android studio 2.1.2

### ISSUE THREAD

**Issue by hexiaofengIjiazu** [jshiell/checkstyle-idea#232]
check style can not work in Android studio 2.1.2, please check it ,thanks

**Comment by jshiell** [comment]
I don't use Android Studio, so unless you can give me more information I fear there's going to be nothing happening on this front.

**Comment by hexiaofengIjiazu** [comment]
A dialog show :   unsupported major.minor version 52.0

**Comment by jshiell** [comment]
You need to run Android Studio on JDK 8 or above.

https://intellij-support.jetbrains.com/hc/en-us

**Comment by hexiaofengIjiazu** [comment]
Thanks , It works in JDK 8, Thanks all.
