### ISSUE TITLE
Why it's not supported in AndroidStudio 64

### ISSUE THREAD

**Issue by QinAndroid** [jshiell/checkstyle-idea#234]
i really love this plugin,but there are something wrong when i use it in my developTool AndroidStudio,it's not supported in AndroidStudio64,it's waste me a lot of time,so i advice some other deveploers when your development tool is AndroidStudio 64,replace it to 32,is anyone has some better advice to impove this question

**Comment by jshiell** [comment]
Why doesn't it work? What error do you get? You're giving me nothing to work with here.

**Comment by QinAndroid** [comment]
@jshiell After i install the plugin in AndroidStudio64,it tips me the message as follow:
Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: org/infernus/idea/checkstyle/CheckStylePlugin : Unsupported major.minor version 52.0 [Plugin: CheckStyle-IDEA] [Plugin: CheckStyle-IDEA]
i didn't konw why is it,but when i change my tool to AndroidStudio 32,it's ok,and i can use this plugin

**Comment by jshiell** [comment]
The plugin requires your IDE to be running on JDK8 or above. If you switch the IDEA SDK to JDK8 or above then it should be fine.

There's more information in this issue: https://github.com/jshiell/checkstyle-idea/issues/142
