### ISSUE TITLE
it is needed java 8?

### ISSUE THREAD

**Issue by tracy1allen3** [jshiell/checkstyle-idea#235]
i use android studio v-2.1.1,when install this plugin,it is error, can not load project.
many solutions from internet show me it is needed java 8. right?
it is the only way ?
how can i work with java 7?

**Comment by jshiell** [comment]
You need to run Android Studio on Java 8. You can still use Java 7 in your project.

There is no way to get the plugin working when the IDE is running on Java 7.

**Comment by tracy1allen3** [comment]
thanks
