### ISSUE TITLE
RequireThis not supported

### ISSUE THREAD

**Issue by cradix** [jshiell/checkstyle-idea#236]
I added the following lines in my configuration file : 
  <module name="TreeWalker">
    <module name="RequireThis">
	  <property name="severity" value="warning"/>
	</module>	

And IntelliJ Checkstyle plugin doesn't found any error while the configuration is correctly taken into account by Sonar.

**Comment by jshiell** [comment]
Looks like a copy & paste error - could you please update this with the line in question?

**Comment by cradix** [comment]
Sorry, here the configuration extract :
`  <module name="TreeWalker">
    <module name="FileContentsHolder"/>
    <module name="SuppressWarningsHolder"/>	
    <module name="RequireThis">
	  <property name="severity" value="warning"/>
	</module>`

**Comment by jshiell** [comment]
Thanks, and thanks for the report! I'll do my best to have a look at this over the weekend.

**Comment by jshiell** [comment]
I'm not able to reproduce this using the latest plugin version and IDEA 15.0.6.

Using the rules file:
```<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">

    <module name="TreeWalker">
        <module name="RequireThis"/>
    </module>

</module>
```

And the test file:
```
public class Issue236 {
    private String boo = "boo";

    public void hello() {
        String boo = "boo2";
        boo = boo;

    }
}
```

I get `Reference to instance variable 'boo' needs 'this.' (8:9)`. This matches the output from `checkstyle-6.19-all.jar` on the command line as well.

I also tried with `validateOnlyOverlapping` turned off, and again the output consistently matched the output from `checkstyle-6.19-all.jar`.

Can you see anything I'm doing differently from you which may be leading to the discrepency?

**Comment by cradix** [comment]
Hello,

Here is my complete Checkstyle configuration file, maybe you will be able to reproduce with it :

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
	<module name="SuppressionCommentFilter"/>
	<module name="SuppressWarningsFilter"/>
	<module name="TreeWalker">
		<module name="FileContentsHolder"/>
		<module name="SuppressWarningsHolder"/>
		<module name="ClassDataAbstractionCoupling">
			<property name="severity" value="error"/>
			<property name="max" value="20"/>
		</module>
		<module name="FinalClass">
			<property name="severity" value="warning"/>
		</module>
		<module name="FinalLocalVariable">
			<property name="severity" value="warning"/>
			<property name="tokens" value="VARIABLE_DEF"/>
			<property name="validateEnhancedForLoopVariable" value="false"/>
		</module>
		<module name="JavaNCSS">
			<property name="severity" value="warning"/>
		</module>
		<module name="MissingOverride">
			<property name="severity" value="warning"/>
		</module>
		<module name="MultipleVariableDeclarations">
			<property name="severity" value="warning"/>
		</module>
		<module name="RedundantModifier">
			<property name="severity" value="info"/>
			<property name="tokens" value="METHOD_DEF,VARIABLE_DEF,ANNOTATION_FIELD_DEF,INTERFACE_DEF,CTOR_DEF,CLASS_DEF,ENUM_DEF"/>
		</module>
		<module name="RequireThis">
			<property name="severity" value="warning"/>
		</module>
	</module>
</module>
```

**Comment by jshiell** [comment]
Thanks both - I'll try and chase this over the weekend!

**Comment by jshiell** [comment]
There's good news and bad news - I can reproduce it with your example, which is great. However, it seems to be a problem with Checkstyle 7. We don't see the audit events for the problem, and when I put a debugger in the `RequireThisCheck` class it shows it's never triggering an error.

It reproduces for me with Checkstyle 7 on the command line with your class (although my test class is fine, so there's obviously some subtlety here that's triggering it):
```
$ java -jar ~/Downloads/checkstyle-7.0-all.jar -c ../../checkstyle-idea/test-configs/issue-236b.xml Issue236.java
Starting audit...
[ERROR] /Users/jshiell/Projects/JavaPlayground/src/Issue236.java:7:5: Definition of 'equals()' without corresponding definition of 'hashCode()'. [EqualsHashCode]
Audit done.
Checkstyle ends with 1 errors.
```

Could you please verify that the [Checkstyle 7 JAR](https://sourceforge.net/projects/checkstyle/files/checkstyle/7.0/checkstyle-7.0-all.jar/download) also produces the same result for you? If so, please raise a bug with the [Checkstyle project](http://github.com/checkstyle/checkstyle/issues) (I had a quick look but couldn't see anything there already). If not, please shout!

**Comment by smilix** [comment]
Yes, I get the same result as you. I'll create a bug ticket there.

**Comment by smilix** [comment]
I found the problem. It seems that the Checkstyle Project introduced a new property for this check: http://checkstyle.sourceforge.net/config_coding.html#RequireThis 
"validateOnlyOverlapping"
I think the default value for this was a bad decision, because it breaks every old config without this property set to false....

TLDL: 
Add 
```xml
<property name="validateOnlyOverlapping" value="false" />
```
and be fine.

**Comment by jshiell** [comment]
Good find, thanks for the update!

I agree, it's an unfortunate way to approach the problem, as it'll catch many people unawares (like us). C'est la vie.
