### ISSUE TITLE
Default property values not honored

### ISSUE THREAD

**Issue by baron1405** [jshiell/checkstyle-idea#237]
I have a property defined in my checkstyle.xml file with a default value:

`<property name="severity" value="${checkstyle.severity}" default="warning"/>`

If I do not explicitly define a value for the `checkstyle.severity` property in the configuration dialog, I get complaints from the plugin that it cannot process the configuration file, failed checkers, stack traces, etc. So it appears that the default value for the property is not being honored.

**Comment by jshiell** [comment]
Thanks for the report. I've just pushed 4.29.1 which should fix this - it looks like the property resolver was trying to be helpful and make it clear when a property was undefined - unfortunately this led to a fake value being set, and the default hence being ignored. The property resolver will now return null, as you'd expect, and Checkstyle should return a default value if present.

**Comment by baron1405** [comment]
Thanks for the quick turnaround on this issue!
