### ISSUE TITLE
Optimizing imports not overridden by checkstyle rule CustomImportOrder

### ISSUE THREAD

**Issue by stroeller** [jshiell/checkstyle-idea#238]
We have imported our checkstyle rules into Intellij , to ease auto-formatting and optimizings imports. But unfortunately the below CustomImportOrder rules is overriden with whatever settings is in Intellij.

`<module name="CustomImportOrder">`
`<property name="specialImportsRegExp" value="se.samtrafiken"/>`
`<property name="sortImportsInGroupAlphabetically" value="true"/>`
`<property name="customImportOrderRules" value="STATIC###STANDARD_JAVA_PACKAGE###THIRD_PARTY_PACKAGE###SPECIAL_IMPORTS"/>`
`</module>`

The above rule gives this error message (which is correct)
![cs-imports](https://cloud.githubusercontent.com/assets/20083889/16259120/72a2de9e-3861-11e6-90af-7f5f6baab41e.png)

Intellij is set to, which unfortunately doesn't get overridden by the above rule.
![cs-imports-default](https://cloud.githubusercontent.com/assets/20083889/16259133/812a38cc-3861-11e6-9bf1-1bc4a92c2a3e.PNG)

but if we rearrange the order in Intellij we get the expected result when pressing Ctrl-Alt-O
![cs-imports-rearranged](https://cloud.githubusercontent.com/assets/20083889/16259165/a0f736d2-3861-11e6-9b10-a15657166643.PNG)

**Comment by jshiell** [comment]
Thanks for the report. However, I fear the importer was a contribution from @dyadix, rather than something I use/implemented, and it looks like `CustomImportOrder` wasn't covered. So while I'll add it to the todo list, I fear it's not a high priority for me to fix at present (contributions are very welcome though).

**Comment by zentol** [comment]
I don't think one can provide a reasonable Importer implementation for the `CustomImportOrder` module.

For one the `SAME_PACKAGE(X)` rule cannot be mapped to CodeStyle settings in IntelliJ.

More importantly however this module works with regular expressions, which again cannot be mapped to Intellij. It could only work if all matches for the regex could be reduced to a series of `a.b.*` import statements, but at that point you could just as well use the `ImportOrder` module.

**Comment by jshiell** [comment]
*All* the importers are best case, mind, as there's a number of things that don't map cleanly. If we can get closer to a map, that's a win, although I fear we're never going to be perfect.

**Comment by stroeller** [comment]
Ok. From our perspective this issue can be closed.

**Comment by jshiell** [comment]
Thanks 😄
