### ISSUE TITLE
wrong place lights error - lights shifted to the left

### ISSUE THREAD

**Issue by BorzdeG** [jshiell/checkstyle-idea#259]
![](https://habrastorage.org/files/539/bf7/98e/539bf798e7b14e17bf904c21eee33f5d.png)
-
![](https://habrastorage.org/files/850/8d5/789/8508d578989845da9b75933a52e3257b.png)

**Comment by jshiell** [comment]
Thanks for the report.

TBH, this one is messy. Checkstyle returns line number/character for errors. IDEA has a parsed tree of elements. Hence the trick is in trying to relate the L:C to the element. Especially where it refers to a missing item, this can be misleading/plain wrong.

I'll have a look, but it's entirely possible it'll stay like this, I fear.

**Comment by jshiell** [comment]
As with #265, I'm having problems reproducing this, so there may be a different, deeper issue 😢

**Comment by KTannenberg** [comment]
@BorzdeG are you using tabs or spaces for indentation? Problem in #265 reproduces with tabs, but everything works well with spaces.

**Comment by jshiell** [comment]
Assuming you were using tabs, this should now be resolved. If not, please reopen and I'll take another looks - thanks!

**Comment by BorzdeG** [comment]
using tabs:

`<property name="tabWidth" value="2"/>`
