### ISSUE TITLE
Deprecation warning for CheckStyleModuleConfigurable

### ISSUE THREAD

**Issue by baron1405** [jshiell/checkstyle-idea#261]
With IntelliJ IDEA 2016.2 and CheckStyle-IDEA 4.30.1, I am seeing the following in my idea.log:

```
WARN - .ui.configuration.ModuleEditor - org.infernus.idea.checkstyle.CheckStyleModuleConfigurable uses deprecated way to register itself as a module editor. com.intellij.openapi.roots.ui.configuration.ModuleConfigurationEditorProvider extension point should be used instead
```

Thought you might like to know...

**Comment by jshiell** [comment]
Thanks very much. I build against 14.1.5, where it's obviously not yet deprecated. Guess I should probably move to 15 or 2016 at some point 😄
