### ISSUE TITLE
Suppression file does not appear to be honored

### ISSUE THREAD

**Issue by baron1405** [jshiell/checkstyle-idea#262]
IntelliJ IDEA 2016.2
CheckStyle-IDEA 4.30.1

I read in a suppression file using the SuppressionFilter module:

```
...
    <module name="SuppressionFilter">
        <property name="file" value="${config_loc}/suppressions.xml"/>
    </module>
...
```

I have CheckStyle-IDEA configured to scan test classes as well as production code. I suppress certain checks for test code using the suppression file referenced above, which contains:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suppressions PUBLIC
    "-//Puppy Crawl//DTD Suppressions 1.1//EN"
    "http://www.puppycrawl.com/dtds/suppressions_1_1.dtd">
<suppressions>
    <!-- Suppress Javadoc requirements for tests -->
    <suppress checks="JavadocType" files="src/(test|integTest)/.+"/>
    <suppress checks="JavadocMethod" files="src/(test|integTest)/.+"/>
    <suppress checks="JavadocPackage" files="src/(test|integTest)/.+"/>

    <!-- Constructors are not required in ests -->
    <suppress checks="MissingCtor" files="src/(test|integTest)/.+"/>

    <!-- Allow magic numbers in tests -->
    <suppress checks="MagicNumber" files="src/(test|integTest)/.+"/>

    <!-- Suppress method length check in tests -->
    <suppress checks="MethodLength" files="src/(test|integTest)/.+"/>

    <!-- Suppress checks on generated code -->
    <suppress checks="." files="generated-src/.+"/>

    <!-- Suppress checking resources -->
    <suppress checks="." files="src/main/resources/.+"/>
</suppressions>
```

I am noticing that after editing my unit test code, the suppressed checks are still being run. It appears that either the suppression file is being ignored or suppressions are ignored for test code.

**Comment by jshiell** [comment]
Thanks for the report!

The 'scan test classes' is just used as a flag when deciding whether a file should be included in the scanned set. After looking at the code, what I think it more likely is the directory path structure - a temporary file is created if IDEA reports that the file to be scanned may be modified from the disk version. However, only part of the directory structure around this temporary file is created (just the package structure, I think). This means path based suppressions that expect constructs outside the area may no longer apply cleanly.

Given we really don't want to force IDEA to flush files to disk (both for perf and for good manners), the only solution that immediately comes to mind is creating the directory structure from the project level up, which may have some interesting edge cases. In any case, I'm out of time to look at this this morning, so will have a think and come back to it.

**Comment by baron1405** [comment]
Thanks for your thoughts on the issue. That seems to correlate with the behavior I am observing. For example, it explains why the plugin is honoring the suppressions after any action that would effectively sync the psi with the file system but then appears to ignore the suppressions as I edit (i.e. make the psi out of sync with the filesystem).

**Comment by baron1405** [comment]
In the meantime, perhaps you could mention this limitation on the CheckStyle-IDEA readme so folks aren't scratching there head when they encounter it.

**Comment by jshiell** [comment]
Yeah, that does sound like a good idea 😄

**Comment by jshiell** [comment]
I've been having a play, and it looks like I was slightly wrong - the temporary folder should usually contain the path of the file in question, but only relative to the file's module. If it doesn't appear to be relative to the module, then we fall back to using only the package.

There are two main ways it looks like this could break - firstly, that the module structure is such that we should be project relative rather than module relative. Secondly, that there's some platform specific oddity that's breaking this logic.

https://github.com/jshiell/checkstyle-idea/blob/master/src/main/java/org/infernus/idea/checkstyle/checker/ScannableFile.java#L125

I need to do a little more testing to nail it down, but it's not quite as simple as I was hoping. I should have expected that, really.

**Comment by jshiell** [comment]
Playing in a single module, I'm able to happily suppress checks based on a path `src/test`. Which is a pain. The only way I've been able to break it so far is by relying on the project relative path (e.g. `files="child-module/src/test/.+`.

Do you have any ideas/guesses as to where the differences might lie? Perhaps OS (I'm on OS X) or in project/module structure?

**Comment by baron1405** [comment]
Thanks for looking into this. My project has only a single module. It is a Gradle project and I directly open the top level build.gradle to import the project. Perhaps the internal representation of the project generated by IntelliJ's use of the Gradle tooling API is not conforming to the assumptions in the path matching code. I'd suggest creating a simple Gradle project, import the build.gradle and see if the path-based suppressions are honored.

**Comment by baron1405** [comment]
I inserted some logging statements in the ScannableFile.parentDirFor method you referenced. The output seems to confirm that the temporary path is not as expected. It appears to start at the directory one above the package level not the module level. Specifically, I made a change in the file src/test/java/com/cthing/miller/domain/project/ExternalDependencyTest.java but the temporary directory path is /tmp/csi-cc359a7f-c058-44c2-a41a-66289c93fe00/java/com/cthing/miller/domain/project notice that instead of src/test/java, the path starts with just java. Hopefully, this provides some clues.

**Comment by baron1405** [comment]
Adding some more logging statements in the loop over content root urls, I see the following:
```
parentUrl: file:///home/baron/projects/miller/src/test/java/com/cthing/miller/domain/project
moduleSourceRoot: file:///home/baron/projects/miller/generated-src/h2-constants/test
moduleSourceRoot: file:///home/baron/projects/miller/generated-src/properties-constants/test
moduleSourceRoot: file:///home/baron/projects/miller/src/test
MATCH
```
So apparently the ModuleRootManager.getInstance(module).getContentRootUrls() considers the content root to start at the 'java' directory.

**Comment by jshiell** [comment]
Thanks for that - very helpful. Although it does make things messier.

In my test project, I'm getting:```
moduleSourceRoot = file:///Users/jshiell/Projects/JavaPlayground/ChildModule
parentUrl = file:///Users/jshiell/Projects/JavaPlayground/ChildModule/src/test/java/foo/bar
tmpDirForFile = /var/folders/3g/_43kt6d94392r3mz2tty30t80000gn/T/csi-3d189df7-86e4-477c-9fc0-c6054ffc04bb/src/test/java/foo/bar
```

Which in this case is entirely correct, and allows the suppressions for the module to use `src/test/.+`. If we switch to basing it from the project then this case breaks, as we'd end up requiring `ChildModule/src/test/.+`.

I then tried with a multi-module Gradle project from one of my clients, and got similar results:```
moduleSourceRoot = file:///Users/jshiell/Projects/client/project/lib/shared
parentUrl = file:///Users/jshiell/Projects/client/project/lib/shared/src/main/java/com/client/project/shared/search
tmpDirForFile = /var/folders/3g/_43kt6d94392r3mz2tty30t80000gn/T/csi-392a6464-0464-4510-b14e-a841a94d1c1c/src/main/java/com/client/project/shared/search
```

Which seems fine - and again would break if project relative rather than module.

So I'm a bit at sea at present - unless this is a IDEA 2016.x problem as I must concede I've had nothing but misery since Jetbrains decided to rewrite the Gradle integration. I know the same project I reference above broke entirely with 2016.1, and we can only use it with 2016.2 if we disable separate modules per source set. Which seems a good point of attach next, although I'm damned if I know what can be done about it should it prove to be that.

**Comment by jshiell** [comment]
Indeed, looks like it's JB continuing to arse up Gradle imports. If you import with 'separate module per source set', the same project returns:
```
moduleSourceRoot = file:///Users/jshiell/Projects/SpringerNature/oscar/lib/shared/src/main
parentUrl = file:///Users/jshiell/Projects/SpringerNature/oscar/lib/shared/src/main/java/com/springer/oscar/shared/search
tmpDirForFile = /var/folders/3g/_43kt6d94392r3mz2tty30t80000gn/T/csi-781bbdc0-ad4f-4bf8-983b-630428d77576/java/com/springer/oscar/shared/search
```

If I had a pound for each hour IDEA 2016 and its Gradle changes have wasted for me ....

So, short term fix is to import with *Create separate module per source set* turned off. Which fixes other bugs in 2016.2 as well, but I appreciate is far from ideal.

Longer term ... no idea really. There's nothing I spotted in the debugger to let us clearly identify this case and adapt appropriately, other than guesswork, and I'd really rather not add silly heuristics to work around JB's madness. Ideas very much welcome.

**Comment by baron1405** [comment]
While I am sad at the state of JB+Gradle, I am glad that at least you were able to get to the root cause. I'll see if anything comes to me.

**Comment by jshiell** [comment]
And thanks very much for your help, or I might still be muddling around trying to find the cause!

**Comment by baron1405** [comment]
Just to tie this off for now, as you suggested, turning off the separate modules per source set did indeed allow suppressions from src/* to work as expected.

**Comment by mashawan** [comment]
Hello, I know this has been open for a while but I am getting hit by this issue (I think) now that IntelliJ 2019 doesn't allow you to be specific about explicit modules per source set.

I have a check-style config and a suppression file to disable certain checks for test source, as soon as I make a change to a test java file, the supressions stop working and I get a load of checkstyle warnings.

**Comment by mashawan** [comment]
Hello! We are still hitting this in IntelliJ 2020.  The setting you mention above is not deprecated and causes us other problems with test source dependencies.   So we are trying to run with the gradle defaults but this has caused checktyle to ignore out test supressions.
