### ISSUE TITLE
Exclude certain Files based on location

### ISSUE THREAD

**Issue by simschla** [jshiell/checkstyle-idea#27]
In our Projects, we have some generated Java classes in a src/gen/java subfolder, while our handcoded Files live in src/main/java - as far as I see, there is no option to prevent Checktsyle-IDEA from visiting the src/gen/java subfolder. Adding this possibility would be very nice!

**Comment by tsjensen** [comment]
I vote to close this one on the basis of your explanation.

**Comment by jshiell** [comment]
Seems fair. It does have a bit of age on it now 😄
