### ISSUE TITLE
Language setting not working for checkstyle error messages

### ISSUE THREAD

**Issue by Wolfsblvt** [jshiell/checkstyle-idea#270]
Heya.
German guy here. I usually develop in english though.
That means my OS is set to German, but my IntelliJ IDE is English. So everything of the normal error (syntax error, etc) is displayed in english.

If I run the Checkstyle Plugin though, the messages are in German.

I have set the Checker language in the xml config to english, like written in the checkstyle documentation:

``` xml
<module name="Checker">
    <property name="charset" value="UTF-8"/>
    <property name="fileExtensions" value="java, properties, xml"/>
    <property name="localeCountry" value="EN"/>
    <property name="localeLanguage" value="en"/>
[...]
```

But it doesn't work either.
Am I missing something? Or is this a bug that it does not respect language settings?

**Comment by jshiell** [comment]
Hmm. That ones a bit odd ... the plugin just reads the messages from the Checkstyle plugin (or at least it should). The code in question certainly appears to be reading Checkstyle's localised text in preference to the default:
```
@NotNull
    public String message() {
        if (auditEvent.getLocalizedMessage() != null) {
            return auditEvent.getLocalizedMessage().getMessage();
        }
        return auditEvent.getMessage();
    }
```

Does this happen with Checkstyle on the command line as well? If not, then I'm obviously doing something wrong. (I'll check myself anon - I've just been bitten with IDEA not playing nicely with macOS Sierra, so it might have to wait a little while.)

**Comment by Wolfsblvt** [comment]
Haven't tested Checkstyle on commind line.
Guess as far as I've read I need to install stuff for that? If so it has to wait a bit for me too, I am not at home right now and Internet data is limited.

**Comment by jshiell** [comment]
No rush here - we'll see who gets to it first 😄 

For reference, you only need to grab [checkstyle-7.1.1-all.jar](https://sourceforge.net/projects/checkstyle/files/checkstyle/7.1.1/) and then run with something like 
```
java -jar checkstyle-7.1.1-all.jar -c rules-file.xml AJavaFile.java
```

But if it's too much hassle, don't worry - I'll get to it once I'm able, just might be a couple of weeks.

**Comment by Wolfsblvt** [comment]
Didn't know it was just a jar.
Can confirm it's english with it.
And more interestingly, it's just english because of the checkstyle XML settings I've posted above. If I remove those two lines, The general output is english ("Checkstyle ends with xxx errors"), but error messages are german.

So those two lines work for the command line version, but not for the plugin.

**Comment by Wolfsblvt** [comment]
Started IntelliJ again, and now all messages are in english.
I don't mind, works now, that's great :D But I am really sure it wasn't working before ._. Don't know what is different.

**Comment by jshiell** [comment]
Hmm very odd ... once I get my env back to normal I'll have a go at reproducing it, anyway. Thanks for the report!

**Comment by jshiell** [comment]
I've had no luck reproducing this, obwohl ich habe sich mein Deutsch verbessern (apologies for the atrocious grammar) ;-) 

If it does reoccur, please feel free to reopen. Thanks for your help!
