### ISSUE TITLE
CheckStyle plugin blocks files while Git tries to checkout another branch

### ISSUE THREAD

**Issue by elmarschulz** [jshiell/checkstyle-idea#279]
We are using IDEA CheckStyle plugin version 4.31.0. Thank you very mutch for the great plugin.

Unfortunately the plugin seems to block some jar files when I try to switch to another branch in IDEA. When the plugin is enabled I get the following warnings and errors in the Git console in IDEA:

```
11:03:31.840: git -c core.quotepath=false checkout release/v2.6
warning: unable to unlink common/.../blabla.jar: Invalid argument
...
error: unable to unlink old 'common/.../eai-base-1.0-SNAPSHOT.jar': Invalid argument
...
```
When the plugin is disabled, all goes well. Suppressing the containing folder doesn't help.
```
<suppressions>
    <suppress files="[\\/]common[\\/]" checks=".*"/>
</suppressions>
```
Thank you very much for your help!

**Comment by jshiell** [comment]
Sorry, entirely missed this in a whirlwind of pre-Christmas building work.

Are you using Windows? I understand Windows has a nasty habit of locking files it's reading. Which is a problem in this sort of case, where you change branches and such. The file locks should (I think) be dropped when the cache is cleared (every 30s or so).

The bad news: I develop on macOS and only use macOS and Linux for development. These platforms don't lock files in such a way, so I have no way of reproducing the problem. Hence - assuming you are using Windows - this is pretty unlikely to get fixed at present. Sorry.

**Comment by jshiell** [comment]
Possibly dup of #263.

**Comment by elmarschulz** [comment]
Sorry for my very late response.
Yes, we are using Windows. I will close this issue.

Many Thanks.
