### ISSUE TITLE
There should be an option to scan only java source but not the generated source

### ISSUE THREAD

**Issue by testn** [jshiell/checkstyle-idea#284]
There should be an option to scan only java source but not the generated source. The current available operations are 

Only Java sources (but not tests)
Only Java sources (including tests)
All sources (but not tests)
All sources (including tests)
All files in the project

I would expect to see some more options there to exclude the generated files

**Comment by tsjensen** [comment]
You can [configure that in Checkstyle](http://stackoverflow.com/q/18013322/1005481) for the time being. Having it in the plugin would improve performance, of course.

**Comment by jshiell** [comment]
Thanks for the feedback.

As @tsjensen is kind enough to add, the catch is detected generated sources. AFAIK IDEA offers Source/Tests/Reosurces/Test Resources/Excluded paths - there's no direct way of marked a source  tree as 'generated', and hence we have no idea of what to exclude. (If I'm wrong on this, correction would be very welcome.)

I would suggest using suppressions to accomplish this as present, as that'll also ensure that other Checkstyle wrappers (e.g. the CLI client/CSEclipse/Maven) will also exclude the same files.

**Comment by testn** [comment]
Definitely, there is something called "Generated Source Root". The current checkstyle plugin does not seem to respect the parameter I set to exclude the file (It does not accept chcekstyle-suppressions.xml")

**Comment by jshiell** [comment]
> Definitely, there is something called "Generated Source Root" in Intellij IDEA.

Great, can you kindly point me to where? As it's certainly not where I expected it to be.
<img width="167" alt="screen shot 2017-01-27 at 12 07 04" src="https://cloud.githubusercontent.com/assets/1030482/22370399/289c7e2a-e489-11e6-89ba-dbaefdfd6816.png">

>  The current checkstyle plugin does not seem to respect the parameter I set to exclude the file (It does not accept chcekstyle-suppressions.xml")

How does it not accept it? Is there an error? Does it work correctly with the command line Checkstyle? What's in your suppressions file? The more concrete information you can give me, the more likely something will be done.

**Comment by testn** [comment]
@jshiell which version of Intellij IDEA do you use? Mine looks like this

![image](https://cloud.githubusercontent.com/assets/445123/22386849/c8d132c4-e48d-11e6-9069-9757ee5f0fde.png)

**Comment by jshiell** [comment]
I'm running IDEA 2016.3.3 Ultimate. It's consistent on both my work & home installations.

Do you have any plugins installed that may be adding extra root types?

**Comment by jshiell** [comment]
I've checked 15.0.6 as well - same result.

**Comment by testn** [comment]
Probably maven project?

**Comment by jshiell** [comment]
The API currently used to query the file's location (`ProjectFileIndex`) offers only the following methods.

![screen shot 2017-01-29 at 11 57 10](https://cloud.githubusercontent.com/assets/1030482/22403793/2da86298-e61a-11e6-85d5-d94838bb064e.png)

So it doesn't seem to be in the expected API. There is a method for parameterised types (`FileIndex.isUnderSourceRootOfType`) but the only concrete types I can find are source & resources.

If you can find the appropriate API it's not a hard feature to add. However I've had no luck.

**Comment by testn** [comment]
Would this filter help?

https://github.com/JetBrains/intellij-community/blob/306d705e1829bd3c74afc2489bfb7ed59d686b84/java/java-analysis-impl/src/com/intellij/openapi/roots/JavaGeneratedSourcesFilter.java

**Comment by jshiell** [comment]
That looks very promising indeed. I'll continue investigations at the weekend - thanks!

**Comment by jshiell** [comment]
Somewhat amusingly, it looks like we already check generation state via `JavaProjectsRootUtil`, in [`PsiFileValiator`](https://github.com/jshiell/checkstyle-idea/blob/9d322c2822267717aae7e54b1c906ec0516d3244/src/main/java/org/infernus/idea/checkstyle/checker/PsiFileValidator.java). This should ensure generated code isn't scanned. Shows what I know...

What's your use case here? Is it like you'd like to scan generated files in some cases, or is it that the check that's in place isn't working and generated source trees are being scanned (which'd be a bug)?

**Comment by testn** [comment]
Yeah, I think the check didn't seem to work properly on my end. It seems to give warning / errors for generated files as well.
