### ISSUE TITLE
Sevntu checkstyle checks can not be loaded

### ISSUE THREAD

**Issue by george-007** [jshiell/checkstyle-idea#286]
Sevntu checks stopped working for me in the latest versions of the plugin (5.0, 5.0.1).

I get the following error:
```
The Checkstyle rules file could not be parsed.
cannot initialize module TreeWalker - Unable to instantiate 'com.github.sevntu.checkstyle.checks.coding.TernaryPerExpressionCountCheck' class, it is also not possible to instantiate it as com.puppycrawl.tools.checkstyle.checks.annotation.com.github.sevntu.checkstyle.checks.coding.TernaryPerExpressionCountCheck, com.puppycrawl.tools.checkstyle.checks.blocks.com.github.sevntu.checkstyle.c...
```

checkstyle.xml:
```
   <module name="com.github.sevntu.checkstyle.checks.coding.TernaryPerExpressionCountCheck" />
```
![intellij ide](https://cloud.githubusercontent.com/assets/1450087/22414992/3be4ba00-e6c4-11e6-9dbd-305162993ee5.png)

**Comment by davideconsonni** [comment]
Same error, using sevntu. 
Put the sevntu-checks-1.21.1.jar manually in plugin directory and intellij directory but doesn't works.

**Comment by tsjensen** [comment]
I had the same error at first, but it went away after I changed something in the configuration dialog. I just selected a different Checkstyle version, pressed OK, then switched back to the one I had selected before. Now I can't reproduce the problem anymore ... Would that be a temporary workaround for you? (Until we can nail down the problem.)

**Comment by tsjensen** [comment]
My guess is that this bug is caused like so: `CheckstyleProjectService.activateCheckstyleVersion()` must be called with a 3rd party classpath, but it is only ever called with one when the user presses OK in the config dialog. Before that, the path is always `null`. The fix would be to read the configuration and use the correct 3rd party classpath right from the start.
@jshiell In order to avoid duplicate work: Do you want me to fix this, or are you already at it?

**Comment by george-007** [comment]
Changing the checkstyle version helps for me but its needed after each restart of idea.

**Comment by tsjensen** [comment]
@george-007 Thanks for the feedback. That fits my above guess about the root cause.

**Comment by jshiell** [comment]
@tsjensen smashing work - I won't be able to look at this until tomorrow night at the earliest, so if you're available now please go ahead.

If you run out of time, shout, and I'll try sort it tomorrow. Thank you!

**Comment by tsjensen** [comment]
The fix would go into the constructor of `CheckstyleProjectService`, but mocking requirements need to be considered, so I will not be able to do this until tomorrow. But I will deal with this within the next couple of days. I feel obliged to do it because I caused the bug :wink:

**Comment by jshiell** [comment]
Sevntu is working for me after a restart, so the fix looks successful. 

I did find one edge case - it looks like adding an extension JAR doesn't trigger the reload of the classpath, so if you add a new extension JAR and immediately try and add a rules file that depends on it then it fails. I believe I've fixed it (fix is exactly what you'd expect).

I'll push this out as 5.1.0, along with CS 7.5 - thanks for the quick fix!

**Comment by JLLeitschuh** [comment]
Well this explains the problems I was having.
Thanks for resolving it.

**Comment by JLLeitschuh** [comment]
Actually, I take it back, it seems to work, but if you change the checkstyle version you are using in intellij then suddenly your third party checks stop working and treewalker fails to load.

I'm trying to use checkstyle version 7.1.2
