### ISSUE TITLE
Changing Checkstyle Version Used requires third party libs to be re-added

### ISSUE THREAD

**Issue by JLLeitschuh** [jshiell/checkstyle-idea#298]
If you change the checkstyle version that you are using suddenly all third party checks stop working.

Restarting does not fix this problem.

The only way I've managed to fix this is by editing the third party check jar and just clicking open on the same file again.

Perhaps the `reload` button should also reload third party jars?

**Comment by tsjensen** [comment]
Can you describe the exact steps to reproduce? I just tried it but it seemed to work fine. Thank you!

**Comment by tsjensen** [comment]
Should we close this? No feedback for over a month ...

**Comment by JLLeitschuh** [comment]
Sorry, I haven't had a chance to try it out.
I'll add a reminder to take care of this tomorrow.

**Comment by tsjensen** [comment]
Shall we close this now? Should you ever get around to trying it out, and you still see a problem, you could reopen.

**Comment by jshiell** [comment]
Sounds good. Please reopen if needed 😄
