### ISSUE TITLE
Checkstlye always reports 1 error in "Before Commit" check even there is no issue

### ISSUE THREAD

**Issue by frimtec** [jshiell/checkstyle-idea#299]
Since about 5.2.0 the before commit checkstyle check always reports at least one error even there is no issue at all.
![checkstyle1](https://cloud.githubusercontent.com/assets/3511114/23351011/c448938e-fcbe-11e6-8fce-f156959accc5.png)
![checkstyle2](https://cloud.githubusercontent.com/assets/3511114/23351012/c4494bee-fcbe-11e6-88b3-a11738d42c8e.png)

**Comment by jshiell** [comment]
Thanks for the report - I'll try have a look at this this weekend.

**Comment by jshiell** [comment]
Ignored checks were being counted in the pre-commit scan - this should be fixed in 5.3.0.

**Comment by frimtec** [comment]
Cool, many thanks for the fix.
