### ISSUE TITLE
Group results by package or severity

### ISSUE THREAD

**Issue by jshiell** [jshiell/checkstyle-idea#3]
It would be very helpful to be able to group results by package or
severity. As a committer for a fairly large project, sometimes I just need
to see the in the package the team I'm committing for owns. Additionally,
for large projects, there are so many results, it would be nice to group
the issues by severity. BTW, I built off of the trunk and find the
enhancement created to filter by severity very valuable.

**Comment by delanym** [comment]
This would be handy

**Comment by jshiell** [comment]
13+ years later, will be present in 5.99.0.
