### ISSUE TITLE
Checkstyle 7.6.1 released

### ISSUE THREAD

**Issue by GlennKintscher** [jshiell/checkstyle-idea#303]
[Version 7.6.1](http://checkstyle.sourceforge.net/releasenotes.html#Release_7.6.1) added:

> NoLineWrap: add support for static imports. [...]
> PackageDeclaration: new property matchDirectoryStructure to match the package name to directory name of source file. [...]
> ParenPad: add LAMBDA token support. [...]

Unfortunately, it is not possible to use the plugin (in my case) until it supports those changes because of the following error:

> The Checkstyle rules file could not be parsed.
> cannot initialize module TreeWalker - Property 'matchDirectoryStructure' in module PackageDeclaration does not exist, please check the documentation
> The file has been blacklisted for 60s.

I would really appreciate if you could take care of this as soon as possible as I really love working with the plugin! :)

**Comment by jshiell** [comment]
Thanks for the reminder - I don't use the plugin myself at present, so I have a nasty habit of missing Checkstyle releases. Released as 5.4.0, should be on the plugin repo now 😄

**Comment by GlennKintscher** [comment]
No problem, thanks for taking care of it! :)
