### ISSUE TITLE
add configuration file crashes and leaves intellij unresponsive 

### ISSUE THREAD

**Issue by hlund** [jshiell/checkstyle-idea#304]
In 2017.1.3.EAP  (build-171.4249.4) when trying to add a configuration file the modal window for selecting configuration file crashes immediately, and leaves idea main window without accepting actions.
(OS: fedora 25)

**Comment by jshiell** [comment]
Thanks for the report. I fear I won't look at this before RC1 at least, though, as I've been bitten before by changes in the EAPs.

**Comment by hlund** [comment]
Sounds reasonable 
workaround is as simple replace sun_checks.xml

**Comment by jshiell** [comment]
I can't reproduce this on the release on 2017.1.3, so I'm assuming it was an EAP issue.

If you're still seeing it with the release version, please reopen the issue. Thank you!
