### ISSUE TITLE
Comment is marked as such, but not  handled by checkstyle

### ISSUE THREAD

**Issue by DominikSpreuer** [jshiell/checkstyle-idea#306]
A comment of 
!--comment
is shown as comment by the plugin. But as checkstyle needs a space behind (!--), checkstyle does not handle it as comment and searches for a matching Annontation

Todo: only accept comments with (!-- ) and not without the space (!--)
Thanks!

**Comment by jshiell** [comment]
Does this occur with Checkstyle on the command line as well, as it doesn't sound like a plugin bug?

**Comment by DominikSpreuer** [comment]
This was complete rubbish. Its a jbehave bug. Sorry for reporting

**Comment by jshiell** [comment]
No worries, glad to hear it's sorted 😄
