### ISSUE TITLE
checkstyle configuration doesn't handle trailing whitespace in file path gracefully

### ISSUE THREAD

**Issue by erikdw** [jshiell/checkstyle-idea#308]
I pasted the path to my checkstyle configuration file into the Checkstyle-IDEA settings and then got an error "File does not exist:".  It was confusing because I knew the path worked (`ls <control-V>` showed the file).  Then I realized I had a trailing newline in the string I was pasting.  Notably, the string was in my vim buffer, I was just selecting it and pasting.  That led to the string in the "Use a local file" > "File" edit box having a single space after the "basename" of the path.

I would suggest:
* strip trailing (and leading?) whitespace from filenames input into the edit box
* showing the nonexistent filename/path within quotes in the error popup.  That would have shown me that the path wasn't exactly what I thought it was.

Versions:

* IntelliJ 15.0.6
* Checkstyle-IDEA 5.5.0

**Comment by jshiell** [comment]
Both very reasonable suggestions, thank you. I'll try to have a look this weekend.

**Comment by jshiell** [comment]
I've added trimming of the values to 5.5.1. I haven't added quotes to the error - as the logic is currently dumping the exception text, so we'd have to introduce a bit more logic there -  and the trimming should rule this particular delight out.

Thanks for the report!
