### ISSUE TITLE
cannot edit existing checkstyle configuration file's path

### ISSUE THREAD

**Issue by erikdw** [jshiell/checkstyle-idea#309]
When I try to edit an existing local configuration file, the dialogue box just shows as empty:

Versions:

* IntelliJ 15.0.6
* Checkstyle-IDEA 5.5.0

<img width="490" alt="screen shot 2017-05-15 at 2 36 05 am" src="https://cloud.githubusercontent.com/assets/1111441/26051568/5f804984-3917-11e7-8897-966f8ec9775f.png">

**Comment by jshiell** [comment]
Can you please attach the rules file in question?

**Comment by erikdw** [comment]
Here it is:
https://github.com/apache/storm/blob/d4ee957a9d677f7ea2ec684915ea88f7717f5d6e/storm-buildtools/storm_checkstyle.xml

**Comment by jshiell** [comment]
Unless I'm missing something, I can't see any properties defined in that file. If true, that would make the exhibited behaviour entirely expected.

Unlike the Eclipse plugin, this plugin does not support editing Checkstyle files, only the properties applied to them.

**Comment by erikdw** [comment]
Maybe I didn't explain the problem well:  I wanted to modify an existing file's *path* after changing the filename in the shell.  I thought that little pencil icon would let me do it.

**Comment by jshiell** [comment]
Oh, right. Delete it and recreate it. I've never added an edit function, as it'd just be the same remove/add process behind the scenes, and adds no benefit unless you have a lot of properties. Curiously, you're the first person to query this in the ten years it's been about.

**Comment by erikdw** [comment]
@jshiell : the problems I encountered in #307 (locking up of intellij) were especially pronounced when I tried to click the pencil icon for the selected (but now missing) checkstyle "profile", which is part of why I submitted this ticket.

**Comment by erikdw** [comment]
@jshiell : sorry for continuing to comment on this closed issue, but I reread your response earlier and I'm wondering if you looked at the wrong file:

> Unless I'm missing something, I can't see any properties defined in that file. If true, that would make the exhibited behaviour entirely expected.

There are numerous "property" fields defined in the [storm_checkstyle.xml](https://github.com/apache/storm/blob/d4ee957a9d677f7ea2ec684915ea88f7717f5d6e/storm-buildtools/storm_checkstyle.xml) file that I [linked above](https://github.com/jshiell/checkstyle-idea/issues/309#issuecomment-301731641).

e.g.,

```
<module name = "Checker">
    <property name="charset" value="UTF-8"/>

    <property name="severity" value="warning"/>

    <property name="fileExtensions" value="java, properties, xml"/>
    <!-- Checks for whitespace                               -->
    <!-- See http://checkstyle.sf.net/config_whitespace.html -->
        <module name="FileTabCharacter">
            <property name="eachLine" value="true"/>
        </module>

    <module name="TreeWalker">
        <module name="OuterTypeFilename"/>
        <module name="IllegalTokenText">
            <property name="tokens" value="STRING_LITERAL, CHAR_LITERAL"/>
            <property name="format" value="\\u00(09|0(a|A)|0(c|C)|0(d|D)|22|27|5(C|c))|\\(0(10|11|12|14|15|42|47)|134)"/>
            <property name="message" value="Consider using special escape sequence instead of octal value or Unicode escaped value."/>
</module>

...
```

Do you mean something different by "property"?

**Comment by jshiell** [comment]
I'm thinking of what the  Checkstyle docs call `property expansion`, e.g. `checkstyle.header.file` in
```
<module name="Header">
    <property name="headerFile" value="${checkstyle.header.file}"/>
</module>
```

**Comment by erikdw** [comment]
@jshiell : ah, some interpolation feature in checkstyle.  It wasn't clear to me what the little pencil button in the Checkstyle configuration dialogue was for -- seems it's a very specific use case.  Thanks for clarifying.
