### ISSUE TITLE
Is there a way to use my own filters?

### ISSUE THREAD

**Issue by agackovka** [jshiell/checkstyle-idea#310]
Oh, guys, I have been trying to apply my own filter for 2hours and have no success at all...
Could you please help me to understand how my filter can be put into plugin's classpath?

Here is what i have:

1: `<module name="org.comeclass.ValueObjectsFilter"/>`

2: 
```
public class ValueObjectsFilter extends AutomaticBean implements Filter {
    public boolean accept(AuditEvent aEvent) {
        return false;
    }
}
```

without line#1 everything works fine, but with line#1 i get 
`The Checkstyle rules file could not be parsed. cannot initialize module org.comeclass.ValueObjectsFilter - Unable to instantiate bla-bla-bla`

Is it even possible to use external filters with IDEA?

**Comment by jshiell** [comment]
Hello. Yes, it should be possible. You need to add the JAR file with your extensions to the lower section of the configuration panel. I think it's called *Third Party Checks* or something similar. This just adds anything listed into the plugin classpath, so I believe it'll work for this case.

**Comment by agackovka** [comment]
Thx, it works!
