### ISSUE TITLE
Temporary folder 'csi-tmp' appearing in projects

### ISSUE THREAD

**Issue by tsjensen** [jshiell/checkstyle-idea#313]
The fix for #302 introduced a new temporary folder on Windows, which is called `csi-tmp` and is created in the project root.
This causes some problems for us because
- the folder is not part of our `.gitignore` files
- Some custom checks which check the folder structure do not know it
- It appears in people's project browser view and confuses them
- The file in the `csi-tmp` folder changes its relative path. In some cases, it starts with `src/main` after the UUID, in other cases it starts with `java` (without `src/main` in front).

We are a large group of developers, so this really causes work for me. I can fix most of the above pain points by adjusting configuration in other tools, but it would be really nice if I could just move this folder into, let's say, the `build` (Gradle) or `target` (Maven) subfolder. Then people wouldn't be bothered.

So, I would like to request that the location of `csi-tmp` be made configurable. It's ok to allow only locations which are below the project root.

Thank you!

**Comment by jshiell** [comment]
Hmm. Agreed, that's an irritation too far. Sorry for the hassle!

This was introduced thanks to 302 - Checkstyle is trying to relativise the path for some checks, and if the file has been modified, and hence saved to a temporary file, it can end up on another drive and break relativisation. 

Originally I wanted to place this in the build folder - however, I didn't find a way of finding this in the IDE, only the output folders for classes/resource, neither of which is appropriate for this. If you've any suggestions on how to pull this from the API, I'd be most grateful.

Quick check - this should only occur when multiple drives are in play, and `%TMPDIR%` isn't on the same drive as the project. Does this fit your scenario? If not, there's another bug in play here.

In any case, I'll have a look this weekend and see if I can find a better place to put this (and spend more time cursing Windows). If not, I guess a configurable location will be a good solution.

**Comment by tsjensen** [comment]
Frankly, I wouldn't know how to pull this from the API, because it would seem to depend heavily on the build tool (Gradle, Maven, Ant, SBT, custom scripts, no build tool at all, you name it). So I think it will have to be a configuration option, with the current behavior as default.
And yes, in our case, the `%TEMP%` and the project are on different drives, so that should be good.
Thanks for looking into this!

**Comment by tsjensen** [comment]
After sleeping on it, it seems to me that the cleanest way would be to create the folder in the project's `.idea` directory. It seems that some plugins do that, but I'm not sure if these are all JetBrains plugins, and I don't know if the API has a function for it. We would certainly have to create the folder through the API, so we don't break anything.
If that doesn't work, it might be another idea to go through the list of excluded directories and look for one called `build` or `target`, and create the folder there if they exist. The current behavior would be a fallback.

**Comment by jshiell** [comment]
Nice catch :-) My thoughts were going along interrogating the project model (i.e. check explicitly for Gradle/Maven/SBT, then follow those), followed by a heuristic driven fallback to build/target/whatever, but that's much simpler and should be substantially easier to do. I hope 😄

**Comment by jshiell** [comment]
I've changed it so it'll create it under the `.idea` folder if the project is directory based. I've also changed the name used, so it's blatantly obvious that the plugin is responsible.

Although it's only theoretical until I get this tested on Windows, hopefully later today 😄 

I might have to surrender on IDEA 15 support soon. The newer APIs are a bit better typed than the 15 API. Ah well.

**Comment by tsjensen** [comment]
Great! This solves it for me. Thank you very much for the quick solution!

**Comment by jshiell** [comment]
Great news - thanks, and sorry for the breakage!
