### ISSUE TITLE
Add support for importing ImportOrder module

### ISSUE THREAD

**Issue by zentol** [jshiell/checkstyle-idea#314]
I would like to contribute an importer for the "ImportOrder" module.

I've already got an implementation that seems to work, at the very least it properly imports the onfiguration for my specific use-case:
```
<module name="ImportOrder">
      <property name="groups" value="org.apache.flink,*,javax,java,scala"/>
      <property name="separated" value="true"/>
      <property name="option" value="bottom"/>
</module>
```

What's the general process for contributing to this project, and are there any general code-guidelines I should follow?

**Comment by jshiell** [comment]
Thanks very much! I always greatly appreciate contributions. Please just raise a pull request, and I'll try to have a look this weekend. Don't worry about style etc., that's all easy enough to fix later.

**Comment by jshiell** [comment]
Merged, will be in the next release (should be later this weekend) - thank you again!
