### ISSUE TITLE
EmptyLineSeparaterImporter should also add an empty line before package declarations

### ISSUE THREAD

**Issue by zentol** [jshiell/checkstyle-idea#315]
When the EmptyLineSeparatorModule is configured for the package declaration it enforces an empty line before and after the package declaration, provided it isn't at the start of the file in which case it only cares about the empty line after it.

That is, these formats would be allowed:

```
package my.package;
<empty line>
```

```
<empty line>
package my.package;
<empty line>
```

```
<license>
<empty line>
package my.package;
<empty line>
```

The EmptyLineSeparaterImporter however only sets the `BLANK_LINES_AFTER_PACKAGE` property. This causes the third example to be instead formatted as 
```
<license>
package my.package;
<empty line>
<rest of class
```
which isn't legal.

I thus propose to also set the `BLANK_LINES_BEFORE_PACKAGE`. If the package declaration is at the start of the file no empty line will be added by IntelliJ regardless of what was configured.

**Comment by jshiell** [comment]
Thanks for the report - I especially appreciate issues which explain exactly how to fix the problem! 😄 I'll try and get this sorted this weekend.

**Comment by jshiell** [comment]
Done - will be in the next release. Thank you!
