### ISSUE TITLE
Alter color for the checkstyle related errors

### ISSUE THREAD

**Issue by PriyaSGit** [jshiell/checkstyle-idea#316]
Hi Team

Please add a way to alter the color of the checkstyle realted warnings on android studio. At present I am using a dracula theme and in that checkstyle warning appear as red same as that of errors. I get confused if its checkstyle warning or some syntax error in code. I need visit code and see what it is.

**Comment by jshiell** [comment]
Hi,

Checkstyle is implemented as an IDEA inspection, and as such this feature is already available.

If you go to *Settings* -> *Editor* -> *Inspections*, you should find a *Checkstyle real-time scan* entry. You can then edit the *Severity* field to define a severity of your own choosing, both in colour and style.
