### ISSUE TITLE
Use sun_checks.xml and google_checks.xml from bundled checkstyle jars

### ISSUE THREAD

**Issue by tsjensen** [jshiell/checkstyle-idea#320]
I would like to suggest a little extension of the internal Checkstyle project service with a command that reads the *sun_checks.xml* or *google_checks.xml* from the bundled checkstyle jars. This would allow us to always use the config file version that matches the selected Checkstyle version. It would also allow us to offer the Google checks as bundled check configuration.
The [sun_checks.xml](https://github.com/jshiell/checkstyle-idea/blob/5.6.1/src/main/resources/sun_checks.xml) file we have currently would be removed.
If you support the idea, I can offer to contribute this feature, as it is sort of a corollary to my "select the Checkstyle version" feature. :wink:

**Comment by jshiell** [comment]
That would be magic - the `sun_checks.xml` is well out of date, and there have been requests for the `google_checks.xml`, so this would nicely clean up a few outstanding rough edges. If you're willing to contribute it, I'd be very willing to merge it in - thank you!

**Comment by tsjensen** [comment]
Ok, will do. Be prepared for a little wait, as always.

**Comment by jshiell** [comment]
Many thanks - released as 5.8.0.

I've then gone and broken it by upgrading to the latest IDEA Gradle plugin, which JARs the plugin and which seemingly breaks it (at least it's always trying to load it from CS 6.10 now, which is the first JAR in the sandbox dir...). I've run out of time to fix that today - it's next on the list, but if you do anything on master just be aware 5c0d1e8 is a bit kaputt.

**Comment by tsjensen** [comment]
The IDEA Gradle plugin is a real pain - I hope the new version has improved a bit. I had to implement a few workarounds to deal with its "special characteristics" ...
What's your goal with this change? I might have some time in the coming week to help (no promise). 👻

**Comment by jshiell** [comment]
All fixed, but thanks for the offer 😄 I muddled the CPs and was bitten for it.

Goal is just general maintenance - I'll probably update to Gradle 4 at some point as well, just to ensure we don't run into problems down the line.
