### ISSUE TITLE
Ensure temp files retain their relative path names

### ISSUE THREAD

**Issue by tsjensen** [jshiell/checkstyle-idea#321]
Let's assume we have a Java file located in

    ${workspace_loc}/moduleA/src/test/java/com/foo/Bar.java

When this file is edited, because of IntelliJ's virtual file system, we need to have a temporary file created to perform real-time inspections. Most of the time (on Windows), the location of the temporary file will be

    ${workspace_loc}/.idea/checkstyleidea.tmp/csi-someuuid/java/com/foo/Bar.java

On other OSes, the absolute location may differ, but my problem is with the part after the UUID: It is shortened too much. All of our suppressions for unit tests are based on the source folder of the file being `src/test/java`, but since this is shortened to just `java`, when editing a test, we always see lots of real-time issues which should really be suppressed.

Ideally, the entire relative path below the project root should be contained in the temp file path, thus catching also suppressions defined by module. On Windows, there may be problems with the maximum path length (something like 260 characters), so we might want to keep the overall path length as short as possible. I could imagine using just a counter instead of `csi-someuuid` (e.g. `1`; if `1` already exists, `2`, and so forth). This would give us:

    ${workspace_loc}/.idea/checkstyleidea.tmp/1/moduleA/src/test/java/com/foo/Bar.java

Note that this seems to be independent of your recent work on this temp dir; it appears to affect the "regular" temp files as well.

**Comment by jshiell** [comment]
Indeed, this is a longstanding issue - originally files were not nested; then the package was added to cover most people's cases. But yes, there's a big hole there for other cases.

I don't think this should be too hard to add - I'll put it on my todo list 😄

**Comment by jshiell** [comment]
Looking at the code it seems I did implement relative paths to the module, but not the project. A curious choice on my part.

**Comment by jshiell** [comment]
And we'll now try to create temp files relative to the project root. If it can't find an overlap (e.g. the module is on another drive from the project) then we'll fall back to the old behaviour.

**Comment by tsjensen** [comment]
Great, this solves it for me! Thank you for fixing this so quickly!

Just as a note: This solution takes up 66 characters in the file path (`.idea/checkstyleidea.tmp/csi-2eee473b-29f7-45c3-997d-119449a9d6c3/`), which means that Checkstyle-IDEA users on Windows must limit their path lengths to 194 characters instead of 260 characters. Else they may run into the Windows maximum path length and stuff may start to fail. If we used something like `.idea/csi/a3/` instead (13 characters), this risk would be much reduced.

**Comment by jshiell** [comment]
Ah, Windows 😢 

Shouldn't be too hard to do, although I think the GUID is generated by Java (we just ask for a temp file), so we'd have to do some trimming of our own.

**Comment by tsjensen** [comment]
How about using a simple atomic counter? You could base64 encode the counter value (or some other encoding with the highest possible base). Normalize to a certain number of digits (e.g. 2 or 3) so that path length problems don't start to occur after IntelliJ has been running for a while. When the maximum value is reached, roll over to 0. This should be safe and short.

**Comment by jshiell** [comment]
Good idea - nice & easy, and should be effective 😄 I'll have a look anon - probably next weekend at this point, thanks to lurgy.

**Comment by jshiell** [comment]
Fixed in 5.7.0, although I didn't bother with the Base64 - 1000 concurrent files should be heaps. (Now we can wait for the issue report that proves me wrong ... ).
