### ISSUE TITLE
Checkstyle not scanning the all rules.

### ISSUE THREAD

**Issue by XTIER-Tech** [jshiell/checkstyle-idea#323]
Hi,

I have added the checkstyle plugins to take care of coding restriction. I fetched the checkstyle.xml from sonar cube server and added in plugin config. As shown :

When I try to check the current file. It shows me 3 warnings which actually should be errors. Moreover, On sonar server report there are 8 error. Therefore I am missing 5 errors as well as there warning that are coming as warning should display as errors.

https://stackoverflow.com/questions/44564271/checkstyle-issues-in-intellijidea

**Comment by jshiell** [comment]
Morning. Do you get the same results using the Checkstyle command line tool? Sonar is a superset of Checkstyle, I believe, so I wouldn't necessarily expect a 1 to 1 match.

If the command line client matches the plugin then the Checkstyle file is being interpreted correctly. If not, we probably have a bug.

**Comment by XTIER-Tech** [comment]
Hi, 

Can you please tell me the steps. what i tried in git shell
$ shopt -s globstar
 $java -jar checkstyle-5.5-all.jar -c checkstyle.xml -r D:\myDir\aem\myTest.java. This give me an error 

Unable to create Checker: cannot initialize module SuppressWarningsFilter - Unable to instantiate SuppressWarningsFilter

**Comment by jshiell** [comment]
That looks more or less correct. However, it doesn't like your rules file - are you using the correct version of Checkstyle? The latest version is 7.8.1, 5.5 is pretty old.
