### ISSUE TITLE
How to export the result

### ISSUE THREAD

**Issue by wisekingokok** [jshiell/checkstyle-idea#326]
I hope I can export the result to html files on Android Studio, bud I don't how to do it.

would you give me any guide?

**Comment by jshiell** [comment]
Hi, I'm afraid we don't support this currently. If you want a HTML report you're probably best to use the command line plugin.

**Comment by wisekingokok** [comment]
what about .md file?   
Actually, I want to get the result that can be read without Android Studio.

**Comment by jshiell** [comment]
There's currently no export feature. The plugin is intended only to assist when using IDEA - if you want reports/output without IDEA then the CLI version or one of the build tool plugins (e.g. Maven, Gradle) remain better options.

**Comment by wisekingokok** [comment]
Thanks for jshiell， got it
