### ISSUE TITLE
Automatically configure built-in properties

### ISSUE THREAD

**Issue by dansanduleac** [jshiell/checkstyle-idea#332]
http://eclipse-cs.sourceforge.net/#!/properties

Properties such as `config_loc` should be automatically configured

**Comment by dansanduleac** [comment]
I notice the readme says these variables are supported: https://github.com/jshiell/checkstyle-idea#eclipse-cs-variable-support

However, while adding a new configuration pointing to a `checkstyle.xml` file and press Next, I reach this dialog which seems to imply that `config_loc` is empty:

![image](https://user-images.githubusercontent.com/222827/28379807-ee3e0eea-6cac-11e7-834d-9b84e941355e.png)

**Comment by jshiell** [comment]
Hi, if you continue, leaving `config_loc` empty, you should find the value is filled in. We don't fill it at this stage as obviously it may change. The logic, therefore, is to populate it with the default value if it's not set.

Please reopen if you don't see this behaviour.
