### ISSUE TITLE
Cannot edit configuration in IDEA 2017.1.2 or 2017.2

### ISSUE THREAD

**Issue by dansanduleac** [jshiell/checkstyle-idea#334]
![cant-click-edit](https://user-images.githubusercontent.com/222827/28458759-ca0e3ae8-6e02-11e7-9d33-3a9141a60ea5.gif)

**Comment by jshiell** [comment]
Thanks for the report. Looking at this on my machine, the dialogue opens, but it opens behind the current window. Does the same happen for you?

**Comment by jshiell** [comment]
The behind the window issue is fixed. If your issue is not the same thing, and is still occurring with 5.8.2, then please reopen.

**Comment by dansanduleac** [comment]
Couldn't tell if that was happening, but now I do get the window allowing me to edit the properties.
I don't have any way of changing the description or file though. It would be nice if these were editable on click.

**Comment by dansanduleac** [comment]
Also, I don't have permissions to reopen an issue. Could you grant that? :)

**Comment by jshiell** [comment]
Not if you're going to reopen it for a different issue 😄 I have a pet hate of issues that bounce state constantly with a trail of different tweaks. 😁 

Feel free to open a request for editable name/files though. It would require change the configuration location implementation to track identity some other way (currently it's by name+filename+type, which breaks if you can mutate these). It's not a high priority from my side, but you're not the first to suggest it so obviously some others feel differently.

**Comment by dansanduleac** [comment]
Fair enough! I'll open a new issue.
