### ISSUE TITLE
The Checkstyle rules file could not be parsed

### ISSUE THREAD

**Issue by igorwojda** [jshiell/checkstyle-idea#336]
This is continuations for bug
https://github.com/jshiell/checkstyle-idea/issues/331#issuecomment-316526756

The file still can't be parsed although this time (5.8.2) the proper error is displayed.

`org.infernus.idea.checkstyle.exception.CheckStylePluginException: <html><b>The Checkstyle rules file could not be parsed.</b><br>Property ${checkstyle.suppressions.file} has not been set<br>The file has been blacklisted for 60s.</html>`

**Comment by jshiell** [comment]
Have you re-entered the value for that property? The previous bug means it was probably not saved, and hence remains empty. The bug fix just ensures that it would be saved properly after being entered.

**Comment by igorwojda** [comment]
Please be more specific where exactly the 'property should be entered'
Now I have simple config for checkstyle

```
checkstyle {
    config resources.text.fromFile("${rootProject.projectDir}/config/static_analysis/checkstyle/checkstyle_rules.xml")
    ignoreFailures false
    configProperties = ["checkstyle.suppressions.file": "${rootProject.projectDir}/config/static_analysis/checkstyle/checkstyle_suppression_filter.xml"]
    showViolations true
    toolVersion '6.19'
    tasks.withType(Checkstyle) {
        reports {
            xml.enabled true
            html.enabled true
        }
    }
}
```

**Comment by jshiell** [comment]
You can edit the properties for a configuration in the Settings dialogue.

Alternately, when you add the rules files you'll be prompted to enter property values. If you remove the configuration, then add it again, you'll be guided through this process.

**Comment by igorwojda** [comment]
I actually didn't realize that property values can be edited' after adding rule files (You should add some description at the top of this window and "Are you sure you want to continue without entering property values" dialog").

Thanks for help

**Comment by jshiell** [comment]
No worries. There's a validation step (i.e. if you hit next without entering required properties then it'll try loading the configuration and explode), as some properties may be omitted without causing problems, depending on the rules file. However, the previous bug meant that this validation step passed, and then values were dropped.
