### ISSUE TITLE
Support CheckStyle 8.1

### ISSUE THREAD

**Issue by baron1405** [jshiell/checkstyle-idea#338]
CheckStyle 8.1 is out so it would be great to have it supported. Heads up that there are some [breaking changes](http://checkstyle.sourceforge.net/releasenotes.html) including a change in the config file effecting the SuppressionCommentFilter and SuppressWithNearbyCommentFilter which are now children of TreeWalker. So an 8.0 config file using those checks will not load into 8.1.

**Comment by jshiell** [comment]
Cheers, will try get this nailed this weekend.

**Comment by jshiell** [comment]
Released in 5.9.0.

**Comment by baron1405** [comment]
Thanks for the super quick turnaround on this!
