### ISSUE TITLE
The Checkstyle rules file could not be parsed.

### ISSUE THREAD

**Issue by SButterfly** [jshiell/checkstyle-idea#339]
Hello, after update to 5.9.0 I have several equal errors:
```
29/07/2017
15:56	The Checkstyle rules file could not be parsed.
			SuppressionCommentFilter is not allowed as a child in Checker
			The file has been blacklisted for 60s.
```

What I did wrong?

**Comment by tsjensen** [comment]
Since 8.1, SuppressionCommentFilter is a child of TreeWalker.
Select Checkstyle 8.0 or earlier, or update your config file.

**Comment by jshiell** [comment]
Thanks @tsjensen 😄 

@SButterfly for reference, you can find the list of changes in the different versions of Checkstyle [on  their project site](http://checkstyle.sourceforge.net/releasenotes.html).
