### ISSUE TITLE
"SuppressionCommentFilter is not allowed as a child in Checker"

### ISSUE THREAD

**Issue by marcelstoer** [jshiell/checkstyle-idea#341]
After the recent IntelliJ incl. plugin update I keep seeing

> The Checkstyle rules file could not be parsed.
    SuppressionCommentFilter is not allowed as a child in Checker
    The file has been blacklisted for 60s.

This is with a config that seems perfectly valid, one that hasn't changed in months.

```
<module name="Checker">
  <property name="severity" value="warning" />
  <module name="TreeWalker">
    ...
  </module>
  ...
  <module name="SuppressWarningsFilter" />
  <module name="SuppressionFilter">
    <property name="file" value="${config_loc}/suppressions.xml"/>
  </module>
  <module name="SuppressionCommentFilter">
    <property name="checkC" value="false" />
  </module>
  ...
</module>
```

**Comment by jshiell** [comment]
Checkstyle 8.1 had breaking changes for this check - http://checkstyle.sourceforge.net/releasenotes.html

Please either select an older version of Checkstyle, or update your rules file to be compatible with 8.1+.

**Comment by Maskime** [comment]
Just for the record, I tried to change the Checkstyle version to 7.8.2 and still had the issue.
Dear reader if you googled your way here, like I did, the solution is to move the `<module name="SuppressionCommentFilter"/>` under the `TreeWalker` module.

**Comment by marcelstoer** [comment]
Yep, that's what it says in the release notes I was pointed to.

**Comment by RikkiGibson** [comment]
If you change the Checkstyle version in the dropdown in Settings, you need to hit Apply before trying to add your configuration file.

**Comment by RikkiGibson** [comment]
It seems like it would be handy if the IDEA plugin could automatically use the checkstyle version referenced in the pom for the project you're working with. I don't know how that would be to implement or if it was a deliberate choice not to do that.

**Comment by jshiell** [comment]
@RikkiGibson thanks - I noticed that just the other day in #367 - while it's technically correct (the best kind of correct) it's horrible UX, so I will try fix it at some point.

On the POM file, we're not tied to any build tool, only the IDEA project model. If it's exposed via the IDEA model (which AFAIK it's not) we could add support. But I've no desire nor plans to add integrations with particular build tools.

**Comment by JohnLockwood** [comment]
@RikkiGibson Your comment about having to click update first was a workaround, but is that also entered somewhere as a bug?  It is.  If you change the rule in the dropdown, the expectation is that adding a new file should honor what you selected.

**Comment by RikkiGibson** [comment]
Looks like there's a fix now :)

**Comment by jshiell** [comment]
😄 Not released yet mind, was just waiting for information on a couple of more issues. If that's not forthcoming I'll release it later this week (all being well).
