### ISSUE TITLE
WhitespaceAroundCheck is not marked by plugin

### ISSUE THREAD

**Issue by igorwojda** [jshiell/checkstyle-idea#356]
error: '{' is not preceded with whitespace.
com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAroundCheck

```
if (eventBus != null){
            
}
```

or

```
public void onTakeView(NotificationsView view){
}
```

**Comment by jshiell** [comment]
Thanks again 😄 

As with #357, it looks like we're failing to find the element. It's interesting that both relate to the parentheses - perhaps these elements in the parse tree are causing consistent problems.

**Comment by jshiell** [comment]
Closing as per #357
