### ISSUE TITLE
Specific warning suppression should be generated

### ISSUE THREAD

**Issue by igorwojda** [jshiell/checkstyle-idea#358]
Now `@SuppressWarnings("CheckStyle")`
Expected `@SuppressWarnings("checkstyle:ExecutableStatementCount")`

![2017-11-08_22-00-01](https://user-images.githubusercontent.com/530122/32576904-34f516aa-c4d0-11e7-89f3-3e04c2b16bdd.gif)

BTW "chechstyle" should be lowercase

**Comment by jshiell** [comment]
Thanks for the suggestion. We've never implemented this - the current behaviour is a default IDEA thing based on the plugin, rather than using the `SuppressWarningsHolder` in CS 5.7 and above.

Seems a fair feature request though. No promises on if or when, however, and this is pretty much in maintenance mode.

**Comment by uhafner** [comment]
Is there no API from IntelliJ to provide a specific suppression ID? Such a feature would be a so valuable addition to the plugin.

Is there at least a way to get the ID of the CheckStyle warning in the tool tip (i.e., error message) so I can copy it? It is quite cumbersome to search the CheckStyle docs or rule file for the correct rule name to suppress.

**Comment by jshiell** [comment]
Honestly no idea. The IDEA API is a horrendous undocumented mess which is primarily controlled via a mix of magic dependency injection and singletons. If you've any pointers to an API feature that covers what you suggest then they'd be appreciated.

**Comment by igorwojda** [comment]
Unfortunately, I don't know anything about IDEA API

**Comment by uhafner** [comment]
I see. Is there at least the possibility to change the message text? Currently the text is `CheckStyle: warning message`. It would be helpful to have `CheckStyle: RuleName: warning message`.

**Comment by jshiell** [comment]
This isn't done in the real-time scan at present (is it useful to add it?), but they rule names are present in the static-scan:

<img width="1046" alt="Screen Shot 2019-07-15 at 17 39 52" src="https://user-images.githubusercontent.com/1030482/61233060-93fe7200-a727-11e9-8a69-8d7e78b67a61.png">

**Comment by jshiell** [comment]
I did have another poke around - I thought I might be on to something with `ProblemDescriptor.ProblemGroup` (description: "It is used to split some inspection to several fake inspections"), but this seems to have no effect on `@SuppressWarnings` generation.

**Comment by jshiell** [comment]
Right, beta time. This is utterly hacked together, not really tested, may blow up your workstation etc etc.

It adds a new quick fix action called "Suppress for Checkstyle". Activate that and it'll hopefully generate a suppression. Hit right on it and, as per the IDEA standard, you should be able to suppress the plugin etc as per current behaviour.

Please let me know what you think: https://www.dropbox.com/s/0tz5b9r7o1wj1ds/checkstyle-idea-5.29.2.zip?dl=0

**Comment by uhafner** [comment]
This looks very promising  🎉🎉🎉 

The only thing that needs to be slightly changed:
you create `@SuppressWarnings("checkstyle:JavadocMethodCheck")`, but it should be `@SuppressWarnings("checkstyle:JavadocMethod")` (without the `Check`)

**Comment by jshiell** [comment]
Try two, this time with less `Check`. Thrown together really quickly, as I'm out tonight, but 🤞 

If this looks good then I'll *try* get some testing in and a release out this weekend.

https://www.dropbox.com/s/bmouy9hrxhxlz0u/checkstyle-idea-5.29.2b.zip?dl=0

**Comment by uhafner** [comment]
Your change looks good 👍 
I tried it on several warnings and all suppressed warnings disappear after the quick fix - these are fantastic news!

**Comment by uhafner** [comment]
Hurray!!!! Thank you very much!

**Comment by uhafner** [comment]
Since you fixed this issue using a `LocalQuickFix`: do you think it makes sense (and is feasible) to add more quick fixes for the individual rules of CheckStyle? E.g a quick fix for `FinalClass` will make the class final, and so on. 

I don't know your code base - but for me this looks not too complex and would be a good topic for a bachelor thesis for one of my students 😄

**Comment by jshiell** [comment]
It's probably not too hard, given most of the quick fixes probably exist already in the IDEA API; it's probably useful to people. Most of the work would be in mapping errors to fixes, I imagine.

The only catch is - as mentioned above - that any contributions do need to be tested (unlike a lot of the current code, which dates from last decade and before I learned my lessons in this regards), and needs to be easy to support. I've been bitten in the past where people have contributed a feature and then I've been left on the hook for fixing issues with it, and I'd prefer to avoid that again!

**Comment by uhafner** [comment]
Well, since I am giving courses in testing *and* development it is a requirement for all my students to write tests as well.

BTW: is there a mailing list or Gitter channel for your plugin? I don't want to spam your issues with unrelated questions?

**Comment by jshiell** [comment]
Touché :-D 

There's no mailing list or Gitter, as there's only one person doing regular maintenance, and only 1-2 others who maintain a presence (and have given major contributions in the past, bless them). I'd suggest just creating a new issue and keeping it there, so we don't keep spamming other people on this one.
