### ISSUE TITLE
plugin "CheckStyle-IDEA"is incompatible with this installation

### ISSUE THREAD

**Issue by silence2455** [jshiell/checkstyle-idea#361]
i have tryed to install the CheckStyle-IDEA-5.0.0/5.4.0/5.6.2/5.9.0/5.10.0/5.12.0,but unfortunately i got an error "plugin "CheckStyle-IDEA"is incompatible with this installation".
remark: my intellij idea version is 15.0.1, and the jdk version is 1.8
do you know why?

**Comment by jshiell** [comment]
The plugin.xml restricts the plugin to version 143.2370.31 (which, I think, is 15.0.6) or above.

To be honest version 15 support will be dropped at some point, as it's becoming a pain to test on.
