### ISSUE TITLE
CustomImportOrder module not importrd

### ISSUE THREAD

**Issue by mqzry** [jshiell/checkstyle-idea#362]
I tried importing the Google check style and it failed  to set the import rules of the code style scheme properly. It left it as it was.

I am willing to fix this myself. If needed.

**Comment by yeoji** [comment]
Hi @mqzry, I noticed that you mentioned this is incomplete, is there still work being done on this issue?

**Comment by mqzry** [comment]
No I abandoned it. Do not need it anymore. Also it turned out that IntelliJ does not support everything that checkstyle supports, so a generic mapper would be impossible.

I only planned to remove the dead code I added with my PR.

**Comment by yeoji** [comment]
I see, would it still be worth it trying to add the custom import order in to the formatter? Without handling the rest of the Checkstyle properties that are not supported in IntelliJ. I'm willing to try looking into this.

**Comment by jshiell** [comment]
Fixed merged - thanks very much @yeoji
