### ISSUE TITLE
Ability to exclude sub-paths from scanning

### ISSUE THREAD

**Issue by madjase** [jshiell/checkstyle-idea#364]
Hey Guys,

Love the work on the check style plugin and really appreciate it, its a great add-on to intellij. I've searched for the ability to exclude subpaths within a module to exclude from check style scanning. But it doesn't appear to be something that is supported.

The use case is that theres a number of java files that are generated at build time that our team doesn't care about. I've basically got a gradle build setup with the gradle checkstyle plugin that is configured to exclude these sub-paths within each module. I wanted to make my intellij match the gradle setup as much as possible, but i don't seem to be able to exclude certain paths from being scanned.

Is this something you guys would consider adding or am i just being dumb and missed it?

**Comment by tsjensen** [comment]
This is actually an absolutely valid request. In fact, it is already covered by core Checkstyle. Please refer to their [documentation](http://checkstyle.sourceforge.net/config_filters.html#SuppressionFilter) about suppression filters, which has some examples that should fit your case almost exactly (the one for "Maven-generated code", just replace the folder name with yours).

This will work with the Checkstyle-IDEA plugin.

**Comment by jshiell** [comment]
Thanks @tsjensen.

Indeed, we don't support it, as core Checkstyle already does. Hope this helps!
