### ISSUE TITLE
Reset particular project setting to default setting

### ISSUE THREAD

**Issue by phazebroek** [jshiell/checkstyle-idea#370]
I have a project with a custom checkstyle plugin setting. Now I've also setup a default setting for checkstyle. Now I want to remove the project specific settings so the default setting is applied.

I have closed my project, removed the checkstyle settings xml file from the .idea folder and then reopened the project, but to no avail. (other project was still open)

**Comment by jshiell** [comment]
When you say 'default' you mean the template project settings? I have no idea what IDEA does in this circumstance I fear, as we rely on IDEA to copy the templated settings into the project. The plugin itself doesn't do anything in this regard, and in the absence of any settings will provide generic defaults.

**Comment by phazebroek** [comment]
Hi Jshiell, Yes I mean the global IDE "template" settings that apply to all projects (if it's not overriden with specific profile settings)

I already reached out to Jetbrains for support, as I believed it was not related to the plugin but to IntelliJ itself... But they asked me to check with you, so here I am.

I created a fresh new project and that one did inherit the template project settings!
Perhaps I just misinterpreted the purpose of these template settings and they only apply to *new* projects created from that point on and they do not apply to existing projects, wether they have custom settings or the default original settings...

Can you confirm this?

**Comment by jshiell** [comment]
My understanding was that they only applied to *new* projects, but it's possible I'm wrong on this.

**Comment by jshiell** [comment]
Closing this as I believe it's still a template, i.e. copied at creation, and not updated to apply future changes.
