### ISSUE TITLE
Option for printing rule name in violation message

### ISSUE THREAD

**Issue by alexbde** [jshiell/checkstyle-idea#371]
I'm looking for an elegant way of suppressing checkstyle warnings in source code in IntelliJ.

If necessary I want to use annotations from SuppressWarningsFilter, e. g. `@SuppressWarnings("checkstyle:AbbreviationAsWordInName")`. To use this I need of course the name of the rule ("AbbreviationAsWordInName") and I cant find it in IntelliJ. It's written to output of Maven's checkstyle goal but it's exhausting to search for rule name at another location.

Would you maybe add an option to integrate Checkstyle rule name in IntelliJ's violation messages?

Eclipse plugin got something similar:

![temp](https://user-images.githubusercontent.com/17784818/35086069-141e179e-fc23-11e7-9c04-eb3ddd0fe881.png)

**Comment by jshiell** [comment]
I'm not a big fan of more permutations, so I've added it to the static scan output (which leaves the inspection a bit tidier). Released in 5.16.2.
