### ISSUE TITLE
on load, plugin overwrites manual changes to .idea/checkstyle-idea.xml

### ISSUE THREAD

**Issue by dsilvasc** [jshiell/checkstyle-idea#375]
I have the following .idea/checkstyle-idea.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="CheckStyle-IDEA">
    <option name="configuration">
      <map>
        <entry key="active-configuration" value="PROJECT_RELATIVE:$PRJ_DIR$/config/checkstyle/checkstyle.xml:content-platform" />
        <entry key="checkstyle-version" value="8.2" />
        <entry key="copy-libs" value="false" />
        <entry key="location-0" value="BUNDLED:(bundled):Sun Checks" />
        <entry key="location-1" value="BUNDLED:(bundled):Google Checks" />
        <entry key="location-2" value="PROJECT_RELATIVE:$PRJ_DIR$/config/checkstyle/checkstyle.xml:content-platform" />
        <entry key="property-2.config_loc" value="" />
        <entry key="scan-before-checkin" value="false" />
        <entry key="scanscope" value="JavaOnlyWithTests" />
        <entry key="suppress-errors" value="false" />
      </map>
    </option>
  </component>
</project>
```

I'm running into https://github.com/jshiell/checkstyle-idea/issues/374 and as a workaround, the plugin does work if I change $PRJ_DIR to $PROJECT_DIR in that file by hand before opening intellij.  I also go ahead and remove the bundled sun and google checks, and the empty config_loc property:

```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="CheckStyle-IDEA">
    <option name="configuration">
      <map>
        <entry key="active-configuration" value="PROJECT_RELATIVE:$PROJECT_DIR$/config/checkstyle/checkstyle.xml:content-platform" />
        <entry key="checkstyle-version" value="8.2" />
        <entry key="copy-libs" value="false" />
        <entry key="location-0" value="PROJECT_RELATIVE:$PROJECT_DIR$/config/checkstyle/checkstyle.xml:content-platform" />
        <entry key="scan-before-checkin" value="false" />
        <entry key="scanscope" value="JavaOnlyWithTests" />
        <entry key="suppress-errors" value="false" />
      </map>
    </option>
  </component>
</project>
```

However, after opening the project in intellij, something (the plugin?) re-writes .idea/checkstyle-idea.xml with the previous contents again.

I'm on a mac with Intellij 2017.3.  I grepped for "property-2.config_loc" from the old file contents in the ~/Library but didn't find anything.

Why is .idea/checkstyle-idea.xml being overwritten on open, and where do the contents come from?

**Comment by jshiell** [comment]
`PROJECT_DIR` isn't used anymore in the config as it clashes with IDEA. We have a migration in place to always rewrite it to `PRJ_DIR` as we assume it's a legacy configuration.

Sun/Google Checks are also built in and will be repopulated there if missing, as we assume - again - that it's a legacy configuration.
