### ISSUE TITLE
Cannot find annotation method 'id()' in type 'Storage': 2018.1 EAP 

### ISSUE THREAD

**Issue by akazancev** [jshiell/checkstyle-idea#376]
IJ build 181.3263.15
Storage annotation was deprecated for a while and now JB started to remove it.
we treat any warning as error and we do depend on checktyle plugin that causes our builds to fail.
As temporary workaround we disabled warnings from classfiles, but it would be nice this can be fixed on checkstyle side.

/Users/username/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/plugins.jetbrains.com/CheckStyle-IDEA-master-5.16.3/CheckStyle-IDEA/lib/checkstyle-idea-5.16.3.jar(org/infernus/idea/checkstyle/CheckStyleConfiguration.class): warning: Cannot find annotation method 'id()' in type 'Storage'
/Users/username/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/plugins.jetbrains.com/CheckStyle-IDEA-master-5.16.3/CheckStyle-IDEA/lib/checkstyle-idea-5.16.3.jar(org/infernus/idea/checkstyle/CheckStyleConfiguration.class): warning: Cannot find annotation method 'id()' in type 'Storage'
error: warnings found and -Werror specified
1 error
2 warnings

Thank you!

**Comment by jshiell** [comment]
Thanks for the heads up. 

At present the plugin is built against the v15 API, so I guess it's time to update it. It'll most likely happen closer to 2018.x going live, as nobody likes losing support for their IDE.

**Comment by jshiell** [comment]
Looks like the `@Storage` changes were introduced in IDEA 2016.1, so I've just dropped 15.0.6 support and updated the usage. Released in 5.17.0 - thanks for the early report! 😄

**Comment by akazancev** [comment]
@jshiell Great! Thank you very much for quick fix:)
