### ISSUE TITLE
Change notes url should be clickable

### ISSUE THREAD

**Issue by igorwojda** [jshiell/checkstyle-idea#378]
![image](https://user-images.githubusercontent.com/530122/36026006-2614a7c6-0d8d-11e8-8d27-10799ded6bf1.png)

**Comment by jshiell** [comment]
Thanks for the feedback. I agree, but this is out of my control - JetBrains provide a text field for the 'change notes' when you upload a plugin, which has a habit of destroying any formatting, let alone rich text. (If you know of a way around this, I'd welcome the knowledge!)

What I've done to assist with this is that the plugin, as of 5.17.0, will provide a notification after update, and this will contain a clickable link.
