### ISSUE TITLE
Lombok's "val" construct is not recognized by Checkstyle's LocalFinalVariableName rule

### ISSUE THREAD

**Issue by mmoayyed** [jshiell/checkstyle-idea#382]
Using the latest version of the checkstyle-idea plugin with IDEA 2017.x, I have a project that uses Lombok's `val` construct:
https://projectlombok.org/features/val

Where this:

```java
final ArrayList<String> example = new ArrayList<String>();
```

Can be written as:

```java
val example = new ArrayList<String>();
```

My checkstyle ruleset has a rule that requires local variables to be declared as final, just as `val` would effectively do. 

```xml
        <module name="LocalFinalVariableName">
            <property name="severity" value="error"/>
        </module>
```
However, I see the following warning:

![image](https://user-images.githubusercontent.com/1205228/36526973-6ccadb6c-17c5-11e8-95ac-847cfdd9048b.png)

Could this be an issue with the plugin, or is this more of a concern with checkstyle itself?

**Comment by jshiell** [comment]
I fear this is almost certainly a Checkstyle limitation - we just report the problems that Checkstyle returns, and certainly have no opinion on what the code looks like (or even if it parses). 

Looks like there's some discussion [over in the Checkstyle GitHub project](https://github.com/checkstyle/checkstyle/issues/5470).
