### ISSUE TITLE
Allow specifying filetypes in scan scope

### ISSUE THREAD

**Issue by aforcier** [jshiell/checkstyle-idea#386]
It would be really useful to expand the scan scope options with an option to specify which filetypes to include (more than just Java, but not _all_ sources). Something like:

Only Java sources (but not tests)
Only Java sources (including tests)
Only sources with filetypes (but not tests) [text field for entry appears]
Only sources with filetypes (including tests) [text field for entry appears]
All sources (but not tests)
All sources (including tests)
All files in the project

My personal use case would be to check `.java`, `.kt`, and `.xml` files inside the source directories.

(I'm currently able to accomplish this for checkstyle in gradle, but would love for the plugin to be able to have the same behavior:)

```groovy
task checkstyle(type: Checkstyle) {
  source 'src'
  include '**/*.java'
  include '**/*.kt'
  include '**/*.xml'
  exclude '**/gen/**'

  classpath = files()
}
```

**Comment by tsjensen** [comment]
This feature is actually already covered by core Checkstyle, for the most part, I think.

You can restrict the file extensions using [Checker properties](http://checkstyle.sourceforge.net/config.html#Checker). The docs give this example (adapted for your case):
> To configure a Checker so that it handles files with the java, xml, properties extensions:
```xml
<module name="Checker">
  <property name="fileExtensions" value="java, kt, xml"/>
  ...
</module>
```
The folder with generated source can be excluded using [filters](http://checkstyle.sourceforge.net/config_filefilters.html):
```xml
<module name="BeforeExecutionExclusionFileFilter">
  <property name="fileNamePattern" value="[/\\]gen[/\\]"/>
</module>
```

**Comment by aforcier** [comment]
These worked perfectly, at least for my use case - thanks @tsjensen!

Since core Checkstyle covers this I guess the feature would be unnecessary - I'll close this issue.

**Comment by jshiell** [comment]
Thanks @tsjensen - a legend as always 👍
