### ISSUE TITLE
Plugin fails to scan UTF-8 files with non-ASCII characters files on windows only

### ISSUE THREAD

**Issue by brenn** [jshiell/checkstyle-idea#389]
We have a mix of Linux and Windows users and the checkstyle-idea plugin fails during scan of UTF-8 Java files that contain non-ASCII  characters. 

The exception is thrown by the checkstyle library :  
TokenStreamRecognitionException occurred while parsing file ....     Unexpected character 0xa6 in identifier

I'm aware of the fact that Checkstyle doesn't really support UTF-8 files : http://checkstyle.sourceforge.net/writingchecks.html#Limitations 
 "Java code should be written with ASCII characters only, no UTF-8 support." 

However, the same version of checkstyle (8.8) works fine in other situations:
- From maven checkstyle plugin 
- From Intellij with checkstyle plugin on MacOS and on Linux  

It's only on Windows that the plugin fails, which means there must be a bug in the plugin...? 

I took a look at the plugin code and according to the stacktrace (attached) the plugin fails in this invocation of the method Checker.process() inside the checkstyle library 

```
    private CheckStyleAuditListener processAndAudit(final List<File> files,
                                                    final CheckStyleAuditListener auditListener)
            throws CheckstyleException {
        final Checker checker = checkerWithConfig.getChecker();
        synchronized (checkerWithConfig.getChecker()) {
            checker.addListener(auditListener);
            try {
                checker.process(files);
            } finally {
                checker.removeListener(auditListener);
            }
        }
        return auditListener;
    }

```

The list of files that are passed on by the plugin to the checkstyle library seem to be of type ScannableFile in the intellij Plugin system. AFAIK it seems the class is making copies of the files to be scanned, and doing some character encoding conversion in the process.  

Could there be a bug in this code that is visible on windows only?  

We are unfortunately not able to enforce checkstyle compliance in our project build until until this plugin issue has been resolved. 
The problem is easy to reproduce on windows using this: 

Plugin version 5.18.5
Checkstyle version:  8.8
IntelliJ version:  2017.3.5

Code with norwegian character in test method and that causes plugin to fail with attached stack trace:
```
public class FooTest {

    @Test
    public void TestWithTheNorwgianCharacter_Æ() {
        assertThat(true);
    }
}

```

Any hints would be greatly appreciated..

------------ stacktrace

```
The scan failed due to an exception: TokenStreamRecognitionException occurred while parsing file C:\dev\...\FooTest.java. Root cause: Unexpected character 0x2020 in identifier line 10:47: Unexpected character 0x2020 in identifier   at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:405)   at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)   at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:134)   at antlr.TokenBuffer.fill(TokenBuffer.java:69)   at antlr.TokenBuffer.LA(TokenBuffer.java:80)   at antlr.LLkParser.LA(LLkParser.java:52)   at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.modifiers(GeneratedJavaRecognizer.java:519)   at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.field(GeneratedJavaRecognizer.java:3232)   at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classBlock(GeneratedJavaRecognizer.java:2542)   at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.classDefinition(GeneratedJavaRecognizer.java:634)   at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinitionInternal(GeneratedJavaRecognizer.java:556)   at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.typeDefinition(GeneratedJavaRecognizer.java:389)   at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:202)   at com.puppycrawl.tools.checkstyle.JavaParser.parse(JavaParser.java:94)   at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:181)   at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:83)   at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:320)   at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:290)   at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:217)   at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:75)   at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:52)   at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:22)   at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)   at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:76)   at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:45)   at org.infernus.idea.checkstyle.checker.ScanFiles.lambda$checkFiles$6(ScanFiles.java:194)   at java.util.Optional.map(Optional.java:215)   at org.infernus.idea.checkstyle.checker.ScanFiles.checkFiles(ScanFiles.java:194)   at org.infernus.idea.checkstyle.checker.ScanFiles.processFilesForModuleInfoAndScan(ScanFiles.java:153)   at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:76)   at org.infernus.idea.checkstyle.checker.ScanFiles.call(ScanFiles.java:32)   at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:338)   at java.util.concurrent.FutureTask.run(FutureTask.java:266)   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)   at java.lang.Thread.run(Thread.java:745) 

```

**Comment by jshiell** [comment]
Thanks for the report - I'll try have a look this weekend. But now for the bad news - it will be just a look, as I only have a OS X machine. Even at work it's all OS X or Linux - no Windows. So I'd expect yes, it'll be a bug in the plugin, but the only way I have to find it is inspection. As such I'll certainly try, but I can't promise anything.

**Comment by brenn** [comment]
Hi
Nevertheless, much appreciated. I could   assist, but would need some hints
on how to set up  things for debugging.  I have cloned the plugin source
repo and the checkstyle code repo . Guess i need to set up idea for plugin
development and then run the debugger or something...
Erik

**Comment by jshiell** [comment]
Indeed that's more or less spot on - in theory, you should be able to clone the repo; import the Gradle file into IDEA; and then debug the `runIdea` Gradle task, which will trigger a download on IDEA-IC-2016.1 and debug the plugin within that. I do say 'in theory' as I've never done it on Windows, and it's been a while since I've clean installed it to be honest.

Looking at the code, my suspicion is that the value isn't being written to disk as UTF-8; both the Linux & macOS VMs (in modern incarnations, at least) default to UTF-8, but from memory the Windows one uses ISO-8859-1 or similar. We attempt to honour the character encoding of the editor; only falling back to UTF-8 if we can't read this. The code in question lives in [ScannableFile](https://github.com/jshiell/checkstyle-idea/blob/master/src/main/java/org/infernus/idea/checkstyle/checker/ScannableFile.java) - in particular: 
```
    private void writeContentsToFile(final PsiFile file, final File outFile) throws IOException {
        final String lineSeparator = CodeStyleSettingsManager.getSettings(file.getProject()).getLineSeparator();

        final Writer tempFileOut = writerTo(outFile, charSetOf(file));
        for (final char character : file.getText().toCharArray()) {
            if (character == '\n') { // IDEA uses \n internally
                tempFileOut.write(lineSeparator);
            } else {
                tempFileOut.write(character);
            }
        }
        tempFileOut.flush();
        tempFileOut.close();
    }
```
And
```
    private Charset charSetOf(final PsiFile file) {
        return virtualFileOf(file)
                .map(VirtualFile::getCharset)
                .orElseGet(() -> Charset.forName("UTF-8"));
    }
```
It looks correct, at first glance, but there's of course one big hole - if the editor has defaulted to the wrong type then everything will go tits up.

Could you please check if the editor encoding in IDEA is set to UTF-8? There's a chance that it's inferring it from the file and falling back to the default (which would differ between Windows and everything else). I'd be mildly surprised if it was this, but only mildly.

I guess the next thing to try is a debugger, assuming it turns out to be relatively easy to get going. If we could stick a breakpoint in that method then we could see what character set it's writing out at - and also the exact character information it's writing out. If there's a mistake in the buffer read/write then I think it should be visible at that point.

**Comment by brenn** [comment]
I thought it may have something to do with the default encoding in IDEA, so I tried to change it.
By default the IDEA settings are as follows on windows:
 Global encoding:  UTF-8
 Project encoding: System default (windows-1252)
 
Tried to change the latter to UTF-8 as well, but didn't help. Not that it should matter I guess, the file I'm testing with is an UTF-8 file according to IDEA (encoding shown in lower right part of the IDEA editor)

Anyhow, thanks for pointing me in the right direction, I will try to set up things at my end for further debugging... 

erik

**Comment by brenn** [comment]
Seems I have to do some reading before getting things setup for debugging. I tried to follow the guide here https://www.jetbrains.com/help/idea/running-and-debugging-plugins.html  , but don't really understand.   How do I hook into the checkstyle-plugin from the new idea instance that starts up after executing a "Plugin" run-configuration ...? 

I tried this:
- Downloaded the checkstyle-plugin source and opened in my standard IDEA ultimate edition
- Create a new "Plugin runner" and manually edited the  iml file and changed JAVA_MODULE -> PLUGIN_MODULE (to allow me to actually select the module in the run-configuration)
- Executed the plugin run-configuration, starting a new IDEA instance 
In the new IDEA instance I did  the following: 
- created a simple commandline project and a Foo main class, containing a method with a non-ascii character in it (to trigger checkstyle plugin error)  
- Activated the checkstyle-plugin and pointed it to my xml configuration-file

what now? how do i tell idea to break at a line in the checkstyle plugin source?

**Comment by jshiell** [comment]
Morning. It's a bit messy, isn't it? :-) This is why I switched to the Gradle plugin instead, which should make it a bit easier. 

If you import the project as a Gradle project, you should then be able to run the Gradle target `run-idea` in debug mode. At that point it should start up a copy of IDEA-CE 2016.1 with the plugin embedded. You can then set breakpoints in the master copy of IDEA, as you'd expect. You shouldn't need to use any runner configurations beyond the Gradle targets.

**Comment by brenn** [comment]
Hi,

Ok, so I tried your approach. When running the gradle plugin with
 ./gradlew runIdea  them  intellij  2016.1  starts up, but there is some
incompatibility problem. I see this error message :

> WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at
root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
> WARN: Can't load PluginDescriptor[name='CheckStyle-IDEA',
classpath='C:\dev\checkstyle-idea\build\idea-sandbox\plugins\CheckStyle-IDEA']:
since build 145.2070 does not match IC-145.258


Any clues?

Also, assuming the above is solved,  can you be more specific on what to do
after the intellij instance has started.  You wrote that I should set  a
breakpoint in the "master copy of IDEA"??  Is the "master copy" the
instance started by the gradle plugin?  The new instance starts without any
project, I don't see the source of the embedded plugin....

Here is what i want to do:

- create a class Foo with a method containing a non-ascii character
- I wish to execute checkstyle plugin on it and have it break on the code
you pin-pointed in the plugin so I can investigate

starting to feel kinda useless here...

**Comment by jshiell** [comment]
> starting to feel kinda useless here...

I fear this process has always been fiddley. It's not you, it's bloody IDEA 😄 

I don't think the registry error is a huge problem, but the second warning does worry me as it suggests the plugin isn't loading. I haven't seen it before, I fear, but I'll shout if anything occurs to me.

On the "master copy" - I was thinking of launching the Gradle task via the Gradle panel in IDEA - hence the version of IDEA you launch from being the 'master copy'. Indeed, my comment makes no sense if launching from the command line. AFAIK you'd have to connect a remote debugger if you want to launch via the CLI - it's needed for a few edge cases with the class path, but I general avoid it and just launch from IDEA.

My suggestion would be:
- launch IDEA (your local copy, henceforth the 'master' IDEA)
- import the project via the Gradle file
- use the Gradle panel on the right-hand-side of to launch the `run-idea` target in debug
- you should now have a debug run in the master IDEA that will launch a child copy of IDEA. Hence you can now set breakpoints etc from the master

Hope that makes a bit more sense that my previous attempt. Please shout if not!

**Comment by brenn** [comment]
Never got time to follow up on the debug setup.  However, we found another solution.  After setting the "charset" property to UTF-8 in our checkstyle.xml  the plugin works ok again.

```
<module name="Checker">
    <property name="charset" value="UTF-8"/>
     ...
```

**Comment by jshiell** [comment]
Good spot! Looking at the docs I see the default is `System property "file.encoding"`, so that nicely shows the platform difference. Glad you found a resolution!
