### ISSUE TITLE
Highlight issues in IntelliJ 2017.3.5

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [jshiell/checkstyle-idea#390]
Hi there!

I created the following check rules in order to test this plugin:

```
<?xml version="1.0"?>
<!DOCTYPE module PUBLIC
        "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
        "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
    <property name="severity" value="warning"/>
    <property name="fileExtensions" value="java, properties, xml"/>
    <module name="TreeWalker">
        <module name="EmptyLineSeparator">
            <property name="allowMultipleEmptyLinesInsideClassMembers" value="false"/>
        </module>
        <module name="LineLength">
            <property name="max" value="10"/>
        </module>
    </module>
</module>
```

So multiple empty lines and lines with more than 10 caracteres should fire a warning in the IDE. When I run the "Check Current File", the IDE doesn't show very well which lines have issues, as you can see in the print below:

![image](https://user-images.githubusercontent.com/12160864/38068112-bfd72f78-32e5-11e8-88d7-3182573e4af4.png)

The violations are shown with a blank warning cursor at the end of each violated line. If I hover that warning, no popup is shown to explain which rule was violated.

Here is the plugin settings for the real time scan:

![image](https://user-images.githubusercontent.com/12160864/38068157-128b7fda-32e6-11e8-94dd-358452f16d70.png)

I tried each Severity option, but the highlight was always kept at the end of the line, without showing the violation popup.

Is this the expected behavior for this plugin?

For example, the Sonar plugin highlight the entire line when a rule is violated, making it easy to identify the line and to hover to see what is going on.

Best regards,
Rafael Pacheco.

**Comment by jshiell** [comment]
Hey - thanks for your feedback. I really appreciate it when people go to such effort to write good reports!

The bad news, however - this is more of less expected. However, I agree it's not ideal. I just don't know how to fix it.

The reason this occurs is that Checkstyle reports issues via line number/character. This makes it really easy to highlight the errors in a text based system. However, IDEA's inspection system isn't line based, but tree based (IDEA's `InspectionManager` class is where we create the problem descriptors that IDEA needs) - we do a bit of work post scan to convert the line/char references into the element (`PsiElement`) in the parse tree that represents the error in [ProcessResultsThread](https://github.com/jshiell/checkstyle-idea/blob/master/src/main/java/org/infernus/idea/checkstyle/csapi/ProcessResultsThread.java). This works nicely where a single element matches - but it's messier where the error relates to structure such as line length.

I'm very welcome to ideas on how this could be improved, as I do agree a line highlight would be the more appropriate option in that case.

A silly workaround: you could turn on the `Line is longer than allowed code style` inspection, and import the code style from the Checkstyle file. Appreciate this isn't a great option, but perhaps better than nothing.

Please feel free to reopen this if you've ideas for enhancements, or don't feel I've answered your question - and happy Easter!
