### ISSUE TITLE
Crashes when adding custom checkstyle in Android Studio (Osx)

### ISSUE THREAD

**Issue by DwordPtr** [jshiell/checkstyle-idea#393]
I'm trying to add a custom checkstyle to the plugin in Android Studio on a mac with high sierra.
It crashes whenever I open the file dialog.
It works fin in Intellij community edition though.

**Comment by jshiell** [comment]
What do you mean by 'crash'? Is an exception thrown? If so, what is it?

If Android Studio is actually crashing then that's a problem that should go to Jetbrains.

**Comment by jshiell** [comment]
Closing due to no further info.
