### ISSUE TITLE
How to Run checkstyle dynamically in Android Studio?

### ISSUE THREAD

**Issue by surendrad** [jshiell/checkstyle-idea#394]
I was able to download the code and built the plugin. Also imported the plugin to Android Studio and after restart able to see the Checkstyle window, but cannot figure out a way to start a scan.

Any ideas on how I can start a scan on the project?

**Comment by jshiell** [comment]
There are two options - one is that the 'play' button should become available in the CS-IDEA tool window when the active editor contains a valid (e.g. `.java`) file. The other option is that you can turn on the Checkstyle inspection to have live scans run against the editor.

**Comment by surendrad** [comment]
Thanks. This helped.
