### ISSUE TITLE
Configurable <suppressionsLocation>

### ISSUE THREAD

**Issue by fprochazka** [jshiell/checkstyle-idea#399]
Hi,
I'm having trouble forcing the plugin to honor our suppressions file.

We've extracted the checkstyle config to [a separate library](https://github.com/Cogvio/checkstyle-config) which is then configured to use `suppressions.xml` that is specific for the project and maven build works as expected.

But I have found no way to configure the checkstyle IDEA plugin to honor our suppressions file. It was only honored, when the checkstyle.xml included

```xml
<module name="SuppressionFilter">
    <property name="file" value="${checkstyle.config.path}/suppressions.xml"/>
</module>
```

and the property was configured accordingly. But now that the configs are separated, I don't think this makes any sense.

I think it would be great to have an option to specify suppressions file for each checkstyle ruleset.

**Comment by jshiell** [comment]
Hey,

How are you configuring the Maven build to use the Checkstyle suppressions file? The main way I've seen this done in the past is via a property, as you suggest. In general the goal is to avoid as much plugin-specific logic as possible and rely on the Checkstyle file itself, so that rules are consistent across Maven/Gradle/Eclipse/IDEA/etc.

**Comment by fprochazka** [comment]
We have a multi-module setup, one of the modules is `parent` with this build plugin and every other module (except `build-tools` mentioned later has it as it's parent pom)

```xml

    <artifactId>maven-checkstyle-plugin</artifactId>
    <version>${maven-checkstyle-plugin.version}</version>
    <dependencies>
        <dependency>
            <groupId>com.cogvio</groupId>
            <artifactId>build-tools</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.cogvio</groupId>
            <artifactId>checkstyle-config</artifactId>
            <version>${cogvio-checkstyle.version}</version>
        </dependency>
        <dependency>
            <groupId>com.puppycrawl.tools</groupId>
            <artifactId>checkstyle</artifactId>
            <version>${checkstyle.version}</version>
        </dependency>
    </dependencies>
    <executions>
        <execution>
            <id>validate</id>
            <phase>validate</phase>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <configLocation>cogvio_checkstyle.xml</configLocation>
        <suppressionsLocation>checkstyle_suppressions.xml</suppressionsLocation>
        <encoding>UTF-8</encoding>
        <consoleOutput>true</consoleOutput>
        <failOnViolation>true</failOnViolation>
        <violationSeverity>warning</violationSeverity>
        <includeTestSourceDirectory>true</includeTestSourceDirectory>
    </configuration>
</plugin>
```

this dependency is part of the project as `build-tools` module, according to https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/multi-module-config.html

```xml
        <dependency>
            <groupId>com.cogvio</groupId>
            <artifactId>build-tools</artifactId>
            <version>${project.version}</version>
        </dependency>
```

this dependency is external project from here https://github.com/Cogvio/checkstyle-config

```xml
        <dependency>
            <groupId>com.cogvio</groupId>
            <artifactId>checkstyle-config</artifactId>
            <version>${cogvio-checkstyle.version}</version>
        </dependency>
```

and because it's multi-module, the checkstyle is running from project root, so the suppressions have to be written like this (note the `.*` at the beginning)

```xml
<suppress files=".*[\\/]src[\\/]test[\\/]java[\\/].*" id="VisibilityModifierCode"/>
```

----

@jshiell if this could be "just" auto-loaded from `pom.xml` of the given module, that would be best :)
