### ISSUE TITLE
Load checkstyle config from a dependency

### ISSUE THREAD

**Issue by fprochazka** [jshiell/checkstyle-idea#400]
Checkstyle can be currently added as a file in local filesystem or HTTP resource

![image](https://user-images.githubusercontent.com/158625/42297497-132867ca-8000-11e8-8b17-a16f653984ac.png)

I would like to propose a third option - which is supported by native checkstyle

```xml
<plugin>
    <artifactId>maven-checkstyle-plugin</artifactId>
    <version>${maven-checkstyle-plugin.version}</version>
    <dependencies>
        <dependency>
            <groupId>com.cogvio</groupId>
            <artifactId>build-tools</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.cogvio</groupId>
            <artifactId>checkstyle-config</artifactId>
            <version>${cogvio-checkstyle.version}</version>
        </dependency>
        <dependency>
            <groupId>com.puppycrawl.tools</groupId>
            <artifactId>checkstyle</artifactId>
            <version>${checkstyle.version}</version>
        </dependency>
    </dependencies>
    <configuration>
        <configLocation>cogvio_checkstyle.xml</configLocation>
        <suppressionsLocation>checkstyle_suppressions.xml</suppressionsLocation>
    </configuration>
</plugin>
```

when you specify dependencies for the checkstyle plugin that provide the config to the classpath of the plugin (as in the example), you can then specify the `configLocation` and `suppressionsLocation` as classpath resource, because checkstyle will load them from it's own classpath.

It would be really great, if the IDEA plugin could be configured to load the checkstyle config (and [suppressions #399](https://github.com/jshiell/checkstyle-idea/issues/399) ) from a dependency.

It would be even better if it would be possible to pickup the installed version from the project's maven build - nobody could forget to change to the newer version.

**Comment by jshiell** [comment]
This seems a very fair feature request, as I know this model is reasonably common and it would probably be useful to a fair subset of users.

The bad news is my work on this plugin is mostly focused on maintenance at present - I haven't used it myself for years, and indeed have my own concerns on the use of lint tools in the development process. I do get the urge to improve things from time to time, but it's not something I'd recommend relying on. As such, it may be a long time before you see any movement on this.

Having said that, I'm very happy to accept tested PRs 😄 

> It would be even better if it would be possible to pickup the installed version from the project's maven build - nobody could forget to change to the newer version.

This one is harder - I've resisted this in the past for the simple reason that it's not simple. We'd have to drill into the Maven model to find the information, and we'd have to reimplement for every variant (e.g. Gradle, SBT, ...). We'd then also open the chance of breaking on new/old versions of the build tools and ... well, it gets exciting 😁

**Comment by fprochazka** [comment]
I completely understand :)

If I happen to have enough time on my hands to learn how to write IDEA plugins, I might try to contribute this :)

**Comment by jshiell** [comment]
Well, thinking about it it seemed quite easy in theory. So I slapped together something ... it's probably full of bugs; I suspect you need to apply the classpath before trying to add a file on it; it doesn't address suppressions at all - but hey, it's a start. I'll try pick it up at the weekend and see if I can refine it enough to make it releasable.

**Comment by fprochazka** [comment]
@jshiell nice! I'll happily test it in a spare moment :)

**Comment by jshiell** [comment]
Right, test build time! This has modifications to check resources against the classpath before loading, and not remove them from the DOM if they exist there. Checkstyle itself should then load them from the CP - seems to work for suppression files, at least.

This was surprisingly messy, due to the need to make the class-loader accessible. There's still a nasty hack in there where I cheat and use ServiceManager to shortcut access - not pretty at all. In any case, given the surprising surface area hit I'd appreciate it if you could give this test build a try at some point, just as a second sanity check - and, of course, to make sure I've hit your use case 😄 

Disclaimer: it's 30C and it's a wonder I can stand up, let alone write code ;-)

https://www.dropbox.com/s/6e24ffcaamdh6rv/CheckStyle-IDEA-5.21.0.zip?dl=0

**Comment by jshiell** [comment]
Released as 5.21.0 - please reopen if you have any issues.

**Comment by abuechler** [comment]
@jshiell Hey James, we have configured our maven-checkstyle-plugin to read the config location via a dependency:

```
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <version>${maven-checkstyle-plugin.version}</version>
        <configuration>
          <configLocation>checkstyle/our-checks.xml</configLocation>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>com.example</groupId>
            <artifactId>build-tools</artifactId>
            <version>${buildtools.version}</version>
          </dependency>
        </dependencies>
....
```

Looking at this issue I thought that we could now configure the plugin to read the configuration from the dependency as well. But I always get "The location could not be loaded. Couldn't read classpath resource /checkstyle/our-checks.xml. Any ideas on whats missing?

**Comment by jshiell** [comment]
Have you added the dependency to the third-party class path?

**Comment by abuechler** [comment]
@jshiell What do you mean by third-party class path? Do you mean global library as described [in the IntelliJ Docs](https://www.jetbrains.com/help/idea/library.html)? Thats what I did...

**Comment by jshiell** [comment]
The lower section of the Checkstyle-IDEA configuration panel allows you to add JARs to the plugin class path - e.g. third-party checks, or JARs as resources.

**Comment by abuechler** [comment]
Yeah, that opens a "Select file dialog" and then points to an OS specific path...

That hole point of specifying it as maven dependency is that it will resolve dynamically no matter where it ends up on the filesystem. At least that's why we're configuring the maven-checkstyle-plugin this way.

**Comment by jshiell** [comment]
You've still got to make IDEA aware of the JAR somehow 🤷‍♂️ Once it's aware of the JAR via third-party class path then you can reference the rules file via the class path reference.

We don't - and won't - read the Maven model, because I've no interest in integrating with multiple build-systems, and IDEA doesn't appear to have a generic way of exposing this information (which seems fair, as I have no idea how you'd extract an equivalent model for Gradle, Maven, and SBT and their relevant Checkstyle plugins).

**Comment by fprochazka** [comment]
Took me a while to figure out, that you have to add the JARs to the "Third-Party Checks", but after that the loading from classpath works great, thanks!

**Comment by jshiell** [comment]
@fprochazka No worries :-) Do you think there's some phrasing/wording I could/should change around that panel to make this functionality more obvious?

**Comment by fprochazka** [comment]
@jshiell a text hint next to the option for jars, that you have to add the deps using the "3rd party checks" dialog would definitely make it more obvious

**Comment by jshiell** [comment]
<img width="490" alt="Screen Shot 2019-05-18 at 11 14 57" src="https://user-images.githubusercontent.com/1030482/57968117-4a2f2080-795e-11e9-94dc-118c87f6d6f1.png">

@fprochazka does this make more sense?

**Comment by fprochazka** [comment]
@jshiell awesome :+1:
