### ISSUE TITLE
AvoidStarImport excludes don't work

### ISSUE THREAD

**Issue by ThexXTURBOXx** [jshiell/checkstyle-idea#401]
CheckStyle IDEA always says, that my static imports with stars don't pass the CheckStyle test (in the Editor, they are marked as red, too). Even though, I defined them as excludes in the checkstyle.xml file

**Comment by jshiell** [comment]
Can you please attach the relevant rules file?

**Comment by ThexXTURBOXx** [comment]
https://hastebin.com/silamiyaji.xml

**Comment by jshiell** [comment]
Thanks. 

What version of Checkstyle are you using? The rules file doesn't appear to work with the latest (8.11 - `SuppressionCommentFilter is not allowed as a child in Checker`).

Does this issue occur with native Checkstyle of the same version? (e.g. [checkstyle-all.jar](https://github.com/checkstyle/checkstyle/releases/)).

If so, do you have a snippet of code to reproduce this? I can presumably knock one together but it helps to ensure we're both on the same page. Cheers.

**Comment by jshiell** [comment]
I've just done a quick check with Checkstyle 8.0 (the newest version that supports `SuppressionCommentFilter` as a child of `Checker`) and it seems okay (and consistent with the command line):

<img width="273" alt="screen shot 2018-07-09 at 17 19 34" src="https://user-images.githubusercontent.com/1030482/42462849-59dda0e6-839c-11e8-96c7-62e1e5329762.png">

<img width="662" alt="screen shot 2018-07-09 at 17 19 41" src="https://user-images.githubusercontent.com/1030482/42462856-5ddee466-839c-11e8-8ec8-c118817559d9.png">

I fear I'll need more information to continue.

**Comment by jshiell** [comment]
Note if I add a class to the whitelisted static import, e.g. `import static java.net.Authenticator.*;`, it does fail, but it's consistent with the command line version:

<img width="750" alt="screen shot 2018-07-09 at 17 22 07" src="https://user-images.githubusercontent.com/1030482/42462934-9f4f81d0-839c-11e8-8d08-1a6cad9a06e1.png">

```
$ java -jar ~/Downloads/checkstyle-8.0-all.jar -c ../../checkstyle-idea/test-configs/issue-401.xml Issue401.java
Starting audit...
[ERROR] /Users/jshiell/Projects/JavaPlayground/src/Issue401.java:0: File does not end with a newline. [NewlineAtEndOfFile]
[ERROR] /Users/jshiell/Projects/JavaPlayground/src/Issue401.java:1: Using the '.*' form of import should be avoided - java.net.Authenticator.*. [AvoidStarImport]
[ERROR] /Users/jshiell/Projects/JavaPlayground/src/Issue401.java:2: Using the '.*' form of import should be avoided - java.boo.*. [AvoidStarImport]
[ERROR] /Users/jshiell/Projects/JavaPlayground/src/Issue401.java:2: Wrong order for 'java.boo.*' import. [ImportOrder]
Audit done.
Checkstyle ends with 4 errors.
```

**Comment by ThexXTURBOXx** [comment]
Ok, I was just silly and forgot to reimport the xml settings file... I'm so sorry! :D Thanks for the quick help and answers though ^^

**Comment by jshiell** [comment]
No worries, glad it's all working now 👍
