### ISSUE TITLE
Plug in failed to install

### ISSUE THREAD

**Issue by adwilk** [jshiell/checkstyle-idea#403]
After downloading the plug in and restarting Intellij I get the following error, and the plugin is not installed: 

`The IDE failed to install some plugins.
Most probably, this happened because of a change in a serialization format.
Please try again, and if the problem persists, please report it
to http://jb.gg/ide/critical-startup-errors

The cause: /Users/awilkin/Library/Application Support/IntelliJIdea2018.1/CheckStyle-IDEA/checkstyle/classes/org/infernus/idea/checkstyle/service/cmd/OpDestroyChecker.class (No such file or directory)`

IntelliJ IDEA 2018.1 (Ultimate Edition)
Build #IU-181.4203.550, built on March 26, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6

**Comment by jshiell** [comment]
This was on my todo list for the weekend - what was the problem in the end?

**Comment by adwilk** [comment]
The problem was my end sorry. IntelliJ was failing to write to the application support folder due to a permissions error.

**Comment by jshiell** [comment]
Thanks for the update - no worries, glad it's sorted!

**Comment by mohammedahban** [comment]
also I got this problem.....
The IDE failed to install some plugins.

Most probably, this happened because of a change in a serialization format.
Please try again, and if the problem persists, please report it
to http://jb.gg/ide/critical-startup-errors

**Comment by jshiell** [comment]
In the past this has been due to client problems, in particular permissions errors - not a fault with the plugin. I can't help you further without extra information such as a stack trace showing the casue of the problem.
