### ISSUE TITLE
PRJ_DIR is undefined

### ISSUE THREAD

**Issue by kevin-wayne** [jshiell/checkstyle-idea#404]
When I load a project, I receive the error message "Load error: undefined path variables; PRJ-DIR is undefined. Path variables are used to substitute absolute paths in IDEA project files and allow project file sharing in version control systems. Some of the files describing the current project settings contain unknown path variables and IDEA cannot restore those paths."

When I click "Fix It", I see that there is no path variable named PRJ_DIR in "Configure Path Variables." My checkstyle-idea.xml file is

```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="CheckStyle-IDEA">
    <option name="configuration">
      <map>
        <entry key="active-configuration" value="LOCAL_FILE:$PRJ_DIR$/.lift/checkstyle-cos126.xml:COS 126 Checks" />
        <entry key="checkstyle-version" value="8.5" />
        <entry key="copy-libs" value="false" />
        <entry key="location-0" value="BUNDLED:(bundled):Sun Checks" />
        <entry key="location-1" value="BUNDLED:(bundled):Google Checks" />
        <entry key="location-2" value="LOCAL_FILE:$PRJ_DIR$/.lift/checkstyle-cos126.xml:COS 126 Checks" />
        <entry key="property-2.basedir" value="$PROJECT_DIR$" />
        <entry key="property-2.suppressions" value="checkstyle-suppressions.xml" />
        <entry key="scan-before-checkin" value="false" />
        <entry key="scanscope" value="JavaOnly" />
        <entry key="suppress-errors" value="false" />
        <entry key="thirdparty-classpath" value="$PRJ_DIR$/.lift/checkstyle-lift.jar" />
      </map>
    </option>
  </component>
</project>
```

If I manually replace PRJ_DIR with PROJECT_DIR in checkstyle-idea.xml, then everything works for a bit. Except that Checkstyle-IDEA replaces PROJECT_DIR with PRJ_DIR the next time I open it. 

Related to #375 and #374. But I have no other occurrences of PRJ_DIR in any other .xml configuration file. I'm running IntelliJ IDEA 2018.1.5 on OS X and just updated to Checkstyle-IDEA 5.21.0.

**Comment by kevin-wayne** [comment]
Thanks for the rapid response (and great product)! I copied Checkstyle-IDEA-5.21.1 to the appropriate place and the configuration file settings seem to be working smoothly (i.e., works with $PROJECT_DIR$ and doesn't change it back to $PRJ_DIR$ when it rewrites checkstyle-idea.xml).

I believe there is a related issue with the Third-Party Checks. When I add a third-party check, the Third-Party Checks box displays it as "/Users/wayne/Desktop/hello/.lift/checkstyle-lift.jar", runs Checkstyle properly, and saves it to checkstyle-idea.xml as "$PROJECT_DIR$/.lift/checkstyle-lift.jar". Everything as expected so far. However, when I edit the Checkstyle-IDEA preferences, save, and go back, it changes the display in the Third-Party Checks box to "$PROJECT_DIR$/.lift/checkstyle-lift.jar" and can no longer find the third-party check when running Checkstyle. The checkstyle-idea.xml file still stores it as "$PROJECT_DIR$/.lift/checkstyle-lift.jar". Perhaps $PROJECT_DIR$ is not getting properly re-expanded in one place.

**Comment by jshiell** [comment]
Thanks for the kind words, and the testing! That's a good spot - I'm embarrassed to say I didn't even think to check that. There was indeed a path missed - now, I hope, [fixed in this new build](https://www.dropbox.com/s/leuzxu8ppql2cki/CheckStyle-IDEA-5.21.1-1.zip?dl=0).

**Comment by jshiell** [comment]
Smashing - I'll release it to the world. Thanks very much for your help!
