### ISSUE TITLE
Remove notification on update

### ISSUE THREAD

**Issue by grimreaper** [jshiell/checkstyle-idea#407]
Few, if any, other extensions have this misfeature. It takes attention from whatever work one is planning to do. The information is also fully available in the plugin information screen if one wants to look.

**Comment by jshiell** [comment]
Maybe you should consider not being passive aggressive if you want me to consider your request.

**Comment by grimreaper** [comment]
> Maybe you should consider not being passive aggressive if you want me to consider your request.

I did not intend to be aggressive (passively or not).  I filed this since it is annoying to have a pop-up every time this plugin decides to update.

**Comment by grimreaper** [comment]
I had actually looked at implementing at this as an option for those who wanted it. It turned out that the options panel is per-project which defeats the point.

The passive-aggressive approach would have been submitting a PR that just removed the code ;)

**Comment by jshiell** [comment]
Fair enough. Describing something as a misfeature is probably not a good opener though, as it is used elsewhere (e.g. the bash support plugin), and its implementation was in response to requests for more information about releases (and, indeed for this particular approach). 

On a practical answer, have you considered disabling popups for the plugin via the event log settings? It's a bit wider, but there aren't really any other popups that don't refer to error conditions, from memory. 

As you say, settings are hard without implementing another IDE wide preferences panel.

> The passive-aggressive approach would have been submitting a PR that just removed the code ;)

Hah. I'll give you that 😂

**Comment by grimreaper** [comment]
> have you considered disabling popups for the plugin via the event log settings? 
Just found that setting and will try it.  Thanks!
