### ISSUE TITLE
Inspection highlighting for errors vs. warnings

### ISSUE THREAD

**Issue by kevin-wayne** [jshiell/checkstyle-idea#411]
Checkstyle checks labeled as "warning" in the Checkstyle xml config file are annotated with a yellow underwaved squiggle, consistent with the Checkstyle real-time scan settings in "Inspections", which, for me, are set to "Preferences -> Color Scheme -> General -> Errors and Warnings -> Warning" (see screenshot below). This is exactly what I would expect.

However, Checkstyle checks labeled as "error" in the Checkstyle xml config file are annotated using the "Errors and Warnings -> Unknown Symbol" style (for me, red text, square border). This is unexpected.

 I think either all Checkstyle Errors and Warnings should get mapped to whatever style is selected in "Preferences -> Editor -> Inspections -> Checkstyle -> Checkstyle real-time scan -> Severity". Alternatively, Errors could get mapped to "Errors and Warnings -> Errors" and Warnings could get mapped to "Errors and Warnings -> Warnings".

<img width="753" alt="screen shot 2018-09-17 at 6 07 27 am" src="https://user-images.githubusercontent.com/5225666/45617688-1a332480-ba41-11e8-8f58-e9bea0e12f7a.png">

<img width="1333" alt="screen shot 2018-09-17 at 6 02 41 am" src="https://user-images.githubusercontent.com/5225666/45617693-1d2e1500-ba41-11e8-97fd-fe480ee1c5e7.png">

**Comment by jshiell** [comment]
Thanks for the report. This area is a bit hairly - the plugin is about twelve years old now, and hence has seen a lot of IDEA API change. I imagine it's just slowly drifted from the appropriate constants - I'll add it to the todo list for when I get a moment.

**Comment by kevin-wayne** [comment]
Great, thanks!
