### ISSUE TITLE
Checkstyle always shows a balloon on new project opened

### ISSUE THREAD

**Issue by Vampire** [jshiell/checkstyle-idea#415]
Since some time always when I open a new project with IJ and your plugin enabled, it always shows a balloon notification that Checkstyle was updated.
This does not make much sense, does it?
Please only show this for a project where Checkstyle actually was used before and this notification might actually be interesting.

**Comment by jshiell** [comment]
Thanks for the suggestion. This seems sensible - not sure why I didn't put the flag in app-level config to begin with, unless there was a good reason that I've since forgotten.

**Comment by jshiell** [comment]
Will be in the next release, hopefully this weekend.
