### ISSUE TITLE
Checkstyle plugin does not find classpath resource

### ISSUE THREAD

**Issue by AndyGee** [jshiell/checkstyle-idea#416]
1. Create and deploy a checkstyle artifact that contains a simple "src/main/resources/checkstyle.xml" resource as per: https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/multi-module-config.html
2. Add the artifact to the plugin configuration
3. Install the checkstyle plugin in Intellij
4. Configure the the plugin Settings/Other Settings to point to the plugin classpath: Use a Checkstyle file assesible via the plugin classpath

What is the expected result?

The plugin finds the classpath file.

What happens instead?

Error: Couldn't read classpath resource: checkstyle.xml

2018-12-11 15:48:04,724 [19046213]   INFO - ClasspathConfigurationLocation - Couldn't read file from classpath: checkstyle.xml 
java.io.FileNotFoundException: Couldn't read classpath resource: checkstyle.xml
 at org.infernus.idea.checkstyle.model.ClasspathConfigurationLocation.asBytes(ClasspathConfigurationLocation.java:47)
 at org.infernus.idea.checkstyle.model.ClasspathConfigurationLocation.resolveFile(ClasspathConfigurationLocation.java:32)
 at org.infernus.idea.checkstyle.model.ConfigurationLocation.resolve(Configurati
onLocation.java:190)
 at org.infernus.idea.checkstyle.ui.LocationDialogue$NextAction.actionPerformed(LocationDialogue.java:250)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 ...
![image](https://user-images.githubusercontent.com/2536412/49850578-5676e680-fdde-11e8-915e-c7bfdea44475.png)

**Comment by rupert654** [comment]
I think that "plugin classpath" is misleading if you are also using the Maven Checkstyle plugin.

Here "plugin classpath" means the classpath of the IntelliJ Checkstyle plugin. You are supposed to add the jar into the "Third Party Checks" at the bottom of the IntelliJ Checkstyle plugins config window.

Then reference the specific location of the file within the jar, relative to the classpath.

Loading checkstyle from the Maven classpath is a different matter and is requested in #107.

**Comment by jshiell** [comment]
Sorry for the delay in the reply - I've been on holiday for the past few weeks.

Thanks very much to @rupert654 for the diagnosis - there is indeed no integration with the Maven/Gradle/etc Checkstyle plugins, and the configuration for the IDEA stands alone. As mentioned in #107 there's unlikely to be any added, as it would require custom code to be maintain for every integration.
