### ISSUE TITLE
checkstyle.xml locked by IDEA process

### ISSUE THREAD

**Issue by Vampire** [jshiell/checkstyle-idea#417]
I often have the problem on Windows that I cannot switch branches in Git as the IDEA process has a lock on the `checkstyle.xml` file.
I don't think there is any need to keep the file open, so please make sure the file handle is not leaked after you need it.

**Comment by jshiell** [comment]
Thanks for the report.

This is odd, as we shouldn't hold the hold on the file (we never need it more than momentarily), and we should give Checkstyle a stream to work with. The only thing I can think of off-hand is that Checkstyle isn't surrendering the steam, which we could potentially work around by reading it into memory before handing over the pointer. Certainly there's problems where Checkstyle holds onto the JAR files, which I know can cause these sort of issues on Windows. But the XML itself is a new one. I'll try have a butchers in the not too distant.

**Comment by jshiell** [comment]
I've changed the file/HTTP/classpath endpoints to read the config to a buffer before caching it/passing it to Checkstyle - I hope this should break the link but it's all guesswork tbh as I don't use Windows, and OSX/Linux are not nearly so anal on file locking as Windows is. Do please feel free to reopen if the problem continues after the next release.
