### ISSUE TITLE
Support checkstyle 8.16

### ISSUE THREAD

**Issue by nborodovskiy** [jshiell/checkstyle-idea#420]
Checkstyle 8.16 is currently available: http://checkstyle.sourceforge.net/releasenotes.html

**Comment by jshiell** [comment]
Thanks for the reminder. I've a bit of a backlog of tasks after a long holiday over December, so I'll try and get this released this weekend.

**Comment by jshiell** [comment]
Will be in the next release, hopefully this weekend.

**Comment by nborodovskiy** [comment]
Thank you!
