### ISSUE TITLE
Use a Checkstyle file accessible via HTTP

### ISSUE THREAD

**Issue by xiaobei2019** [jshiell/checkstyle-idea#426]
Another question to ask is how often do I synchronize checkstyle configuration files via http？

**Comment by xiaobei2019** [comment]
Thank you for the answer:From memory we cache for ~30s.
I want to know more about how often synchronization between http file servers and memory occurs.

**Comment by jshiell** [comment]
https://github.com/jshiell/checkstyle-idea/blob/master/src/main/java/org/infernus/idea/checkstyle/checker/CheckerFactoryCache.java

Checkers are cached for 30s.

https://github.com/jshiell/checkstyle-idea/blob/master/src/main/java/org/infernus/idea/checkstyle/model/HTTPURLConfigurationLocation.java

HTTP reads are cached for 2s.

Hence you'd expect a maximum lag of ~32s, assuming constant scans.
