### ISSUE TITLE
Give a way to sepciy configProperties

### ISSUE THREAD

**Issue by vbence** [jshiell/checkstyle-idea#427]
The recommended way to use header checks is the following:
build.gradle
```
    configProperties 'checkstyle.header.file': 'license-header-java.regexp';
```
checks.xml
```
    <module name="RegexpHeader">
        <property name="headerFile" value="${checkstyle.header.file}"/>
        <property name="fileExtensions" value="java"/>
    </module>
```
... I realize there is no gradle Integration in the plugin's scope, but a UI element where we can manually specify `configProperties` would be great!

**Comment by jshiell** [comment]
When you add the file in the plugin configuration you should be given the chance to set any properties in the Checkstyle file via a table. Are you not seeing this, or am I misunderstanding your suggestion?

**Comment by vbence** [comment]
Thanks, It works perfectly. I edited the file (originally this section was commented out) so I wasn't prompted at import-time.

In this case can we have a button to re-open the property editor dialog?

**Comment by jshiell** [comment]
Working from memory as I don't have the plugin installed here, but I'm pretty sure you do - the edit button in the rule files table should pop up the properties box (we currently don't support editing file location or name, though).

**Comment by vbence** [comment]
It does indeed, thanks for your help!

**Comment by jshiell** [comment]
My pleasure 🙂
