### ISSUE TITLE
How to set global custom rules?

### ISSUE THREAD

**Issue by zenglian** [jshiell/checkstyle-idea#429]
I create a custom rules in one project, but it does not appear in another project. How to set it gloallby?

**Comment by jshiell** [comment]
All settings are project-specific. However, you may be able to set it in the project defaults, in order to have it set up in new projects.

**Comment by zenglian** [comment]
I think it makes sense to remember the settings across projects, to save the time to re-configure it.

**Comment by jshiell** [comment]
It may it some cases; in others, for instance where projects have wildly different Checkstyle settings, it may not. In any case I've no plans to add support for this at present.
