### ISSUE TITLE
White backgrounds on CheckStyle tab when using Darcula colour scheme (2018.3.5 Intellij)

### ISSUE THREAD

**Issue by embee1981** [jshiell/checkstyle-idea#432]
I've just updated to 2018.3.5 of intellij and the checkstyle panel seems to have some funkiness about it
![checkstyle](https://user-images.githubusercontent.com/13723136/53458722-1ca59b80-3a2f-11e9-9379-90299094d6f2.png)

Toggling to the white theme then back to Darcula resolves for the session but when you restart Intellij, you get the same affect as before in the screenshot :(

**Comment by jshiell** [comment]
Thanks for the report. I'm travelling this week, so will try and have a look this weekend.

What platform is this on?

**Comment by embee1981** [comment]
I'm on Windows 10, v 1809, build 17763.316
2019.1 EAP also has the same issue
Everything else is behaving like general display and the settings panel

**Comment by embee1981** [comment]
I've put up a pull request for this, some Swing jiggery pokery :-)

**Comment by jshiell** [comment]
You're a legend :-) Thanks - I don't use Windows, so I was already trying to work out how to reproduce this if it behaved differently on OS X 😄 I'll try get that merged tonight!

**Comment by jshiell** [comment]
Released in 5.24.3 - thank you for doing all the hard work!
