### ISSUE TITLE
Checkstyle plugin causes high CPU usage and locks IntelliJ

### ISSUE THREAD

**Issue by jack-cole** [jshiell/checkstyle-idea#441]
When using the Checkstyle plugin, sometimes IntelliJ's CPU usage will spike up and remain at high usage until it is closed.

I have narrowed it down to the Checkstyle plugin based on the problems below, but I do not know exactly how it is triggered.
* Trying to scan a single file just says "A scan is in progress" indefinitely
* Going into Checkstyle settings causes the program to lock, where the settings window is stuck and I am unable to interact with IntelliJ anymore. The settings area for Checkstyle is completely blank.
* I cannot close the project, I must force quit  IntelliJ if I wish to stop it

Force closing IntelliJ fixes the issue. When I start it back up everything works fine.

System Information:
CheckStyle-IDEA v5.25.0
IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4
MacBook Pro (Retina, 13-inch, Mid 2014)

**Comment by jshiell** [comment]
Thanks for the report. That sounds nasty, and from your description it does sounds like it's getting stuck waiting for the scan locks.

You're the first person to report this, so I do wonder if there's something in your rules file or usage pattern which is triggering this bug. Could you please attach your rules file and describe anything about your project which you think might be out of the ordinary, e.g. is it a very large project? Do you usually have multiple projects open at the same time? Are some of the files unusually large? Is the project on a network drive? Anything that might give me hints as to where the edge case lies.

Alternately, if you're able to get a thread dump of the IDE when it's in this state then that might be a better option, as hopefully it'll show exactly what's tied up.

**Comment by spartan-jack** [comment]
Update: This might not be due to your program, but checkstyle. I ran into the exact same issue with gradle stuck on checkstyle.

What's even weirder is running checkstyle on its own in command line can analyze the contents fine. No hanging.

Fixing the errors stopped the hanging in gradle and the checkstyle plugin. I found the exact line of code that when fixed, stops the hanging. I am working on reproducing the bug with a sanitized version of the file, since it's proprietary.

**Comment by jshiell** [comment]
Nice work - that's very interesting indeed because - as you can probably guess from the lack of updates here - I've made no progress in producing similar problems.

I'd appreciate a link to the bug report when you do have a use-case, as I'd love to see what I missed!

**Comment by jack-cole** [comment]
Here you go. Just put the Field.java file in IntelliJ, create a checkstyle config using sun_checks.xml, with suppressions.xml as the suppressFile parameter, and then do a scan on the file in IntelliJ.

[checkstyle_issue.zip](https://github.com/jshiell/checkstyle-idea/files/3507466/checkstyle_issue.zip)

**Comment by jack-cole** [comment]
I was able to reproduce in the console without your plugin, so you probably don't need to worry about it. https://github.com/checkstyle/checkstyle/issues/6987

**Comment by jshiell** [comment]
Thanks very much for the update, and good luck!
