### ISSUE TITLE
Run Checkstyle for changed files

### ISSUE THREAD

**Issue by crlikcngroup** [jshiell/checkstyle-idea#442]
It would be a real time saver if you had an option to only check files that were modified since last commit or something like that.

There is an option to run Checkstyle for whole module or project but sometimes with a lot of modules and changes scattered between them, checking every file individually takes too much time. And running it for whole project may report many issues that can't be fixed right now in our projects.

**Comment by jshiell** [comment]
There's a `Scan with Checkstyle` option in the `Before Commit` section of the commit dialogue; there are also buttons for `Check All Modified Files` and `Check Files in the Current Change List` (just below the `Scan Project` button) in the plugin tool-window. Unless I'm misunderstanding your request, I believe these should cover this particular case. Please feel free to re-open if I've missed something.
