### ISSUE TITLE
Add  8.21 version to plugin

### ISSUE THREAD

**Issue by Anron97** [jshiell/checkstyle-idea#446]
Hi. Could you please add 8.21 version to plugin?

**Comment by jshiell** [comment]
Released in 5.28.0.

**Comment by tsjensen** [comment]
Hi @jshiell I think you typed "8.20" in the [release note](https://github.com/jshiell/checkstyle-idea/releases/tag/5.28.0) ... 😉

**Comment by jshiell** [comment]
🤦‍♂ 

Thanks 👍
