### ISSUE TITLE
Gradle command seems wrong

### ISSUE THREAD

**Issue by erinyees** [jshiell/checkstyle-idea#451]
### AS-IS :
I followed and type command of Development in README.md.
**./gradlew runIdea**

> To run it in a sandboxed IDEA, run:
```
./gradlew runIdea
```

but it returns below result.
> $ ./gradlew runIdea
>
> FAILURE: Build failed with an exception.
>
> * What went wrong:
> Task 'runIdea' not found in root project 'checkstyle-idea'. Some candidates are: 'idea', 'openIdea', 'runIde'.
>
> * Try:
> Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
>
> * Get more help at https://help.gradle.org
>
> BUILD FAILED in 1s

and I typed other command in the result.
**./gradlew runIde** 

finally IntelliJ started!

**Comment by jshiell** [comment]
It looks like the [gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin) has dropped the `runIdea` command in favour of `runIde` - I've updated the `README.md`.

Thanks very much for letting me know!
