### ISSUE TITLE
invalid thirdPartyPackageRegExp pattern conversion

### ISSUE THREAD

**Issue by ffmammadov** [jshiell/checkstyle-idea#452]
Hi, I tried to use `customImportOrderRules` property as below:

```xml
<property name="customImportOrderRules"
             value="SPECIAL_IMPORTS###THIRD_PARTY_PACKAGE###STANDARD_JAVA_PACKAGE###STATIC"/>
```

but for some reason, when I try to import my `checkstyle.xml` to IDEA, `.*` (`thirdPartyPackageRegExp` value) converts to `<emptyLine />` as below:

```xml

    <option name="IMPORT_LAYOUT_TABLE">
      <value>
        <package name="my.company" withSubpackages="true" static="false" />
        <emptyLine />
        <emptyLine />
        <package name="javax" withSubpackages="true" static="false" />
        <package name="java" withSubpackages="true" static="false" />
        <emptyLine />
        <package name="" withSubpackages="true" static="true" />
        <emptyLine />
        <package name="" withSubpackages="true" static="false" />
      </value>
    </option>
```
and because of this, autoformat breaks the code.

**Comment by jshiell** [comment]
Thanks for the report. I'll try have a look, but no promises as this was contributed code and I have no great insights into how the import works. But 🤞

**Comment by jshiell** [comment]
Dup of https://github.com/jshiell/checkstyle-idea/issues/500 I believe.

Shockingly, surprising even myself, this is hopefully now fixed in the latest release🤞
