### ISSUE TITLE
Cannot load checkstyle file

### ISSUE THREAD

**Issue by amanteaux** [jshiell/checkstyle-idea#453]
Hello, I have the same issue as described in #312 : `org.infernus.idea.checkstyle.exception.CheckStylePluginException: <html><b>The Checkstyle rules file could not be parsed.</b><br>cannot initialize module LineLength - Property 'fileExtensions' in module LineLength does not exist, please check the documentation<br>The file has been blacklisted for 60s.</html>`

However, I have an up to date version of the plugin:
![image](https://user-images.githubusercontent.com/3846854/63857357-d90ef880-c9a3-11e9-971d-3142afb183bd.png)

I am choosing the 8.16 checkstyle version:
![image](https://user-images.githubusercontent.com/3846854/63857256-a9f88700-c9a3-11e9-90ca-68a20b7c3727.png)

I am using the Google checks file available at https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml

Is there a bug with the plugin or am I doing something wrong?
Thank you!

**Comment by tsjensen** [comment]
You XML file is too new (latest unreleased Checkstyle). Do not download the Google checks XML, instead check them in the list shown in your screenshot (put a checkmark next to "Google Checks").

If you really *must* download, then use the matching version of the config, e.g.
https://raw.githubusercontent.com/checkstyle/checkstyle/checkstyle-8.16/src/main/resources/google_checks.xml

**Comment by amanteaux** [comment]
Thank you! Downloading the right checkstyle file version did the trick.

Actually I wanted to change the default Google indentation length from 2 spaces to 4 :)
