### ISSUE TITLE
Manifest order warning: uses-permission tag appears after application tag

### ISSUE THREAD

**Issue by DevDengChao** [jshiell/checkstyle-idea#455]
See issue https://github.com/checkstyle/checkstyle/issues/7079

**Comment by jshiell** [comment]
Is this with the style importer? If so, this is unlikely to be fixed tbh. That was contributed code; the contributor hasn't shown much interested in maintaining it. I've no interest in the feature myself. Sorry.

**Comment by jshiell** [comment]
As far as I can see our importer only affects the Java style, not XML, and we don't intercept reformatting for XML at all. So I don't see how this could be related to the plugin in any way.
