### ISSUE TITLE
Not allowed as a parent of LineLength

### ISSUE THREAD

**Issue by hello-zhengzq** [jshiell/checkstyle-idea#458]
I used idea plugins v5.33.1，checkstyle version v8.25，when i imported my style file，message showed “TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard.“，not support LineLength ？did anyone have this problem？

**Comment by hello-zhengzq** [comment]
file contents like：
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
  <property name="severity" value="warning"/>
  <property name="charset" value="UTF-8"/>
  <property name="fileExtensions" value="java, properties, xml"/>
  <module name="TreeWalker">
    <module name="LineLength">
      <property name="ignorePattern" value="^package.*|^import.*|a href|href|http://|https://|ftp://"/>
      <property name="max" value="100"/>
    </module>
  </module>
  <module name="FileTabCharacter">
    <property name="eachLine" value="true"/>
  </module>
</module>
```

**Comment by tsjensen** [comment]
When it says "Please review 'Parent Module' section for this Check in web documentation", it wants you to look at this: https://checkstyle.org/config_sizes.html#LineLength  
The "Parent Module" section simply says:
> Checker

This means that you must put your `LineLength` module directly under `Checker`, not down under `TreeWalker`.

Maybe the error message should be clearer about this? Then you can [raise an issue](https://github.com/checkstyle/checkstyle/issues) at Checkstyle directly. The Checkstyle-IDEA plugin only displays Checkstyle's error messages.

**Comment by hello-zhengzq** [comment]
> 
> 
> When it says "Please review 'Parent Module' section for this Check in web documentation", it wants you to look at this: https://checkstyle.org/config_sizes.html#LineLength
> The "Parent Module" section simply says:
> 
> > Checker
> 
> This means that you must put your `LineLength` module directly under `Checker`, not down under `TreeWalker`.
> 
> Maybe the error message should be clearer about this? Then you can [raise an issue](https://github.com/checkstyle/checkstyle/issues) at Checkstyle directly. The Checkstyle-IDEA plugin only displays Checkstyle's error messages.

Thx，i found the issue about LineLength at checkstyle.
The error message is clearer enough, seems many templates on the website show that the LineLength under `TreeWalker`, hah....QAQ

**Comment by jshiell** [comment]
Closing as solved, thanks @tsjensen
