### ISSUE TITLE
"Reload Rules files" broken

### ISSUE THREAD

**Issue by fishbone1** [jshiell/checkstyle-idea#459]
The "Reload Rules files" in the CheckStyle window doesn't work for me. I configured a local checkstyle.xml and it works most of the time, but changes are not reckognized by the plugin immediately and I cannot tell, when they are detected. As I make lots of edits in the rules file at the moment, I was happy when I found the "Reload Rules files"-button. Unfortunately, pressing it seems to have zero effect. It looks like the file is cached somehow. It's very annoying if you have an error in the file, because it's blacklisted for 60s. Although i fixed the error, the file is blacklisted again... (BTW it would be nice if you could change the timeout value of 60s, but that's a different story)

IntelliJ version: IntelliJ IDEA 2019.2.3 (Ultimate Edition) Build #IU-192.6817.14, built on September 24, 2019
CheckStyle-IDEA version: 5.33.1
CheckStyle version: 8.25

**Comment by jshiell** [comment]
Thanks for the report. The file is indeed cached, as setup is expensive. The reload button should just clear the cache, but it sounds like it’s being naughty.

I’ll try have a look ASAP, but it’s unlikely to be this weekend given the lay of the land at present.

**Comment by jshiell** [comment]
I fear I've had no luck in reproducing this - I can happily break the rules file, and continue to scan until the cache time expires or I hit the reload button. Once I hit reload, it breaks on the next scan as expected. Likewise, I can continue to try and scan and watch the blacklist count down, but once I fix the file and hit reload it correctly parses the file again and scanning starts to work.

What I have done it rework the cache logic - it was written a long, long time again, when I was young and [more] reckless - it's now a lot simpler, and also ensures checkers aren't invalidated until after they've been dropped from the cache. I don't know if it'll have any effect, but it's in today's release.

If you've any hints on where our test cases might be diverging, or if today's release does change behaviour, please let me know.

Also, what would you suggest for the blacklist timeout? 60s is pretty arbitrary, and built around it's original implementation to stop people being spammed on setup errors. As such the use case was generally that their network was broken, or the file had been renamed, and 60s was a good value to allow time to fix it. Obviously you don't fit that bucket, but I'm not wedded to the value, and if we can find a workable compromise I'm open to changing it.

**Comment by fishbone1** [comment]
Hmm... Maybe it's because of the long time needed to process the rules file? So after clicking the reload button it takes minutes until it is actually reloaded and the cache is used until the processing is finished?

I changed the LeftCurly option from "eol" to "nl". Then I switched to a Java source file and clicked the reload-button and after that, multiple times the "check current file" (green triangle) in the CheckStyle-pane => The "check current file" worked about a minute later.

But then I changed the LeftCurly option back to "eol". It took about 15 minutes (!), until this change was respected for the single file check. Important: I did not click the reload button again.

Another interesting thing I noticed: I tried to add a new (minimalistic) checkstyle rules file. Your plugin didn't accept it and stated it has errors. It took me about 10 times until it worked, although I copied all the content from my other file which works. So again - it looks like the plugin reads cached content rather than the actual content. Could it be a problem with the IntelliJ plugin API delivering wrong content?

Unfortunately the plugin update today didn't change this behavior.

About the 60s blacklist timeout: Well, during setting up a complete new rules-file, there are a lot changes. So it's very common that there are errors: Most of time I guessed a wrong value or I have copy/paste errors from the docs. So everytime there is a syntax problem, I have to wait for 60 seconds. Then I fix it and missed another error - I have to wait for 60 seconds again. So I thought it would be useful if a user could change this timeout in the settings panel. I'd change it to 10 seconds in this situation, I guess. But it's not really problem as long as the "reload"-button works...

**Comment by jshiell** [comment]
> But then I changed the LeftCurly option back to "eol". It took about 15 minutes (!), until this change was respected for the single file check. Important: I did not click the reload button again.

There's something very odd going on here, as the timeout should be max 60s. Unless there's a FS sync problem, but that seems extremely unlikely unless your setup is very weird. 

It should be anything to do with the Plugin API AFAIK - we read the files directly from the FS via the standard Java IO. We do some simple tricks to try and reduce file locking on Windows, mostly around buffering files in memory rather than passing the file stream about, but these shouldn't be held on to for long.

So two questions to help me as I look at this code - what OS are you on?; and how are you loading the file (I presume directly from the filesystem, but best to double-check)?

**Comment by LEQADA** [comment]
@jshiell I have the same problem.
OS: Ubuntu 18.04
Loading using CheckStyle settings in Intellij from the file system.

**Comment by donalmurtagh** [comment]
From the POV of usability it would be helpful if there was some kind of notification when the reloading has finished

**Comment by jshiell** [comment]
The reload should be instant. The fact that it's not for a lot of people is a bug; just one I haven't managed to reproduce or otherwise diagnose.

**Comment by JD-CSTx** [comment]
I had the problem for a long time, still under Windows 10 64 Bit 21H2, IntelliJ 2021.3.2 Ultimate Edition, CheckStyle Plugin 5.61.1.

**Comment by ahus1** [comment]
I stumbled across this issue and it seems that pressing "save" in the modified file helps before triggering "Reload Rules files". I created PR #562 for this. Maybe someone could comment if this helps them as well.
