### ISSUE TITLE
IntelliJ freezes, Checkstyle in Thread Dump

### ISSUE THREAD

**Issue by ahus1** [jshiell/checkstyle-idea#462]
I've running Checkstyle and was trying to commit some code. The IDE froze, and I took the following thread dump. I had two diff views open at the time. 

The dialog showed "Performing Code Analyse..." but didn't move for minutes. No process visible in two consecutive stack traces. I had to kill the VM.

I'm suspecting Checkstyle to be involved, therefore I open the issue in this GitHub repo: 

```
	at org.infernus.idea.checkstyle.checker.ScannableFile.createAndValidate(ScannableFile.java:77)
	at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:87)
	at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$0(CheckStyleInspection.java:63)
	at org.infernus.idea.checkstyle.CheckStyleInspection$$Lambda$5202/0x00000001027fec40.call(Unknown Source)
```

[stacktrace2.txt](https://github.com/jshiell/checkstyle-idea/files/3935051/stacktrace2.txt)
[stacktrace1.txt](https://github.com/jshiell/checkstyle-idea/files/3935052/stacktrace1.txt)

IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 27, 2019
Licensed to Alexander Schwartz
You have a perpetual fallback license for this version
Subscription is active until December 13, 2020
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: 
Non-Bundled Plugins: Batch Scripts Support, CheckStyle-IDEA, Error-prone plugin, EclipseCodeFormatter, FindBugs-IDEA, Lombook Plugin, PlantUML integration, YourKit Java Profiler 2017.02-b75 Integration, com.dubreuia, com.github.tinselspoon.intellij.kubernetes, mobi.hsz.idea.gitignore, tanvd.grazi, org.asciidoctor.intellij.asciidoc, org.jetbrains.plugins.vue

**Comment by jshiell** [comment]
Thanks for the excellent report and apologies for the delayed response.

Unfortunately, I don't think it's likely - although it's certainly possible - that this plugin is the cause of this. The referenced line is calling into the IDEA application class and asking to run a read action. 
```
return ApplicationManager.getApplication().runReadAction(action);
```
Looking at both stack traces, that read action appears to be waiting for the lock:
```
	at jdk.internal.misc.Unsafe.park(java.base@11.0.4/Native Method)
	- parking to wait for  <0x00000000aeb05498> (a com.intellij.openapi.application.impl.ReadMostlyRWLock)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.4/LockSupport.java:234)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.waitABit(ReadMostlyRWLock.java:133)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.readLock(ReadMostlyRWLock.java:124)
	at com.intellij.openapi.application.impl.ApplicationImpl.startRead(ApplicationImpl.java:833)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:809)
	at org.infernus.idea.checkstyle.checker.ScannableFile.createAndValidate(ScannableFile.java:77)
```
Another of our threads is waiting on the result on that read action:
```
"Performing Code Analysis..." #1525 daemon prio=4 os_prio=-1 cpu=2343.75ms elapsed=242.41s tid=0x0000000033714800 nid=0x1a254 waiting on condition  [0x000000007135d000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(java.base@11.0.4/Native Method)
	at org.infernus.idea.checkstyle.util.Async.waitFor(Async.java:41)
	at org.infernus.idea.checkstyle.util.Async.whenFinished(Async.java:34)
	at org.infernus.idea.checkstyle.util.Async.asyncResultOf(Async.java:20)
	at org.infernus.idea.checkstyle.CheckStyleInspection.checkFile(CheckStyleInspection.java:63)
```

The diff viewer is also waiting on the read lock:
```
"AWT-EventQueue-0" #24 prio=6 os_prio=0 cpu=546296.88ms elapsed=12666.06s tid=0x000000001c8f2000 nid=0x1cd70 waiting on condition  [0x000000001fbbc000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.4/Native Method)
	- parking to wait for  <0x00000000aeb05498> (a com.intellij.openapi.application.impl.ReadMostlyRWLock)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.4/LockSupport.java:234)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.writeLock(ReadMostlyRWLock.java:219)
```

So my guess is that something else has that locked for write access, and hence those two threads are blocked on the lock release. As to what, though, I'm uncertain - the lock address isn't referenced elsewhere in the stack trace.

**Comment by ahus1** [comment]
I digged a bit into the stack trace came up with a theory of a dead lock situation. 

Assumtions: 

1. ApplicationImpl has a RW-lock: Multiple threads are allowed have a read lock, but only can have a write lock. Someone who wants to get a write lock must wait until all other threads with a read lock finished.
2. While a thread waits for a write lock, no other thread can enter with a read lock

This could map to the situation in the stack trace:

* Thread 1525 holds a read lock as it successfully passed through ApplicationImpl.runReadAction. It waits for Async.asyncResultOf() - that would be thread #1523?
* Thread 24 waits to acquire a write lock - so no thread is allowed to get a read lock now
* Thread 1523 waits to acquire a read lock to continue with ScannableFile.createAndValidate(), but can't as 24 is waiting for a write lock

What do you think?

**Comment by jshiell** [comment]
Nice - I like your thinking. I can't fault it - the IDEA docs, such as they are, don't guarantee read action behaviour when a write action is pending (indeed, they don't acknowledge it at all). And while the IDE locks used to be pretty chunky, they've been aggressive recently in making them more fine-grained.

It does leave us in a sticky situation though - the scan runs on a background thread to avoid UI lockup, yet IDEA is the requestor for a read-lock on the inspection invocation, so we can't avoid the `Async` call being requested within a read-action.

The read submit doesn't let us specify a timeout, so we could modify the `Async` wait so it has a maximum limit. The inspection should only scan a single file at a time, so it shouldn't ever run for unreasonable times. 

The other option is to drop the run on the background thread - if the IDE is going to hold a lock for the duration in any case, perhaps it's better just to suck it up and get it done as fast as possible. I'll need to do some testing to see what this does to UI responsiveness in modern IDEA versions, though.

**Comment by jshiell** [comment]
So here's option two - obviously my testing hasn't been deep, but it seems fine so far. The proviso is that I'm using a fairly beefy workstation, and a fairly small project.

If you have a chance, could you please give it a spin? 

https://www.dropbox.com/s/mww48au3dihvye0/CheckStyle-IDEA-5.35.1.zip?dl=0

**Comment by ahus1** [comment]
Thank you for the quick first version. I gave it a test run on a project. I've triggered some code change and also a full scan of the project. 

That triggered an exception in the event log. I can't tell if the exception occured during manual scan or during editing.

It's still the same IntelliJ version as above. Digging into the IntelliJ code this leads to the following comment in ReadMostlyRWLock.java: 

```
  /**
   * Executes a {@code runnable} in an "impatient" mode.
   * In this mode any attempt to grab read lock
   * will fail (i.e. throw {@link ApplicationUtil.CannotRunReadActionException})
   * if there is a pending write lock request.
   */
```

The Exception:

The scan failed due to an exception: Error executing command 'OpScan': null Root cause: null com.intellij.openapi.application.ex.ApplicationUtil$CannotRunReadActionException   at com.intellij.openapi.application.ex.ApplicationUtil$CannotRunReadActionException.create(ApplicationUtil.java:94)   at com.intellij.openapi.application.impl.ReadMostlyRWLock.throwIfImpatient(ReadMostlyRWLock.java:147)   at com.intellij.openapi.application.impl.ReadMostlyRWLock.checkReadLockedByThisThreadAndNoPendingWrites(ReadMostlyRWLock.java:106)   at com.intellij.openapi.application.impl.ApplicationImpl.checkReadAccessAllowedAndNoPendingWrites(ApplicationImpl.java:941)   at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:790)   at org.infernus.idea.checkstyle.service.CheckStyleAuditListener.auditFinished(CheckStyleAuditListener.java:66)   at com.puppycrawl.tools.checkstyle.Checker.fireAuditFinished(Checker.java:262)   at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:223)   at org.infernus.idea.checkstyle.service.cmd.OpScan.processAndAudit(OpScan.java:76)   at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:52)   at org.infernus.idea.checkstyle.service.cmd.OpScan.execute(OpScan.java:22)   at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)   at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.scan(CheckstyleActionsImpl.java:76)   at org.infernus.idea.checkstyle.checker.CheckStyleChecker.scan(CheckStyleChecker.java:43)   at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$inspectFile$0(CheckStyleInspection.java:90)   at java.base/java.util.Optional.map(Optional.java:265)   at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:90)   at org.infernus.idea.checkstyle.CheckStyleInspection.checkFile(CheckStyleInspection.java:62)   at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:144)   at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:520)   at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:77)   at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:332)   at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:167)   at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:125)   at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:114)   at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:109)   at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$7(LocalInspectionsPass.java:331)   at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:148)   at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:227)   at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:155)   at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:227)   at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:155)   at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:227)   at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:155)   at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:227)   at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:155)   at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)   at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)   at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)   at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)   at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)   at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)   at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)   at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)   at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)   at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)   at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)   at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)   at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by jshiell** [comment]
Well that's just embarrassing 🤦‍♂ Curiously this should only have changed the code for the inspection, not the full-scan. Apologies, I'm obviously going to have to give this a proper bash, and I fear I'm out of time for tonight. I'll try get a better effort together next week. Thanks for trying it though, much appreciated!

**Comment by muntyan** [comment]
I am not sure if my problem is the same, I have intellij randomly (totally randomly, even sometimes when I don't do anything at all) eat up to 100% CPU, and activity monitor shows that it's checkstyle plugin. I got an intellij cpu dump and submitted a bug to JetBrains, and they also said it's checkstyle: https://youtrack.jetbrains.com/issue/IDEA-229839. Is there anything I can do to help diagnose this? Should I open another bug?

**Comment by jshiell** [comment]
@muntyan thanks for the report - it could well be this problem, so I'd suggest waiting to see if this fixes it before raising another bug. 🤞 

@ahus1 irritatingly, the SDK we build again (2018) appears to have a version different `ApplicationImpl` to 2019.3 (there's no `checkReadAccessAllowedAndNoPendingWrites` method, for a start). Looking at the code for 2019, it seems it now have a `impatient` check, where it can refuse the read action if there's a write pending. The old behaviour was that if you have a read action lock and you attempt to do another read action it would just short-circuit and run it in the same thread - which meant we could leave the calls there as the read-action lock isn't in place unless we are running as an inspection. This change means that any such call could be aborted, despite us already having a read-lock. Hence the exception.

So, three options I guess. Either we need to grab a read-lock for the entirety of the static scan - which seems wasteful and less-than-great for responsiveness; we need to handle aborts during the inspection and abort the inspection - which, tbh, seems a good idea; and/or we need to avoid calling runReadAction if we already have a read-action, which means branches in the shared code (well, a wrapper function, anyway). I think the 2nd option is a good place to start, and the 3rd is a good place to go afterwards. Plus the 2nd option should be quick enough to get a prototype together, as I think we can agree that IDE lockups are pretty high priority to fix.

**Comment by jshiell** [comment]
Right, try #2 - hopefully it'll last a bit longer before embarrassing me this time. The major change is we now handle wrapped `ProcessCancelationException`s, which should mean that if a read action does get canceled we just drop it and move on with our lives.

https://www.dropbox.com/s/sg0abv2zphgmh33/CheckStyle-IDEA-5.35.1.beta2.zip?dl=0

**Comment by ahus1** [comment]
I've installed 5.35.1.beta2 and it works for me. No more immediate errors. Running Checkstyle while editing files, committing and running the whole project works. And it still reports errors when there are errors to find. The lock-ups have been very seldom, so I can't be sure that they are gone.

I wasn't able to follow all your technical comments as I am not into the technicalities of the plugin and I didn't find the latest source code changes on GitHub yet. Therefore I refrain from commenting about the implementation and/or options.

Thanks a lot for this update!

**Comment by ahus1** [comment]
@muntyan / cc: @jshiell - I had a look at the snapshot file uploaded to the JetBrains issue. Several threads seem to be stuck (or working) at the same code snippet `ClasspathStabilizer.residesInProject`. IMHO this looks quite different than the stack traces I uploaded above. And I didn't see high CPU usage, only a frozen UI.

```
ApplicationImpl pooled thread 185  Runnable CPU usage on sample: 531ms
  sun.nio.fs.WindowsNativeDispatcher.FindFirstFile0(long, WindowsNativeDispatcher$FirstFile) WindowsNativeDispatcher.java (native)
  sun.nio.fs.WindowsNativeDispatcher.FindFirstFile(String) WindowsNativeDispatcher.java:185
  sun.nio.fs.WindowsLinkSupport.getRealPath(WindowsPath, boolean) WindowsLinkSupport.java:232
  sun.nio.fs.WindowsPath.toRealPath(LinkOption[]) WindowsPath.java:891
  sun.nio.fs.WindowsPath.toRealPath(LinkOption[]) WindowsPath.java:42
  org.infernus.idea.checkstyle.checker.ClasspathStabilizer.residesInProject(Path, URL) ClasspathStabilizer.java:146
  org.infernus.idea.checkstyle.checker.ClasspathStabilizer.stabilize(List) ClasspathStabilizer.java:67
  org.infernus.idea.checkstyle.checker.ModuleClassPathBuilder.build(Module) ModuleClassPathBuilder.java:60
  org.infernus.idea.checkstyle.checker.CheckerFactory.createChecker(ConfigurationLocation, Module) CheckerFactory.java:138
  org.infernus.idea.checkstyle.checker.CheckerFactory.getOrCreateCachedChecker(ConfigurationLocation, Module) CheckerFactory.java:77
  org.infernus.idea.checkstyle.checker.CheckerFactory.checker(Module, ConfigurationLocation) CheckerFactory.java:59
  org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(PsiFile, Module, InspectionManager) CheckStyleInspection.java:90
  org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$0(PsiFile, Module, InspectionManager) CheckStyleInspection.java:63
  org.infernus.idea.checkstyle.CheckStyleInspection$$Lambda$4149.call()
  com.intellij.openapi.application.impl.ApplicationImpl$2.call() ApplicationImpl.java:274
  java.util.concurrent.FutureTask.run() FutureTask.java:264
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) ThreadPoolExecutor.java:1128
  java.util.concurrent.ThreadPoolExecutor$Worker.run() ThreadPoolExecutor.java:628
  java.lang.Thread.run() Thread.java:834
```

**Comment by jshiell** [comment]
@ahus1 thanks very much for all of your help with this, and apologies for the hassles! If the lockups do reoccur, please shout and I'll have another go. I've released this build as 5.35.1. Also - thank you for having a poke at that dump, much obliged.

@muntyan given that kind analysis by @ahus1, it does appear to be a different issue. I don't use Windows myself, so if it's platform specific it could be a problem ... first check - do you have any links in the directory being parsed? My knowledge on the Windows FS code isn't great, but I suspect it may be trying to resolve a FS link in that case. I wonder if we've fallen into a loop created by a link. In any case, could you please create a new bug so we can discuss without spamming @ahus1? Thank very much!

**Comment by jshiell** [comment]
I spoke too soon, as reported in #466 this appears to be causing perf issues for some. If you have a moment could you please try this build of 5.35.2 - this restores the background thread for the Checkstyle execution, but creates the scannable file (which requires a read lock) before starting the thread. I hope this will avoid the case above, at least, while restoring the performance for affected users. It also has a sexy plugin icon 😄 Thank you!

https://www.dropbox.com/s/s2b45fjuc95tzix/CheckStyle-IDEA-5.35.2.beta1.zip?dl=0

**Comment by ahus1** [comment]
I've installed the new version and will give it try during the day.

**Comment by ahus1** [comment]
It worked well for me throughout the day: editing files, full project scan, committing. Ready to go from what I see.

**Comment by jshiell** [comment]
Thanks very much! Hopefully this one will fare a little better in the wild 🤞
