### ISSUE TITLE
How to import configuration once for every project

### ISSUE THREAD

**Issue by lewiszlw** [jshiell/checkstyle-idea#464]
Hi, 
I am using IDEA IntelliJ IDEA 2019.2.4 (Community Edition, macOS), there is no default settings feature (I didn't find it). I have to import checkstyle configuration for every project. How to import a configuration via HTTP as default configuration like bundled?

BTW, the plugin is great!

**Comment by jshiell** [comment]
Hey - thanks for your kind comments ! Sorry, it's Christmas so not in a position to double-check right at the moment, but I think you can do this via the default project settings. If you open that then there should be a Checkstyle panel when you can configure the default options.

**Comment by jshiell** [comment]
Back at a computer, so yes, the above should work for templating new projects.

There's no feature for adding shared configurations to existing project however I'm afraid.

<img width="691" alt="Screen Shot 2019-12-27 at 14 58 17" src="https://user-images.githubusercontent.com/1030482/71521620-6d895900-28b9-11ea-9c16-9c9da049cc1d.png">
<img width="990" alt="Screen Shot 2019-12-27 at 14 58 29" src="https://user-images.githubusercontent.com/1030482/71521624-6febb300-28b9-11ea-8ddc-a9d13db45904.png">

**Comment by lewiszlw** [comment]
I don't know why IDEA(new edition) doesn't support default settings feature. So do you plan to support this via saving checks.xml in the plugin or any other way?

**Comment by jshiell** [comment]
Sorry, I don't quite understand - the screenshots above are from the latest IDEA (2019.3.1) - what version are you using?

**Comment by lewiszlw** [comment]
I am using version 2019.2.4. It doesn't support configuring for existing projects. So I need to configure my check style file for every existing projects.

**Comment by jshiell** [comment]
Ah, gotcha. As far as I know IDEA has never supported configuring templated configuration for existing projects. I've no plans to support such a feature. Your best bet is to configure the default settings for new projects, and then copy the configuration from an existing project to your other projects, e.g. 

```
cp project/.idea/checkstyle-idea.xml another-project/.idea/
```

**Comment by lewiszlw** [comment]
Ok, thanks. Maybe I can write a script to configure checkstyle for existing projects.
