### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by enzadesai** [jshiell/checkstyle-idea#466]
I just updated from 5.34.0 to 5.35.1 on IntelliJ IDEA 2019.3.1 Build 193.5662.53. There is a massive regression in performance, so much so that typing would get stuck for seconds (2-3s at times).

I am unsure what details (plugin logs, etc.) that would be useful here. I am also not certain if there are ways to instrument the plugin on my machine.

**Comment by jshiell** [comment]
Thanks for the report. Is 5.35.0 okay? There was a change in the thread handling for 5.35.1 to fix a deadlock with newer versions of IDEA, but this would result in coarser thread locking, and I was only able to test it on an i7 so it could well be the cause.

**Comment by jshiell** [comment]
Could you please try this pre-release of 5.35.2? This restores the background thread for the Checkstyle execution, but shuffles the file creation to try and avoid the deadlock in #462. Thank you!

https://www.dropbox.com/s/s2b45fjuc95tzix/CheckStyle-IDEA-5.35.2.beta1.zip?dl=0

**Comment by enzadesai** [comment]
That was so fast! Been testing this for a bit and looks great! 👍🚢

**Comment by jshiell** [comment]
Luckily I'm still on holiday - thanks very much for the report, and sorry for the hassle!
