### ISSUE TITLE
Checkstyle warnings shown twice in the IntelliJ inspections report window

### ISSUE THREAD

**Issue by mashawan** [jshiell/checkstyle-idea#467]
https://github.com/jshiell/checkstyle-idea/releases/tag/5.35.2 Seems to cause the same checkstyle violation to be reported twice in the IntelliJ inspection report (SHIFT + ALT + i)
Where running checktyle in the Checkstyle window shows it once.

Older versions https://github.com/jshiell/checkstyle-idea/releases/tag/5.34.0 for example show the correct number of violations.

We use the inspection reports all the time and would like to see the correct number of violations there.

**Comment by mashawan** [comment]
Here's a sample project to reproduce, and a screenshot of the problem occuring...

[CheckstyleTest.zip](https://github.com/jshiell/checkstyle-idea/files/4026334/CheckstyleTest.zip)
<img width="1330" alt="Capture" src="https://user-images.githubusercontent.com/3415851/71822824-c319ee80-308d-11ea-99d8-70df4e72734f.PNG">

**Comment by jshiell** [comment]
Thanks for the report. This is likely related to the fixes to accomodate the thread lock changes in newer versions of IDEA. I'll try and have a look this weekend.

**Comment by jshiell** [comment]
Even just using it for testing that was pretty annoying - sorry! Should be fixed in 5.35.3.
