### ISSUE TITLE
Activating multiple checkstyle rules at one?

### ISSUE THREAD

**Issue by SebiderSushi** [jshiell/checkstyle-idea#471]
Currently, only one checkstyle rule file can be selected at a time.

At my university, we are provided with two different checkstyle files for our coding projects. One contains rules required for source files to be accepted for grading at all, the second contains optional rules that can lead to a lower grading if violated but don't prevent the source files to be accepted.

What i wanted to do in this scenario is to activate both of these files at the same time, generating two entries to the List of Inspections. This would have the neat benefit that one of the inspections could be classified as an error while the other one could be treated as a warning.

Is this possible to implement?
Is it possible to at least allow selecting of multiple files?
What prevents such an implementation?

**Comment by tsjensen** [comment]
Yes, you can simply combine both XML files into one, and use the [Severity](https://checkstyle.org/config.html#Severity) feature to classify the first set as error, and the second set as warning.

It's ok to have a module in a file twice with different settings.

**Comment by SebiderSushi** [comment]
Thank you very much for your heads-up! Seems like i totally missed those property tags that even already were inside my files.

I have now managed to get my desired behavior. However, i have only accomplished to specify the severity per submodule. I.E. i've added the severity warning property within one of the TreeWalker modules since trying to add two Checker modules within the XML file resulted in a parsing error.

My files only contain one TreeWalker module that i want treated differently. However, there are many modules in total and i wonder how to comfortably apply a property tag to arbitrary sets of those modules instead of tinkering with each of them one-by-one. Since enclosing each set within an own Checker module doesn't seem to be valid and since i don't know about any other method of enclosing multiple modules i'm out of ideas here.

Generally, i am completely new to checkstyle and only just got in contact with it at all through university, so please excuse my cluelessness.

**Comment by tsjensen** [comment]
Yeah, I think you're currently stuck with specifying the severity on all of the modules, as there is no grouping functionality that would help you.

But you can always [suggest it as a new feature](https://github.com/checkstyle/checkstyle/issues) with the Checkstyle folks. Who knows, they might like the idea too and implement it. 😉

**Comment by jshiell** [comment]
Thanks @tsjensen - I've been travelling this week, so greatly appreciate your help here!

As said, we don't support this as the general approach would be a single file with multiple levels. As such, I've no great desire to add niche features - things are complex enough as they are!

**Comment by SebiderSushi** [comment]
Thank you very much!
Thanks to all of your explanations i am now aware of how to handle this use case and that there is no need to implement something new here :)
