### ISSUE TITLE
Checkstyle import MaxLength and Wrap if long

### ISSUE THREAD

**Issue by ltsallas** [jshiell/checkstyle-idea#487]
Hi everybody,

I am importing a google_checks.xml into IntelliJ IDEA. 
e.g  https://github.com/checkstyle/checkstyle/blob/checkstyle-8.29/src/main/resources/google_checks.xml

There is a  max Line length rule 100 

IntelliJ correctly sets "Hard wrap at"to  120 in Code Style -> Java -> Wrapping and Braces but does not set "Wrap if long" in all the categories, e.g "Method declaration parameters" so when auto formatting with Ctrl+Alt+L I still get code style violations. As a workaround I have to manually set every option to "Wrap if long"

Shouldn't this setting be applied automatically on import?

**Comment by jshiell** [comment]
Thanks for the report. Seems fair, to be honest. As to whether it'll get fixed, I fear that's unlikely - the code layout import was a contribution so I don't know the code very well, and hence it's not a high priority - sorry. Contributions are, of course, welcome.

**Comment by ltsallas** [comment]
I am glad you find it reasonable, I will have a look at the importer package and try to work on a pull request.

**Comment by jshiell** [comment]
I found some free time today and had a look - could you please check in 5.36.2 resolves the issue for you?

**Comment by ltsallas** [comment]
It works!
Thank you!
