### ISSUE TITLE
Please update up to date google checkstyle xml with suppress properties

### ISSUE THREAD

**Issue by 1951FDG** [jshiell/checkstyle-idea#488]
Checkstyle added suppression filters to google_checks.xml:
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml

https://github.com/checkstyle/checkstyle/issues/6946

It would be great if the default bundled Google Checks includes the latest google_checks.xml,
so that new users can specify a suppression xml file, e.g.,

![image](https://user-images.githubusercontent.com/220168/78416938-4e733380-762d-11ea-8ff4-9d7bed8658a0.png)

This could be useful for new users, and also avoids having the need for two Google Checks when suppression is required.

**Comment by jshiell** [comment]
We make available the Google checks that are bundled with Checkstyle, so the version will be newer if you use a more recent Checkstyle version.  Likewise, new versions from Google will be packaged with newer Checkstyle releases, and hence become the plugin once added. Given Checkstyle tend to do a new release every month the time lag isn’t too great.

I fear I’ve no plans to package Google checks ourselves, given that the file layout will not be able to support all the versions of Checkstyle that we support, and given that Checkstyle already do the job for us.

**Comment by alex-albericio** [comment]
Wasn't that included in checkstyle 8.28? I'm using 8.32 and @SuppressWarnings seem to have no effect, warnings don't disappear.

**Comment by jshiell** [comment]
If SupressWarnings aren't working for you then please raise a new issue with the appropriate details.

**Comment by alex-albericio** [comment]
Sorry. Turns out is was a misconfiguration issue. My apologies 🙏
