### ISSUE TITLE
CheckStyle-Idea not working for one project

### ISSUE THREAD

**Issue by mcmasjc3** [jshiell/checkstyle-idea#491]
I hate to open an issue for this, but I don't see a forum for questions.

I installed the plugin on Idea 2020.1.1 (Professional) Build #IU-201.7223.91, built on April 29, 2020. This is on a Mac running macOS Catalina Version 10.15.4.

I enabled the plugin for three Java projects using the built-in Google Java Style rules.. Two of them work as expected.  The third simply doesn't show any issues, though they definitely are there. The CheckStyle window says "No scan has been run as yet" and there is no green arrow to run the scan.  If I run the scan manually through Analyze -> Run inspection by name..., I get a message "No suspicious code found".

This could be a setup problem, but I don't see it.  Any suggestions?

**Comment by jshiell** [comment]
There isn't a forum; this venue is perfectly fine.

That's odd indeed. The inspection and the tool window run on entirely seperate trigger paths, so it's interesting that both aren't functioning. Starting with the tool window, as it's simpler, the only reasons (from memory) that the green arrrow should be disabled are 

a) if the project is indexing; 
b) if there's no configuration file configured (or if its disabled for the module)
c) if the file isn't valid (i.e. it's not a Java file, or it's a test file and test scope is disabled)

Given you've configured it perfectly for two other projects, (b) seems unlikely. My initial thoughts would be that (c) is the most likely cause - what's the scope set to in the configuration panel, and do you know of any reason why it might not consider the current file valid? 

Also, are the "scan current module"/"scan current project" files enabled in the tool window?

**Comment by mcmasjc3** [comment]
I am using the same config file for all three projects, the built-in Google Checks. I don't think the project is indexing after all this time. I started with the "Only Java Sources (including tests)" scope, but have tried them all.  I have tried several files, and the entire project, so I don't think it is one bad file.  Neither scan is enabled in the tool window. I am attaching screen shots of settings and the tool window.
![Screen Shot 2020-05-26 at 3 13 20 PM](https://user-images.githubusercontent.com/29512087/82951481-7b283500-9f64-11ea-8e3c-0e03fa8deea9.png)
![Screen Shot 2020-05-26 at 3 19 15 PM](https://user-images.githubusercontent.com/29512087/82951492-80857f80-9f64-11ea-893f-846bfa1b66df.png)

If there are any diagnostics or logs, I will try to provide them.

**Comment by jshiell** [comment]
Sorry for the delay. I've utterly failed to come up with any ideas.

The `Scan Project` button is clearly disabled in your screenshot. So, focusing on that - as it's the simplest - [the rules are pretty simple](https://github.com/jshiell/checkstyle-idea/blob/3e60916f1a55aafee3b2756148d8dbde469fa642/src/main/java/org/infernus/idea/checkstyle/actions/ScanProject.java#L62):

* There must be a valid, open project
* The project must have a valid file (by IDEA's reckoning, using `VirtualFile.isValid()`) in either one of the content roots (if scan scope is `all files in project`) or one content source roots.
* There must be no already scan in progress.

Assuming you have a valid source file in your project, I can't see why any of those rules wouldn't pass.

Hence, no bright ideas at present I'm afraid.

**Comment by mcmasjc3** [comment]
The project apparently was corrupt somehow.  I deleted .idea and started from scratch.  Now Checkstyle-Idea is functioning.  Sorry for the unnecessary bug report.

**Comment by jshiell** [comment]
No problem - just glad everything is working again for you!
