### ISSUE TITLE
Add ability to enter username/password for "accessible via HTTP"

### ISSUE THREAD

**Issue by tonyfalabella** [jshiell/checkstyle-idea#493]
Would it be possible to add the ability to enter a username/password for "accessible via HTTP"?  Our Bitbucket repos requires id/password to be entered to authenticate.  This is similar to calling a url like this in curl:

`curl -u USERNAME:PASSWORD https://bitbucket.com/projects/PROJECT/repos/REPOS/xxx`

Without that we're forced to using a local file, which makes our setup cumbersome.

Ideally it would be nice to add an "accessible via HTTP" to the suppression file too.

**Comment by jshiell** [comment]
It's not as simple as it might appear I fear, as then we'd have to manage stored credentials, or prompt regularly.

Does including them in the URL work, e.g. https://user:password@bitbucket.org/... ?

**Comment by tonyfalabella** [comment]
I figure it's a bit of a slippery slope with the auth for sites as there's many different auth techniques.  I think our particular site is using Basic Auth.  I've tried your suggestion, unfortunately it doesn't work.

**Comment by tsjensen** [comment]
You may have to use a *token*, not a password, so it‘s `user:token@host...`. At least that‘s how GitHub and GitLab work.

**Comment by jshiell** [comment]
I've confirmed that `http://username:password@host/` works for basic auth sites in current builds. Given the challenges and risks of password management, I fear support will be limited to this approach.
