### ISSUE TITLE
Unable to use suppression file with plugin

### ISSUE THREAD

**Issue by fayimora** [jshiell/checkstyle-idea#497]
### Background
I have a spring boot project with checkstyle maven plugin configured. Everything works as expected. I recently switched to google_checks and wanted to use this plugin in IntelliJ but I can't get the plugin to use my suppression file.

A sample project can be found [here](https://github.com/fayimora/java-springboot-app/tree/checkstyle) (ensure you're on the checkstyle branch)

I changed my `configLocation` in the pom to `<configLocation>google_checks.xml</configLocation>` which is bundled with the maven plugin and everything works fine. The suppression file is respected. I also installed the checkstyle-idea plugin in IntelliJ and was able to select the bundled Google Checks which gave me the violations I was expecting.

### Issue

The main issue I'm facing with the plugin is having it respect the suppressions file. From what I understand, you have to use a suppression filter and the default(from this codebase) looks like this:

```xml
<module name="SuppressionFilter">
        <property name="file" value="${org.checkstyle.google.suppressionfilter.config}"
                  default="checkstyle-suppressions.xml" />
        <property name="optional" value="true"/>
    </module>
```

I set that property in my pom and I do have a `checkstyle-suppressions.xml` in my resources folder but the suppressions aren't being read.

### Questions
- Can someone please assist with a step-by-step guide on exactly what is required to get all this working. The documentation makes the assumption everyone is very familiar with checkstyle. I'm happy to contribute back to the docs  for future users.

- I'm getting the feeling a separate checkstyle config, in this case, a duplicate `google-checks.xml` is required. Is this correct?

- Is this plugin using the same google_checks config as checkstyle? I ask because when running checks in the plugin and via `mvn checkstyle:check`, I'm seeing different violation names. E.g `Indentation` vs `IndentationCheck`

Cheers

**Comment by jshiell** [comment]
> I set that property in my pom

We don't read the POM at all - there's no Maven integration in the plugin. You'll need to set the property when you add the rules file in IDEA.

If you don't set it, I believe - from memory - that we'll try looking for the file in the directory of the rules file (which won't apply if you use the packages rules), then in the root of the project directory. I don't believe (from memory) that we check the classpath, as we don't know the state of it (e.g. has IDEA copied all the files? Is it up to date?)

If you're using the bundle Google Checks and you're happy with the version that's packaged with Checkstyle then you shouldn't need a duplicate file.

The plugin uses the Google Checks packaged with the given version of Checkstyle - so yes, it should be identical. The violation names may vary slightly, as I think we remove the redundant `Check` in the message, but the content should otherwise match.

**Comment by fayimora** [comment]
@jshiell Thanks for the response. 

> If you're using the bundle Google Checks and you're happy with the version that's packaged with Checkstyle then you shouldn't need a duplicate file.

I am using the bundled google checks for both the maven plugin and this plugin. I guess what I need are instructions on how to setup [these suppressions](https://github.com/fayimora/java-springboot-app/blob/checkstyle/src/main/resources/checkstyle-suppressions.xml) for the plugin while using the bundled checks. Can you help with this pls?

**Comment by jshiell** [comment]
Having check the code, it appears the bundled property files do not currently support editing the properties. Hence I think you have two options at present.

a) don't use the bundled Google Checks, but use a separate copy. When you add this in the configuration then you'll be able to edit the property to point at your suppressions file.
b) move or symlink the suppressions XML to the root project directory. Our [fallback](https://github.com/jshiell/checkstyle-idea/blob/7cab0dda452a5b2ed8ef9dcbadb65c3ca45b562e/src/main/java/org/infernus/idea/checkstyle/model/ConfigurationLocation.java#L229) should check there as a worst case.

Ideally we'd allow editing the properties for the bundled file, but I've no time/inclination to look at this at present. Sorry.

**Comment by n-n-nebbl** [comment]
Hi,
we also have this problem. we want to use the google checks and it would be convenient to just use the bundled one, but we have suppressions configured which are not used by the checkstyle-idea plugin.
Our file is located in the project root and is called "checkstyle-suppressions.xml", but it is still not getting picked up.

would be nice to have a way to use a suppressions file with the bundled configuration file

**Comment by jshiell** [comment]
Properties for bundled configs are, shockingly, now editable as of 5.51.0.
