### ISSUE TITLE
Support checkstyle 8.35

### ISSUE THREAD

**Issue by mickroll** [jshiell/checkstyle-idea#498]
[Checkstyle 8.35](https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-8.35) is out. It would be nice if checkstyle-idea supports it.

Release notes: https://checkstyle.org/releasenotes.html#Release_8.35

Hint: eclipse-cs was faster this time: https://github.com/checkstyle/eclipse-cs/issues/243 ;)

**Comment by jshiell** [comment]
What, they did? The scoundrels! Well, in that case, released as 5.41.0!

😄
