### ISSUE TITLE
Support for Checkstyle 8.36.1

### ISSUE THREAD

**Issue by eggilbert** [jshiell/checkstyle-idea#501]
Checkstyle [8.36.1](https://checkstyle.org/releasenotes.html#Release_8.36.1) is released and has some additional bug fixes for JDK 14 support.

Can this be added to the plugin? Thanks!

**Comment by jshiell** [comment]
Sorry for the delay; now released as 5.43.0.

**Comment by eggilbert** [comment]
Thanks! 🙌
