### ISSUE TITLE
Intellij 2020.3 EAP compatibility

### ISSUE THREAD

**Issue by doublefx** [jshiell/checkstyle-idea#503]
Hi,

I just updated IJ to the last EAP along with CheckStyle plugin, haven't changed anything else in my checkStyle settings and get:

12:55	The Checkstyle rules file could not be parsed.
			LineLength is not allowed as a child in Checker
			The file has been blocked for 60s.

**Comment by jshiell** [comment]
What version of Checkstyle do you have selected, and does it match the rules file? LineLength was moved out of Checker at some point - https://github.com/checkstyle/checkstyle/issues/2116

**Comment by jshiell** [comment]
This changed in Checkstyle 8.24, apparently - https://checkstyle.sourceforge.io/releasenotes.html

You'll need to either update the rules file, or select Checkstyle version 8.23 or below.

**Comment by doublefx** [comment]
The checkstyle version I use: 7.8.2 and matching the rule file

updating to 8.24 seems to work, still need some more tests though.

Thanks @jshiell !

**Comment by doublefx** [comment]
The checkstyle version I use: 7.8.2 and matching the rule file

updating to 8.24 seems to work, still need some more tests though.

Thanks @jshiell !
