### ISSUE TITLE
macOS Big Sur + custom checkstyle config file are not working anymore

### ISSUE THREAD

**Issue by GregoireLgt** [jshiell/checkstyle-idea#504]
Hello, 

I am running Checkstyle-IDEA plugin on Intellij for a school project. 

Yesterday everything was working fine. But after macOS Big Sur update, when I run a checkstyle analysis, it doesn't find any problems in my project. I have a custom checkstyle rules configuration file. I am sure that I have checkstyle problems in my coding "syntax" because I had ones yesterday and now it is gone.

I tried to delete and add again my configuration file but it seems it doesn't check correctly the project. 

Thanks a lot,

**Comment by jshiell** [comment]
Hi. If you attach your rules files, and tell me the version of Checkstyle you have selected, then I can give it a sanity check.

I can't see any obvious way it can be related to Big Sur; however, I don't have a machine that I can run Big Sur on at present, so I fear any testing will be with Catalina or High Sierra.

**Comment by GregoireLgt** [comment]
Thanks for your answer !
I am running : 
CheckStyle 8.37
CheckStyle-IDEA (plugin) 5.45.1

Unfortunately, I am not able to attach my .xml files (GitHub saying "We don't support that file type".

**Comment by jshiell** [comment]
Can you copy & paste the contents please?

**Comment by GregoireLgt** [comment]
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE module PUBLIC "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN" "https://checkstyle.org/dtds/configuration_1_3.dtd">



<module name="Checker">
  <property name="severity" value="error"/>
    <module name="LineLength">
      <property name="max" value="120"/>
    </module>
    <module name="TreeWalker">
      <module name="JavadocType">
        <property name="tokens" value="INTERFACE_DEF,ENUM_DEF,CLASS_DEF,ANNOTATION_DEF"/>
      </module>
      <module name="JavadocMethod">
        <property name="scope" value="public"/>
        <property name="tokens" value="METHOD_DEF, CTOR_DEF, ANNOTATION_FIELD_DEF, COMPACT_CTOR_DEF"/>
      </module>
      <module name="JavadocMissingWhitespaceAfterAsterisk"/>
      <module name="MissingJavadocMethod"/>
      <module name="NonEmptyAtclauseDescription">
        <property name="javadocTokens"
                  value="PARAM_LITERAL,RETURN_LITERAL,THROWS_LITERAL,EXCEPTION_LITERAL,DEPRECATED_LITERAL"/>
      </module>
      <module name="Indentation">
        <property name="basicOffset" value="4"/>
        <property name="caseIndent" value="4"/>
      </module>
      <module name="JavadocTagContinuationIndentation"/>
      <module name="AtclauseOrder"/>
      <module name="AbstractClassName"/>
      <module name="ClassTypeParameterName"/>
      <module name="ConstantName"/>
      <module name="LocalFinalVariableName"/>
      <module name="LocalVariableName"/>
      <module name="MemberName"/>
      <module name="MethodName"/>
      <module name="MethodTypeParameterName"/>
    <module name="InterfaceTypeParameterName"/>
    <module name="PackageName"/>
    <module name="ParameterName">
      <property name="accessModifiers" value="public"/>
    </module>
    <module name="StaticVariableName"/>
    <module name="TypeName"/>
    <module name="AvoidStaticImport"/>
    <module name="IllegalImport"/>
    <module name="RedundantImport"/>
    <module name="UnusedImports"/>
    <module name="AnonInnerLength"/>
    <module name="ExecutableStatementCount">
      <property name="tokens" value="INSTANCE_INIT,STATIC_INIT,METHOD_DEF,CTOR_DEF"/>
    </module>
    <module name="MethodLength"/>
    <module name="ParameterNumber"/>
    <module name="OuterTypeNumber"/>
      <module name="MethodCount"/>
      <module name="GenericWhitespace"/>
      <module name="EmptyForInitializerPad"/>
      <module name="EmptyForIteratorPad"/>
      <module name="NoWhitespaceAfter"/>
      <module name="NoWhitespaceBefore"/>
      <module name="MethodParamPad"/>
      <module name="ParenPad">
        <property name="tokens"
                  value="ANNOTATION,ANNOTATION_FIELD_DEF,CTOR_DEF,CTOR_CALL,DOT,ENUM_CONSTANT_DEF,EXPR,LAMBDA,LITERAL_CATCH,LITERAL_DO,LITERAL_FOR,LITERAL_IF,LITERAL_NEW,LITERAL_SWITCH,LITERAL_SYNCHRONIZED,LITERAL_WHILE,METHOD_CALL,METHOD_DEF,RESOURCE_SPECIFICATION,SUPER_CTOR_CALL,QUESTION"/>
      </module>
      <module name="TypecastParenPad">
        <property name="option" value="nospace"/>
      </module>
      <module name="WhitespaceAfter">
        <property name="tokens" value="COMMA, SEMI"/>
      </module>
      <module name="WhitespaceAround">
        <property name="tokens"
                  value="ASSIGN,BAND,BAND_ASSIGN,BOR,BOR_ASSIGN,BSR,BSR_ASSIGN,BXOR,BXOR_ASSIGN,COLON,DIV,DIV_ASSIGN,DO_WHILE,EQUAL,GE,GT,LAMBDA,LAND,LCURLY,LE,LITERAL_ASSERT,LITERAL_CATCH,LITERAL_DO,LITERAL_ELSE,LITERAL_FINALLY,LITERAL_FOR,LITERAL_IF,LITERAL_RETURN,LITERAL_SWITCH,LITERAL_SYNCHRONIZED,LITERAL_TRY,LITERAL_WHILE,LOR,LT,MINUS,MINUS_ASSIGN,MOD,MOD_ASSIGN,NOT_EQUAL,PLUS,PLUS_ASSIGN,QUESTION,RCURLY,SL,SLIST,SL_ASSIGN,SR,SR_ASSIGN,STAR,STAR_ASSIGN,TYPE_EXTENSION_AND"/>
      </module>
      <module name="ModifierOrder"/>
      <module name="RedundantModifier"/>
      <module name="RegexpSinglelineJava">
        <property name="format" value="^.*System.exit(.*).*$"/>
        <property name="message" value="Une sortie plus élégante est attendue."/>
        <property name="ignoreComments" value="true"/>
      </module>
      <module name="RegexpSinglelineJava">
        <property name="format" value="^.*printStackTrace(.*).*$"/>
        <property name="message" value="Un affichage plus élégant du problème est attendu."/>
        <property name="ignoreComments" value="true"/>
      </module>
      <module name="AvoidNestedBlocks">
        <property name="allowInSwitchCase" value="true"/>
      </module>
      <module name="EmptyBlock">
        <property name="option" value="text"/>
      </module>
      <module name="EmptyCatchBlock"/>
      <module name="LeftCurly">
        <property name="tokens"
                  value="ANNOTATION_DEF, CLASS_DEF, CTOR_DEF, ENUM_CONSTANT_DEF, ENUM_DEF,
                    INTERFACE_DEF, LAMBDA, LITERAL_CASE, LITERAL_CATCH, LITERAL_DEFAULT,
                    LITERAL_DO, LITERAL_ELSE, LITERAL_FINALLY, LITERAL_FOR, LITERAL_IF,
                    LITERAL_SWITCH, LITERAL_SYNCHRONIZED, LITERAL_TRY, LITERAL_WHILE, METHOD_DEF,
                    OBJBLOCK, STATIC_INIT, RECORD_DEF, COMPACT_CTOR_DEF"/>
      </module>
    <module name="NeedBraces">
      <property name="tokens" value="LITERAL_DO,LITERAL_ELSE,LITERAL_IF,LITERAL_FOR,LITERAL_WHILE"/>
    </module>
     <module name="RightCurly">
      <property name="id" value="RightCurlySame"/>
      <property name="tokens"
               value="LITERAL_TRY, LITERAL_CATCH, LITERAL_FINALLY, LITERAL_IF, LITERAL_ELSE,
                    LITERAL_DO"/>
    </module>
    <module name="RightCurly">
      <property name="id" value="RightCurlyAlone"/>
      <property name="option" value="alone"/>
      <property name="tokens"
               value="CLASS_DEF, METHOD_DEF, CTOR_DEF, LITERAL_FOR, LITERAL_WHILE, STATIC_INIT,
                    INSTANCE_INIT, ANNOTATION_DEF, ENUM_DEF, INTERFACE_DEF, RECORD_DEF,
                    COMPACT_CTOR_DEF"/>
    </module>
    <module name="BooleanExpressionComplexity"/>
    <module name="ClassDataAbstractionCoupling"/>
    <module name="ClassFanOutComplexity"/>
    <module name="CyclomaticComplexity"/>
    <module name="JavaNCSS"/>
    <module name="NPathComplexity"/>
    <module name="HideUtilityClassConstructor"/>
    <module name="InnerTypeLast"/>
    <module name="InterfaceIsType">
      <property name="allowMarkerInterfaces" value="false"/>
    </module>
    <module name="OneTopLevelClass"/>
    <module name="ArrayTypeStyle"/>
    <module name="CommentsIndentation"/>
    <module name="NoCodeInFile"/>
    <module name="OuterTypeFilename"/>
    <module name="AvoidDoubleBraceInitialization"/>
    <module name="AvoidNoArgumentSuperConstructorCall"/>
    <module name="DefaultComesLast"/>
    <module name="DeclarationOrder"/>
    <module name="EmptyStatement"/>
    <module name="EqualsAvoidNull"/>
    <module name="ExplicitInitialization">
      <property name="onlyObjectReferences" value="true"/>
    </module>
    <module name="IllegalCatch"/>
    <module name="IllegalThrows"/>
    <module name="InnerAssignment"/>
    <module name="MissingSwitchDefault"/>
    <module name="ModifiedControlVariable">
      <property name="skipEnhancedForLoopVariable" value="true"/>
    </module>
    <module name="NestedForDepth">
      <property name="max" value="2"/>
    </module>
    <module name="NestedIfDepth">
      <property name="max" value="3"/>
    </module>
    <module name="NestedTryDepth"/>
    <module name="NoArrayTrailingComma"/>
    <module name="NoEnumTrailingComma"/>
    <module name="OneStatementPerLine"/>
    <module name="OverloadMethodsDeclarationOrder"/>
    <module name="PackageDeclaration"/>
    <module name="ParameterAssignment"/>
    <module name="SimplifyBooleanExpression"/>
    <module name="SimplifyBooleanReturn"/>
    <module name="StringLiteralEquality"/>
    <module name="UnnecessaryParentheses"/>
  </module>
  <module name="FileLength"/>
  <module name="UniqueProperties">
    <property name="fileExtensions" value="properties" />
  </module>
</module>

**Comment by GregoireLgt** [comment]
[Configuration_Checkstyle_QL_2020.txt](https://github.com/jshiell/checkstyle-idea/files/5537737/Configuration_Checkstyle_QL_2020.txt)

Not able to past the content also (blank comment I dunno why), so here is the xml file converted to txt

**Comment by jshiell** [comment]
👍 That worked nicely, thanks.

There's good news, and bad news.  The good news is that it works correctly for me - I add it, rescan my source (the plugin in this case), and I'm getting back a heap of errors that appear correct based on the configured rules, both in the static view and the inline scanner.

That's with Checkstyle 8.37 and plugin 5.45.1 (installed from the repo).

So that's also the bad news, in that it seems to work correctly for me. Which leaves us with no leads to go on...

I still can't think of any reason Big Sur would break this. My Hackintosh has a Nvidia card though, and my work MBP can't be upgraded due to a dependency on an old Cisco client, so I'm not going to be able to test on it any time soon.

Assuming there's nothing in the event log, then I'm short on ideas at present I'm afraid.

**Comment by GregoireLgt** [comment]
That's really strange because I am sure it was working before updating my MBP to Big Sur. Indeed, I am running checkstyle on this project (with these rules) and on Catalina for almost 2 months now without any single problem

I'll try rebooting again my MBP and see what happens but that's bad news for me...

Anyway, thanks for your help and your answers.

**Comment by jshiell** [comment]
Do of course note that "I still can't think of any reason Big Sur would break this" doesn't mean that it isn't, and I'm just not thinking hard enough. But if this is the case hopefully we'll see more bug reports soon, which might give us a guide as to where the problem is.

**Comment by GregoireLgt** [comment]
+up 

I found that using another version of checkstyle (before 8.36.2) gets me an unexpected exception caught when I run a checkstyle analysis : 

Unexpected Exception Caught
			The scan failed due to an exception: Error executing command 'OpCreateChecker': given name COMPACT_CTOR_DEF
			Root cause:
			given name COMPACT_CTOR_DEF
			java.lang.IllegalArgumentException: given name COMPACT_CTOR_DEF
			at com.puppycrawl.tools.checkstyle.utils.TokenUtil.getTokenId(TokenUtil.java:174)
			at com.puppycrawl.tools.checkstyle.TreeWalker.registerCheck(TreeWalker.java:212)
			at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:130)
			at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
			at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:477)
			at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
			at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:61)
			at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.... (show balloon)

**Comment by jshiell** [comment]
That's because `COMPACT_CTOR_DEF` was only introduced in relatively recent versions of Checkstyle - https://github.com/checkstyle/checkstyle/commit/534a1669d67f62f1e64e879899fbeafaec41d364 - looks like it's a 8.36 feature, so that error is valid.

**Comment by GregoireLgt** [comment]
Okay, and now running the last version of Checkstyle, it is saying : The source file could not be parsed by Checkstyle

**Comment by jshiell** [comment]
That usually means that your Java source is malformed. Checkstyle is designed to parse only valid Java, and blows up on syntax errors. Obviously IDEA’s inspections mean we may get malformed code during editing, so we catch most of these.

If there’s no obvious cause, another option is to run Checkstyle itself on the file - this can help with isolating problems with the plugin and problems with checkstyle itself.
