### ISSUE TITLE
Use CheckStyle rules when formatting/generating code within IntelliJ

### ISSUE THREAD

**Issue by donalmurtagh** [jshiell/checkstyle-idea#505]
When code is generated (e.g. getters/setters) or formatted within IntelliJ, it will use the current code style scheme to determine the rules to apply, e.g. indentation size, line length, etc.

Is there a way to force IntelliJ to use the CheckStyle rules instead such that when code is generated/formatted within IntelliJ it will necessarily be compliant with CheckStyle?

**Comment by jshiell** [comment]
There is some limited support for generating the coding style from Checkstyle (Preferences -> Editor -> Code Style -> Scheme -> Import Scheme -> CheckStyle Configuration). However, this was a third party contribution and it does have known issues at present.
