### ISSUE TITLE
Support the config_loc variable for specifying suppressions file location

### ISSUE THREAD

**Issue by donalmurtagh** [jshiell/checkstyle-idea#506]
I've using the Gradle Checkstyle plugin. The [plugin recommends](https://docs.gradle.org/current/userguide/checkstyle_plugin.html#sec:checkstyle_configuration) using the `${config_loc}` variable to specify the location of the suppressions file from the rules file, e.g.

```xml
    <module name="SuppressionFilter">
        <property name="file" value="${config_loc}/suppressions.xml"/>
        <property name="optional" value="false"/>
    </module>
```

In my case the relative path to the Checkstyle files from the root of my project is

- `config/checkstyle/checkstyle.xml`
- `config/checkstyle/suppressions.xml`

This works when I run Checkstyle via Gradle, but when using the IntelliJ plugin, after I import the rules file I get a balloon warning notification that says

> The Checkstyle suppression filter file was not found and will be ignored

I've tried specifying the location of the suppressions file in various other ways e.g.

1. `<property name="file" value="suppressions.xml"/>`
1. `<property name="file" value="./suppressions.xml"/>`
1. `<property name="file" value="config/checkstyle/suppressions.xml"/>`

But none of these seem to work in IntelliJ either. Even if they did work in IntelliJ, they wouldn't work under Gradle, which seems to require the use of `${config_loc}`.

**Comment by jshiell** [comment]
Thanks for the report. I believe this *should* work, so it sounds like something that needs investigation. However, I can't promise when I'll get to it as I'm just coming up to a house move and hence life is chaos for the next few weeks - nevertheless, I'll try and have a look when I can.

**Comment by donalmurtagh** [comment]
@jshiell sorry, this is entirely my own fault. I didn't realise that you can enter a value for the `${config_loc}` variable on the modal that appears after you add the rules file. Once I did this, it works perfectly. Sorry about this, and good luck with the move.

**Comment by jshiell** [comment]
No worries, glad it’s working!
