### ISSUE TITLE
Rules file per Gradle module

### ISSUE THREAD

**Issue by donalmurtagh** [jshiell/checkstyle-idea#507]
When using Checkstyle via the Gradle plugin, it's possible to associate a different rules file with each module, e.g. one might want less strict checks in the test source than in the main source

```groovy
checkstyleMain {
    configFile = file("${rootDir}/config/checkstyle/main.xml")
}

checkstyleTest {
    configFile = file("${rootDir}/config/checkstyle/test.xml")
}
```

Although the IntelliJ plugin allows multiple rules files to be added, only one of them can be active at a time i.e. you can't associate different rules files with different modules.

**Comment by jshiell** [comment]
You should be able to do this already - project settings -> modules -> checkstyle tab for module. You should then be able to select the rules file to use for that module, or exclude the module from checks.
