### ISSUE TITLE
Error when loading a checkstyle file via http url in the plugin

### ISSUE THREAD

**Issue by samvaity** [jshiell/checkstyle-idea#509]
I am getting the following error when I try to use a checkstyle file accessible via HTTP url.

![image](https://user-images.githubusercontent.com/16845631/101110384-bb104a80-358d-11eb-8f39-3d10c76e1676.png)

Do we need any other configuration to load a custom checkstyle file in Intellij using this plugin? Is this a known bug?

**Comment by jshiell** [comment]
That doesn't appear to have anything to do with HTTP, but with the third-party check `com.azure.tools.checkstyle.checks.JavadocThrowsChecks`. Have you added this to the third-party classpath before attempting to load the file?

**Comment by samvaity** [comment]
>That doesn't appear to have anything to do with HTTP, but with the third-party check com.azure.tools.checkstyle.checks.JavadocThrowsChecks. Have you added this to the third-party classpath before attempting to load the file?

I haven't. Do we have a guide of the required steps for loading a custom checkstyle file?

**Comment by samvaity** [comment]
I think I was successfully able to add the checkstyle files but when run on the file see the following error 
![image](https://user-images.githubusercontent.com/16845631/101408425-3d03ba80-3891-11eb-8fda-75d635d56565.png)

**Comment by jshiell** [comment]
That looks like a class-loading issue. Are you using the same version of Checkstyle that the third-party check is compiled against?

**Comment by samvaity** [comment]
Using the same version worked, thanks
