### ISSUE TITLE
CheckStyle.xml SingleLineJavadoc does not match the GoogleStyle format plugin in idea.

### ISSUE THREAD

**Issue by zhangmingshuang** [jshiell/checkstyle-idea#511]
I use the idea's "Google-Style-Format" plugin-in to format my codes. but the plugin-in formats comments no more then one line as:

/** Create a new {@code ConcurrentReferenceHashMap} instance. */
  public ConcurrentReferenceHashMap() {
However, in ”Check-Style“, if it's a constant or a class, the "Check-Style" wants the comment document to be multi-line.
it said likes: "the java-doc comment should be mulit-line. [SingleLineJavadoc]"

Thank you in advance.

guide update - google/styleguide@594d91b#diff-b6c9191ee5ccb7a5ef170e98e51d94d8L1084

**Comment by jshiell** [comment]
What rules file are you using for Checkstyle? This should be controlled by the rules file - checkstyle itself (and the plugin) have no impact on this beyond what the rules file tells them to do.

If it’s the built in rules files (Sun, Google) then you’d need to talk to the Checkstyle project, as we just use the packaged version. If it’s your own rules then you’d need to change the rules to match your formatting.

**Comment by jshiell** [comment]
Closing due to no further info.
