### ISSUE TITLE
settings remove last line in checkstyle-idea.xml

### ISSUE THREAD

**Issue by silverailscolo** [jshiell/checkstyle-idea#517]
My project requires (set in IntelliJ as Editor preference) to have an ampty (blank) line as the last line in all (java and) xml files.
However checkstyle-idea keeps removing that blank line in `.idea/checkstyle-idea.xml`, so it does not apply to the rules set in `.idea/codeStyleConfig.xml` (BLANK_LINES_BEFORE_CLASS_END).

**Comment by jshiell** [comment]
`checkstyle-idea.xml` is an internal configuration file, and shouldn't be edited directly, so I'm not sure why this would matter. But in any case, this is saved through the IDEA API - we don't have any control over the formatting of the file. Hence I'm afraid this won't be changed.

https://github.com/jshiell/checkstyle-idea/blob/master/src/main/java/org/infernus/idea/checkstyle/config/ProjectConfigurationState.java
