### ISSUE TITLE
Won't work with Coursera Checkstyle... Showing error: The Checkstyle rules file could not be read

### ISSUE THREAD

**Issue by thecoderenroute** [jshiell/checkstyle-idea#518]
![image](https://user-images.githubusercontent.com/32408025/112095486-98e51b80-8bc2-11eb-9beb-b180fbf61333.png)

Checkstyle version: 5.48.0
IntelliJ Version: 2020.3.3

**Comment by jshiell** [comment]
Please attached the offending rules file (or a link to it).

What version of Checkstyle do you have selected?

**Comment by thecoderenroute** [comment]
So I manually selected the checkstyle file from the project and it's working now.
( I just need to manually select the file from the .lift folder every time I start IntelliJ
