### ISSUE TITLE
Checkstyle 8.42

### ISSUE THREAD

**Issue by remal** [jshiell/checkstyle-idea#524]
In Checkstyle 8.42 `scope` property for `JavadocMethod` and `MissingJavadocMethod` modules was replaced with `accessModifiers` (see https://github.com/checkstyle/checkstyle/issues/7417). As we have our own checkstyle.xml file in the project's root, right now this file can't be used by Checkstyle-IDEA.

Could you please add 8.42 to the list of supported versions?

**Comment by jshiell** [comment]
I’ll try and get this sorted this weekend 👍

**Comment by jshiell** [comment]
Added in 5.52.0.
