### ISSUE TITLE
Checkstyle 8.42 doesn't work with JavadocMethod.accessModifiers

### ISSUE THREAD

**Issue by remal** [jshiell/checkstyle-idea#525]
In Checkstyle 8.42 scope property for JavadocMethod and MissingJavadocMethod modules was replaced with accessModifiers (see checkstyle/checkstyle#7417).

I've selected `8.42` as a checkstyle version for the plugin, however, the `checkstyle.xml` file from attached [checkstyle.zip](https://github.com/jshiell/checkstyle-idea/files/6420082/checkstyle.zip) still can't be parsed. I still have this error message:
```
The Checkstyle rules file could not be parsed.
cannot initialize module TreeWalker - cannot initialize module MissingJavadocMethod - Property 'accessModifiers' does not exist, please check the documentation
The file has been blocked for 60s.
```

Is there a chance that I broke smth when I **manually** set checkstyle version to `8.42` in `.idea/checkstyle-idea.xml` **before** updating the plugin? If "yes" how it can be debugged and fixed?

I tried to enable debug logging for the plugin, but IDEA log doesn't contain a full Checkstyle exception with its stacktrace.

**Comment by jshiell** [comment]
Good news and bad news. 

The good news is that you haven't broken anything - I can reproduce the problem. And the rules file works correctly with `checkstyle-8.42-all.jar`, so it appears to be something odd with the plugin.

The bad news - it's highly unlikely that I'll have time to look at it before the weekend, at the earliest.

**Comment by jshiell** [comment]
Better news - I think this is a problem with your rules file, in particular `MissingJavadocMethod` - this still appears to have the `scope` attribute, not `accessModifiers`.

Source - https://github.com/checkstyle/checkstyle/blob/9456a052d88382854b60877fd9959318b3d87296/src/main/java/com/puppycrawl/tools/checkstyle/checks/javadoc/MissingJavadocMethodCheck.java#L340
Docs - https://checkstyle.sourceforge.io/config_javadoc.html#MissingJavadocMethod

```
    <module name="MissingJavadocMethod">
      <property name="severity" value="ignore"/>
      <property name="accessModifiers" value="public, protected"/>
      <property name="minLineCount" value="2"/>
      <property name="allowedAnnotations" value="Override, Test"/>
      <property name="tokens" value="METHOD_DEF, CTOR_DEF, ANNOTATION_FIELD_DEF"/>
    </module>
```

If I changed accessModifiers to `<property name="scope" value="public"/>` then it loads fine.

I've no idea why it doesn't break with `checkstyle-8.42-all.jar`.

**Comment by remal** [comment]
Checkstyle 8.42 requires `accessModifiers` only, not `scope`. This version of Checkstyle **should fail** on `scope`. As you can see in https://github.com/checkstyle/checkstyle/commit/2954d8723003ef229f5825510a433ab8c60f2774, the `scope` property has been completely removed.

BTW my CI job executes Checkstyle 8.42 check successfully. The problem with the IDEA plugin only.

**Comment by jshiell** [comment]
Your file uses access modifiers on MissingJavadocMethod, which - as per the source and the docs - does not support it.

Closing as user error.

**Comment by remal** [comment]
Thank you, you're absolutely right! They changed `JavadocMethod`, but not `MissingJavadocMethod`. But I changed both of them modules in my config file. Don't know why CI doesn't fail, btw.

**Comment by jshiell** [comment]
Yeah, it's pretty weird (and inconsistent - hopefully they'll fix this in a future version). I couldn't get it to fail with the command-line version either - yet looking at the source it really should.
