### ISSUE TITLE
Configuration option "Ignore invalid certificates" does not get saved

### ISSUE THREAD

**Issue by GethDeeo** [jshiell/checkstyle-idea#528]
I've set up the plugin for new projects, added my configuration from HTTP source.
Unfortunately, I need the ignore invalid certificates option :(
It seems to me, that it gets saved as `HTTP_URL` instead of `INSECURE_HTTP_URL`, ignoring the checkbox on the UI.

Manually editing the XML solves the problem, it does not get reverted.

**Comment by jshiell** [comment]
Thanks for the report. Hopefully shouldn't be too hard to fix - will try and get it sorted in the not too distant.

**Comment by jshiell** [comment]
I think I've got it - past me was obviously an idot, and failed to override a clone method 🤦  Hopefully 5.53.1 will sort this for you!
