### ISSUE TITLE
Configuration file HTTP auth

### ISSUE THREAD

**Issue by austek** [jshiell/checkstyle-idea#535]
Adding a configuration file from Authenticated HTTP doesn't work when the users password contains `@` sign

Tried following URLs

* `https://user:pass@12word@sonarqube.example.com/api/qualityprofiles/export?exporterKey=checkstyle&language=java&qualityProfile=Default%20Profile`

* `https://user:pass%4012word@sonarqube.example.com/api/qualityprofiles/export?exporterKey=checkstyle&language=java&qualityProfile=Default%20Profile`

**Comment by jshiell** [comment]
Fixed thanks to @austek !
