### ISSUE TITLE
Support checkstyle 9.0

### ISSUE THREAD

**Issue by horwitzj** [jshiell/checkstyle-idea#536]
[Release](https://github.com/checkstyle/checkstyle/releases/tag/checkstyle-9.0)

[Release notes](https://checkstyle.org/releasenotes.html#Release_9.0)

Thank you!

**Comment by jshiell** [comment]
Released in 5.56.0. 9.0 uses Antlr 4.0, so some of the exception handling code has had to change, but testing seems okay 🤞
