### ISSUE TITLE
OpLoadConfiguration internal error

### ISSUE THREAD

**Issue by irux** [jshiell/checkstyle-idea#545]
Hello,

I was trying to import this checkstyle.xml file https://github.com/confluentinc/common/blob/master/build-tools/src/main/resources/checkstyle/checkstyle.xml on the Settings -> Code Style -> Java -> Import Checkstyle configuration, but when I  give the file to the importer, I get this error:

![image](https://user-images.githubusercontent.com/10131986/143200356-9f040ae8-fb32-403a-a1f6-2d917c0ff177.png)

Do you have any idea what is happening? 

Thank you!

**Comment by jshiell** [comment]
Very odd, just tried myself with Checkstyle 9.1 active and it imported correctly for me.

What version of Checkstyle do you have selected?

**Comment by irux** [comment]
![image](https://user-images.githubusercontent.com/10131986/143871369-5e96f045-811c-450b-a704-60a5faa0b6cc.png)
I have the 9.1 but I get an error too.
here my IDE version:
![image](https://user-images.githubusercontent.com/10131986/143871458-e2900e4a-ca40-4959-b676-b34939aba58f.png)

should I test something else ? 

thank you! @jshiell

**Comment by jshiell** [comment]
You're on the same version of IntelliJ as myself.

Is there any more information in the event log? Normally a load error would have a root cause from Checkstyle that would explain it.

Do you have the properties set to anything in particular? I left them blank in my test.

**Comment by ichantzaras** [comment]
Hello,
I also stumbled upon the same error and I see the is a relevant [question ](https://stackoverflow.com/q/69558684) posted on SO with the same stack trace I get.
In my case I tried to import the checkstyle config of the odl project located [here](https://github.com/opendaylight/odlparent/blob/master/checkstyle/src/main/resources/odl_checks.xml)

Thanks in advance for any help.

**Comment by jshiell** [comment]
Hi @ichantzaras - OpLoadConfiguration wraps a lot of errors during load, so it may not be indentical.

What version of Checkstyle do you have selected? The ODL rules files works fine for me with the latest plugin as long as I have Checkstyle 8.26 selected and Sevntu 1.36.0 in the third-party checks.

**Comment by ichantzaras** [comment]
Hi @jshiell ,
I tried also with Checkstyle 8.26 as you mentioned but it doesn't seem to work either. The version of the plugin is 5.69.0.
If I change the odl_checks to not include the placeholder in the severity property it is imported successfully, same as described in the SO post. 
Below you can find the configured settings I have and the related error log. 


![image](https://user-images.githubusercontent.com/25647695/182019753-5e4acf46-4425-4268-a9d3-b2f3e30cc6b7.png)

![image](https://user-images.githubusercontent.com/25647695/182019175-0fbe7923-6e19-42a0-9d91-780dc97282e9.png)

![image](https://user-images.githubusercontent.com/25647695/182019274-fbe03bad-b412-4043-8469-b536eb5ef68a.png)

[idea_20220731.log](https://github.com/jshiell/checkstyle-idea/files/9228559/idea_20220731.log)

I also tried to include the [sventu checks 1.36.0](https://github.com/sevntu-checkstyle/sevntu.checkstyle/blob/1.36.0/sevntu-checks/sevntu-checks.xml) but I run into the below error

![image](https://user-images.githubusercontent.com/25647695/182020751-fce5720d-8fd3-49da-a001-e6db24bd4011.png)

Am I missing any required settings? 
Is there any other information I could obtain that might help you reproduce it?

Thanks again.

**Comment by jshiell** [comment]
That looks that the classloader isn't able to see the Sventu modules, and they're not present in the screenshot above.

You need to ensure they're added into the third-party modules checks, as below, so the classloader can find them.

<img width="599" alt="Screenshot 2022-08-06 at 09 57 52" src="https://user-images.githubusercontent.com/1030482/183242327-416d5756-6771-4f69-9d59-ae7051c6e353.png">
