### ISSUE TITLE
Checkstyle-IDEA Plugin incompatible with DevEcoStudio

### ISSUE THREAD

**Issue by kanaksony** [jshiell/checkstyle-idea#548]
Hello all,
I am facing an issue. Here are the details details -
https://stackoverflow.com/questions/70344375/checkstyle-idea-plugin-incompatible-with-devecostudio

I am trying to configure the Checkstyle-IDEA plugin With the latest version of DevEcoStudio but seems it is incompatible with the same.

Steps I have performed in DevEcoStudio - Main Menu -> File->Settings->Plugins->Search Checkstyle, results in Nothing found as you can see in below picture
![image](https://user-images.githubusercontent.com/6097596/145942701-d8b92977-ecbd-4f86-ab0b-7086d767ba65.png)

Also, I have tried installing it from Checkstyle-IDEA marketplace but it fails while installation with the following error -
![image](https://user-images.githubusercontent.com/6097596/145942736-0faa15f7-476b-4d0b-bdef-c1078442402b.png)

DevEco Studio Version:
```
DevEco Studio 3.0 Beta1
Build Version: 3.0.0.601, built on October 19, 2021
Runtime version: 11.0.9+11-b944.49 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
open-source software
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1484M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.mayevskiy.intellij.sonar
```

**Can anyone please suggest any solution?**

**Comment by jshiell** [comment]
I'm afraid we don't support DevEco Studio. Indeed, until you posted this I didn't even know it existed. The only thing I test on and support is IntelliJ IDEA, although I _believe_ the plugin does work in Android Studio as well.

Given the above, it looks like it's complaining based on the build number. Given the DevEcoStudio version references "202" in the number, it may well be built on an older platform version (platform 202 was IDEA 2020.2 I think). [You could try an older version of the plugin](https://plugins.jetbrains.com/plugin/1065-checkstyle-idea/versions) as the current versions won't work below platform 211 (IDEA 2021.1.3). Version 5.56.0 was build against IDEA 2020.1.4, so may work, but I cannot guarantee it.

**Comment by kanaksony** [comment]
Thanks @jshiell , the previous version 5.56.0 worked.
