### ISSUE TITLE
IntelliJ 2022.1 EAP: Detected both log4j-over-slf4j.jar AND bound slf4j-log4j12.jar on the class path

### ISSUE THREAD

**Issue by ahus1** [jshiell/checkstyle-idea#553]
There seems to be a problem with the CheckStyle plugin in the latest 2022.1 EAP version and log4j. 

This is probably caused by JetBrains removing Log4J from their distribution, see https://blog.jetbrains.com/platform/2022/02/removing-log4j-from-the-intellij-platform/ for the announcement.

IntelliJ IDEA 2022.1 EAP (Ultimate Edition)
Build #IU-221.4501.155, built on February 17, 2022
Runtime version: 11.0.14+9-b1993.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    ide.browser.jcef.contextMenu.devTools.enabled=true
    CheckStyle-IDEA (5.61.0)

> The scan failed due to an exception: null Root cause: Detected both log4j-over-slf4j.jar AND bound slf4j-log4j12.jar on the class path, preempting StackOverflowError. See also http://www.slf4j.org/codes.html#log4jDelegationLoop for more details. java.lang.IllegalStateException: Detected both log4j-over-slf4j.jar AND bound slf4j-log4j12.jar on the class path, preempting StackOverflowError. See also http://www.slf4j.org/codes.html#log4jDelegationLoop for more details.   at org.slf4j.impl.Log4jLoggerFactory. (Log4jLoggerFactory.java:54)   at org.slf4j.impl.StaticLoggerBinder. (StaticLoggerBinder.java:72)   at org.slf4j.impl.StaticLoggerBinder. (StaticLoggerBinder.java:45)   at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)   at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)   at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)   at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)   at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)   at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)   at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)   at org.infernus.idea.checkstyle.util.CheckStyleEntityResolver. (CheckStyleEntityResolver.java:26)   at org.infernus.idea.checkstyle.model.ConfigurationLocation.extractProperties(ConfigurationLocation.java:134)   at org.infernus.idea.checkstyle.model.ConfigurationLocation.resolve(ConfigurationLocation.java:198)   at org.infernus.idea.checkstyle.model.ConfigurationLocation.ensurePropertiesAreUpToDate(ConfigurationLocation.java:188)   at org.infernus.idea.checkstyle.checker.CheckerFactory.createChecker(CheckerFactory.java:141)   at org.infernus.idea.checkstyle.checker.CheckerFactory.getOrCreateCachedChecker(CheckerFactory.java:88)   at org.infernus.idea.checkstyle.checker.CheckerFactory.checker(CheckerFactory.java:69)   at org.infernus.idea.checkstyle.CheckStyleInspection.inspectFile(CheckStyleInspection.java:127)   at org.infernus.idea.checkstyle.CheckStyleInspection.lambda$checkFile$0(CheckStyleInspection.java:80)   at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:326)   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)   at java.base/java.security.AccessController.doPrivileged(Native Method)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)   at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by jshiell** [comment]
Thanks very much - I'll try get that sorted in the not too distant.

**Comment by jshiell** [comment]
Turns out I'd already done the work to port it to the diagnostic API - I just hadn't cleaned up all the artefacts. I've now removed these; will release as 5.61.1 - hopefully that fix this for you 🤞

**Comment by ahus1** [comment]
Thanks for releasing this update, it works nicely. 

I no longer see the exception in the notifications, and validation with Checkstyle works as expected!
