### ISSUE TITLE
Apply Checkstyle Plugin settings globally to all projects

### ISSUE THREAD

**Issue by IgorKomissarov** [jshiell/checkstyle-idea#554]
Checkstyle plugin settings are project specific in IDEA: if I want to use a different checkstyle version and use a custom configuration file I have to repeat this set up in every project that I have. Is there a way to apply plugin settings globally?

I know about an option to set up settings for all _new_ projects. But I want to apply it to already existing ones which I have plenty.

**Comment by jshiell** [comment]
At present, there's no option to do so.

IDEA's API does offer the ability to do application-level configuration (we use it [for the update alert](https://github.com/jshiell/checkstyle-idea/blob/main/src/main/java/org/infernus/idea/checkstyle/config/ApplicationConfigurationState.java)) but there's no Checkstyle configuration stored at that level at present. Any change to do so would require some thought, in particular as to what belongs where, how this impacts existing projects, and especially how this impacts shared projects (which won't share application-level config). 

So it's not a trivial thing to add I fear, and not a feature I'm planning to add at present. Sorry.

**Comment by jshiell** [comment]
A thought ... as a hack, would copying the project settings from project to project (i.e. `.idea/checkstyle-idea.xml`) help?

**Comment by gabryellr** [comment]
> A thought ... as a hack, would copying the project settings from project to project (i.e. `.idea/checkstyle-idea.xml`) help?

I tried it, it works like a charm :) thank you
