### ISSUE TITLE
New Checkstyle 10 features lead to error during plugin execution

### ISSUE THREAD

**Issue by r0bb3n** [jshiell/checkstyle-idea#556]
Hi,

I migrated ([this PR](https://github.com/r0bb3n/sonar-quality-gate-maven-plugin/pull/208)) my project [sonar-quality-gate-maven-plugin](https://github.com/r0bb3n/sonar-quality-gate-maven-plugin) to latest (10.1) checkstyle used with maven and updated my custom checkstyle configuration file by rebasing on the [internal google_check.xml](https://github.com/checkstyle/checkstyle/blob/checkstyle-10.1/src/main/resources/google_checks.xml) and changing just a few things. While mvn execution just runs fine, I get now the following error logs in IntelliJ:

```
The Checkstyle rules file could not be parsed.
	cannot initialize module TreeWalker - Token "ELLIPSIS" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck
	The file has been blocked for 60s.

The Checkstyle rules file could not be parsed.
	cannot initialize module TreeWalker - Token "LITERAL_SWITCH" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck
	The file has been blocked for 60s.

The Checkstyle rules file could not be parsed.
	cannot initialize module TreeWalker - Token "LAMBDA" was not found in Acceptable tokens list in check com.puppycrawl.tools.checkstyle.checks.whitespace.WhitespaceAfterCheck
	The file has been blocked for 60s.
```

It seems the the new features [introduced with version 10.0](https://checkstyle.org/releasenotes.html#Release_10.0) are not supported by this plugin so far:

* WhitespaceAfter does not work on 'switch' and lambda statements. Author: Vyom-Yadav [#11298](https://github.com/checkstyle/checkstyle/issues/11298)
* WhitespaceAfter should support `ELLIPSIS` token. Author: Vyom-Yadav [#11116](https://github.com/checkstyle/checkstyle/issues/11116)

**WhitespaceAfter config with 10.0 features - breaking**
```xml
    <module name="WhitespaceAfter">
      <property name="tokens"
        value="COMMA, SEMI, TYPECAST, LITERAL_IF, LITERAL_ELSE,
                    LITERAL_WHILE, LITERAL_DO, LITERAL_FOR, DO_WHILE, ELLIPSIS,
                    LITERAL_SWITCH, LAMBDA"/>
    </module>
```

**WhitespaceAfter config without 10.0 features - not breaking**
```xml
    <module name="WhitespaceAfter">
      <property name="tokens"
        value="COMMA, SEMI, TYPECAST, LITERAL_IF, LITERAL_ELSE,
                    LITERAL_WHILE, LITERAL_DO, LITERAL_FOR, DO_WHILE"/>
    </module>
```

For the moment I rolled back my local config to the latter one, but would be nice, if also the new features would be supported by your nice plugin.

Best regards,
r0bb3n

My setup:

* Plugin: CheckStyle-IDEA 5.62.0
* IntelliJ IDEA 2021.3.3 CE
* Open JDK 11
* Window 10 Pro

**Comment by jshiell** [comment]
Moring. thanks for the report - quick check, you do have Checkstyle 10.0 selected as the active version in the plugin preferences? That will require changing manually if you've been using old versions.

As an aside, I'll try and get a release with 10.1 out today as well.

**Comment by r0bb3n** [comment]
🤦‍♂️ you are absolutely right. After selecting `10.0` from the drop-down, it works perfectly fine. 

Sorry for raising this issue. 😅

**Comment by jshiell** [comment]
No worries at all, just glad we got it working!
