### ISSUE TITLE
Google Style Ckeck - PatternVariableName false flag on local variable

### ISSUE THREAD

**Issue by ryzexcode** [jshiell/checkstyle-idea#560]
a false flag is generated for local variable names like "xArr", even though they match the pattern "^[a-z][a-zA-Z0-9]*$", when using the google checks

**Comment by jshiell** [comment]
Does it occur with Checkstyle as well, or only with the IDEA plug-in?

AFAIK we just report the results of this check verbatim.

**Comment by ryzexcode** [comment]
can confirm, this is an issue with Checkstyle in general and not specifically linked to the IDEA plugin.

**Comment by jshiell** [comment]
Thanks for checking that, 🤞 for a fast fix!
