### ISSUE TITLE
exclude package or directory from being scanned

### ISSUE THREAD

**Issue by jonasgeiregat** [jshiell/checkstyle-idea#561]
A project where some sources are generated should be able to be excluded like the gradle checkstyle plugin allows.

```grvooy
checkstyleMain.exclude("some/dir/*.java")
```

**Comment by jshiell** [comment]
I believe you can do this in standard Checkstyle and the IDEA plugin by using [suppression filters](https://checkstyle.sourceforge.io/config_filters.html).

We've no plans to support integration with build tools, as that's a Pandora's box.

**Comment by JanK411** [comment]
Shouldn't this be also resolved by PR #559 ?
Not with a gradle integration but manually you could exclude files like the given scheme providing it with a scope in the IDE.

**Comment by jshiell** [comment]
Depends on how much they wish to exclude - if it's an entire scope, yes, but if it's just a subset of an existing scope, they may need a suppression file.

Closing for the present anyway, as I believe suppressions files will provide standardised support for this use case.
