### ISSUE TITLE
5.64.0: NullPointerException: Adding null to TreeSet

### ISSUE THREAD

**Issue by vicky17d** [jshiell/checkstyle-idea#566]
Version 5.64.0

https://github.com/jshiell/checkstyle-idea/blob/bb004746a2f45d63fc269d9b713d02a95f7457a0/src/main/java/org/infernus/idea/checkstyle/config/PluginConfiguration.java#L50

constrainActiveLocation() method can return null which causes NPE

**Comment by jshiell** [comment]
Thanks very much. I've withdrawn 5.64.0 until I'm able to look at this at #565

**Comment by vicky17d** [comment]
I saw that. Just want to confirm that this issue is fixed along with #565 as well as it is a blocker for us.

**Comment by jshiell** [comment]
Fixed in 5.65.0.
