### ISSUE TITLE
The Finish button is not displayed when a local checkstyle is added.

### ISSUE THREAD

**Issue by wangboeveryday** [jshiell/checkstyle-idea#571]

**Comment by wangboeveryday** [comment]
![截图](https://user-images.githubusercontent.com/20419140/168514616-90a70099-16c8-4c44-a67d-d4e831e2454c.PNG)

**Comment by jshiell** [comment]
I can't reproduce this - the `Next` button is always enabled for me, even before I've entered any details.

Can you please describe how you got it into this state? Did you just press the `+` button, or have you gone backwards in the wizard?

**Comment by jshiell** [comment]
Closed due to no futher info. Please feel free to reopen if you have more data.
