### ISSUE TITLE
The Checkstyle rules file could not be read

### ISSUE THREAD

**Issue by ladislavlencucha** [jshiell/checkstyle-idea#577]
After upgrade to 5.67.2 I am getting "The Checkstyle rules file could not be read" error message. It seems, that the plugin does not do anything  (obviously) afterwards.

My config:
```
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="CheckStyle-IDEA" serialisationVersion="2">
    <checkstyleVersion>8.45.1</checkstyleVersion>
    <scanScope>JavaOnlyWithTests</scanScope>
    <scanBeforeCheckin>true</scanBeforeCheckin>
    <option name="thirdPartyClasspath" />
    <option name="activeLocationIds">
      <option value="e85e46be-d89e-4842-9657-72ed421dee5a" />
    </option>
    <option name="locations">
      <list>
        <ConfigurationLocation id="e85e46be-d89e-4842-9657-72ed421dee5a" type="PROJECT_RELATIVE" scope="All" description="myproject">etc/codestyle/checkstyle.xml</ConfigurationLocation>
      </list>
    </option>
  </component>
</project>
```

**Comment by jshiell** [comment]
Hmm, something has gone oddly wrong here. Project relative paths should just reparse the path to be project relative, e.g. if the rules file was in a parent directory then we'd refer to it using `$PROJECT_DIR$/../file.xml`. However, they will still require `$PROJECT_DIR` to be there.

Without seeing the data prior to transformation it's hard to say how it got into this state, but the quick fix should be to edit file to have `$PROJECT_DIR`, i.e.

```xml
... description="myproject">$PROJECT_DIR$/etc/codestyle/checkstyle.xml</ConfigurationLocation>
```

**Comment by ladislavlencucha** [comment]
Re-generating the file from scratch seems to have fixed the issue. Thanks!
