### ISSUE TITLE
Point plugin to particular checkstyle jar on local machine

### ISSUE THREAD

**Issue by stoyanK7** [jshiell/checkstyle-idea#582]
Of course there is the dropdown menu to choose the ![Screenshot from 2022-07-19 18-42-19](https://user-images.githubusercontent.com/23459549/179792274-b596f818-be93-4ed2-be1a-7e3e6ef8ae58.png) from. But I was wondering whether it is currently possible to point it to a `checkstyle-x-all.jar` file on my computer to execute from? Maybe add the file in the plugin folder or something like that? I am currently digging to see what I can do.

I am currently contributing to Checkstyle itself and would like to point to the latest snapshot `jar` in the `target` folder. https://github.com/checkstyle/checkstyle/issues/11916

This is not a feature request but rather a question.

---
Edit: Making a symlink from one of the jar files(in plugin folder, `~/.local/share/JetBrains/IdeaIC2022.1/CheckStyle-IDEA/checkstyle/lib/checkstyle-10.2.jar` in my case) and then selecting that version seems to work.

**Comment by tsjensen** [comment]
Officially, this is not possible. It's not supported. However, if you're in for wild hacks, you can find the `checkstyle-classpaths.properties` file in the plugin, and add a line to it:

`10.2=checkstyle/lib/xmlresolver-4.2.0-data.jar;checkstyle/lib/Saxon-HE-11.3.jar;checkstyle/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;checkstyle/lib/checker-qual-3.12.0.jar;checkstyle/lib/antlr4-runtime-4.10.1.jar;checkstyle/lib/javassist-3.28.0-GA.jar;checkstyle/lib/xmlresolver-4.2.0.jar;checkstyle/lib/slf4j-api-1.7.32.jar;checkstyle/lib/checkstyle-10.2.jar;checkstyle/lib/reflections-0.10.2.jar;checkstyle/lib/commons-collections-3.2.2.jar;checkstyle/lib/httpcore-4.4.13.jar;checkstyle/lib/picocli-4.6.3.jar;checkstyle/lib/failureaccess-1.0.1.jar;checkstyle/lib/httpclient-4.5.13.jar;checkstyle/lib/commons-codec-1.11.jar;checkstyle/lib/guava-31.1-jre.jar;checkstyle/lib/jsr305-3.0.2.jar;checkstyle/lib/error_prone_annotations-2.11.0.jar;checkstyle/lib/j2objc-annotations-1.3.jar;checkstyle/lib/commons-beanutils-1.9.4.jar`

The above adds version `10.2`, but you can just add `10.42-RC1` or whatever. You need the correct classpath of course, and all the libraries you reference must be provided in the `checkstyle/lib` dir.

Just never ask us if this fails. 😈

**Comment by jshiell** [comment]
Thanks @tsjensen - much obliged.

@stoyanK7 unfortunately we don't support this as not all versions of Checkstyle (especially older versions) are binary compatible (in particular, some older versions required some funky introspection for cross-compatibility).
