### ISSUE TITLE
It is inconsistent with the Google plugin.

### ISSUE THREAD

**Issue by lin-mt** [jshiell/checkstyle-idea#588]
This is after Google Format
https://github.com/google/google-java-format
<img width="543" alt="image" src="https://user-images.githubusercontent.com/58337359/184634227-ae52d753-cd73-4178-971a-e2e71a4e2404.png">

Checkstyle prompts that the imports are in the wrong order：
<img width="823" alt="image" src="https://user-images.githubusercontent.com/58337359/184634336-a3ad9fce-f9b2-40e1-8de1-d649a69c3d23.png">

**Comment by jshiell** [comment]
We use the Google Checks that are packaged with [https://github.com/checkstyle/checkstyle](Checkstyle) - not something we have control over.
