### ISSUE TITLE
Are there any plan to support JetBrains Client？

### ISSUE THREAD

**Issue by SwimSweet** [jshiell/checkstyle-idea#589]
thx

**Comment by jshiell** [comment]
No plans at present, but from what I understand it _should_ work - if someone is willing to test it by hacking the manifest, I'd be willing to add it to the distribution once that's confirmed.

**Comment by SwimSweet** [comment]
@jshiell  thank you. I installed Checkstyle plugin in wrong way by past. The right way is install Checkstyle plugin by Idea plugins button with On host.
By my test , Checkstyle support JetBrains Client.
![244a8ffe84af775fd23602e37c8cfd5](https://user-images.githubusercontent.com/21351694/186686689-a373f7fb-7c57-4afd-9f95-acc1dbd97f0f.jpg)

**Comment by jshiell** [comment]
No worries, glad to hear it's working for you!
