### ISSUE TITLE
Request: Ignore warnings when executing pre-commit check

### ISSUE THREAD

**Issue by simonstratmann** [jshiell/checkstyle-idea#591]
I only care about errors. When the pre-commit check finds warnings or errors in the scanned files there's no way for me to tell which kind the issues are that it found.

Please add an option to ignore warnings in the pre-commit check or show how many errors and warnings were found, respectively.

Thanks!

**Comment by jshiell** [comment]
<img width="375" alt="Screenshot 2022-10-08 at 11 40 15" src="https://user-images.githubusercontent.com/1030482/194703502-a3db70a6-7f3d-4e31-a961-c646be9c16dc.png">

On its way in 5.71.1 👍

**Comment by simonstratmann** [comment]
Awesome, thanks!
