### ISSUE TITLE
not support idea  2022.3

### ISSUE THREAD

**Issue by licocon** [jshiell/checkstyle-idea#599]
<img width="1482" alt="iShot_2022-12-05_11 40 55" src="https://user-images.githubusercontent.com/36863277/205544531-c832d2ac-23f8-4420-954c-2038b828530f.png">

**Comment by jshiell** [comment]
The plugin definitely supports 2022.3 (I'm running it in 2022.3 right now) - indeed, we don't set up upper bound, so it won't block installation on any newer IDEA (although if they change the API it might blow up...).

The only dep for the plugin is the `com.intellij.modules.java` module - I don't think this is present in DataGrip or WebStorm, and hence it's unlikely to work in those. However, IDEA or Android Studio should be fine.
