### ISSUE TITLE
Suppressions File from 3rd party lib

### ISSUE THREAD

**Issue by dlafreniereupgrade** [jshiell/checkstyle-idea#603]
I have a 3rd party library (that I control) with custom checks and config/suppressions files. I'm having trouble getting the plugin to pickup the suppressions file via SuppressionFilter

```
myChecks.jar
 - com/my/company/Check.java
 - com/my/company/config.xml
 - com/my/company/suppressions.xml
```

I add `myChecks.jar` to "Third-Party Checks"
Then I add a Configuration File, "Use a Checkstyle file accessible via the third-party checks classpath", `com/my/company/config.xml`

The custom checks work, however the suppressions aren't loaded, I get `"The Checkstyle suppression filter file was not found and will be ignored"`

I've tried various combinations of file path for the SuppressionFilter (in config.xml)
```xml
<module name="SuppressionFilter">
  <property name="file" value="suppressions.xml"/>
</module>
```
```xml
<module name="SuppressionFilter">
  <property name="file" value="/suppressions.xml"/>
</module>
```
```xml
<module name="SuppressionFilter">
  <property name="file" value="com/my/company/suppressions.xml"/>
</module>
```
```xml
<module name="SuppressionFilter">
  <property name="file" value="/com/my/company/suppressions.xml"/>
</module>
```

but I always get the error message that the file can't be found. Am I doing something wrong, or is this not supported?

**Comment by jshiell** [comment]
Hmm, I'm pretty sure this should be supported. [Our associated file lookup code](https://github.com/jshiell/checkstyle-idea/blob/b5df24062ba005d822e5fc6349b34051bbb3fa0d/src/main/java/org/infernus/idea/checkstyle/model/ConfigurationLocation.java#L260) explicitly tries to check the classpath.

Do you have a prepared test case for it? Sounds like it'll need a poke with a debugger to see what's going wrong.

**Comment by dlafreniereupgrade** [comment]
Thanks for the response, while preparing a sample project, I got it to work using the following syntax:
```xml
<module name="SuppressionFilter">
  <property name="file" value="/com/my/company/suppressions.xml"/>
</module>
```

I think something was messed up in the Intellij plugin settings, and by removing all of the 3rd party jars and custom configs and re-adding them, it started working 🤷‍♂️ (I could have sworn I did this already).

Thanks for maintaining this and for the rubber ducking 🦆

**Comment by jshiell** [comment]
My pleasure, glad to hear it's all working!
