### ISSUE TITLE
error when im trying to add a checkstyle_rules.xml

### ISSUE THREAD

**Issue by lurafonso** [jshiell/checkstyle-idea#611]
When I try to add the checkstyle rules, the following message appears

The Checkstyle suppression filter file was not found and will be ignored

![Captura de Tela 2023-04-28 às 17 44 03](https://user-images.githubusercontent.com/129226240/235251030-8b5a327b-bdf5-452c-bf87-8690b39236c8.png)

IntelliJ IDEA 2023.1.1 (Ultimate Edition)
CheckStyle-IDEA (5.78.0)

**Comment by jshiell** [comment]
That indicates it can't find the referenced suppression filter file. There's a bunch of heuristics we use to find it. 

Can you please add your rules files, and desribe where the files are on disk and in relation to your project?

**Comment by jshiell** [comment]
Although if you're just using this for code style, not for the checks, then this warning can be ignored.

**Comment by jshiell** [comment]
Closing due to no further information
