### ISSUE TITLE
Exclude paths from scanning

### ISSUE THREAD

**Issue by AndyGee** [jshiell/checkstyle-idea#613]
Is there any reliable way to configure excluded paths for the plugin?
Code that is generated (eg, target/anypath) is scanned by the 'Check Project' option and I can't find a way to disable that in the code or docs.

**Comment by jshiell** [comment]
The normal way to do this is via a SupressionFilter, which keeps it consistent across mutliple checkstyle impls (e.g. the CLI, Gradle plugins, etc.)

https://checkstyle.sourceforge.io/config_filters.html

**Comment by jshiell** [comment]
Closing due to no futher feedback and because this can be accomplished in core Checkstyle.
