### ISSUE TITLE
Checkstyle XML based on the default Intellij settings

### ISSUE THREAD

**Issue by royteeuwen** [jshiell/checkstyle-idea#619]
This is more a request for information.

I'd like to start using the checkstyle maven plugin on our existing project. Sadly enough it does not conform to the google checks, but in every pull request we always requested that people format their file using the existing formatting (CMD + L) in intellij.

To still have the benefit of using checkstyle, I'd like to make the default intellij code style rules the actual checkstyle checks. Do you know of any existing checkstyle XML that conforms to the Intellij formatting?

**Comment by jshiell** [comment]
Afraid not - the only two shared maintained ones I know of are the Sun and Google ones distributed with Checkstyle.
