### ISSUE TITLE
checkstyle not performing some checkstyle rule.

### ISSUE THREAD

**Issue by parth-ekzero** [jshiell/checkstyle-idea#624]
I have updated the latest version of intellij idea.

after updating my version, I have found that some validations are not working properly.

i.e. 

I have provided validation that at max 140 character should be there in one line.

Before updating the version, if I write more than 140 characters in a line then when I save my code, IntelliJ was arranging extra characters in next line. But after updating this (or in latest version) it is not happening.

what is the solution?

**Comment by jshiell** [comment]
CheckStyle only provides feedback, not code changes. If you were using something that would reformat the code, it wasn't this. While we do have some limited options for supporting importing the CheclStyle rules as an IDEA formatter, the formetter itself is a core part of IDEA and not something we can change.

If there's a part of that import that's not working properly then that would potentially be something the plugin could affect.

**Comment by jshiell** [comment]
Clsoing due to no further info
