### ISSUE TITLE
Enhance Jar Reload Functionality for Improved Workflow

### ISSUE THREAD

**Issue by EricKrohnfeldt** [jshiell/checkstyle-idea#630]
Description:
Currently, when building a new version of the JAR with custom checks, the process of reloading the JAR involves navigating to settings and either editing or deleting and re-adding the third-party check row. This workflow is cumbersome and could be streamlined for better efficiency.

Request:
Use "Reload" button to easily refresh or reload the JAR without the need to manually edit or delete and re-add the third-party check row. This enhancement would greatly improve the user experience and save time during the development process.

![image](https://github.com/jshiell/checkstyle-idea/assets/72825654/47a88f94-7e00-4551-90ae-ce9eff049d70)

**Comment by jshiell** [comment]
Seems a very fair request, and I'm surprised it doesn't do it already. I think it's fairly simple, but will require a little refactoring to remove the (partial) dup of the code here; I'm out of time to work on this today but will _try_ have a look next weekend.

**Comment by jshiell** [comment]
Code is pushed, but testing is cursory at best so I'm not prepared to release it just yet.

**Comment by jshiell** [comment]
It's not looking like I'll get much time to look at it this weekend, but [here's a link](https://www.icloud.com/iclouddrive/042KNaUqCiJA6i7rfpXnpj8Gg#CheckStyle-IDEA-5.87) to a test build, in case that's of use.

**Comment by EricKrohnfeldt** [comment]
No rush.  I just reel better knowing it's in the pipe.

**Comment by jshiell** [comment]
Hopefully fixed in 5.87.1 - if it doesn't work for your use case, please reopen, and I'll take another go (experience has taught me never to be overconfident regarding anything involving caching).
