### ISSUE TITLE
Changes to checkstyle.xml file don't seem to be picked up without restart

### ISSUE THREAD

**Issue by paulgrime-sky** [jshiell/checkstyle-idea#632]
I have a `checkstyle.xml` file in my workspace. I make changes to it. I run code analysis and the changes haven't been picked up.

**Comment by jshiell** [comment]
The rules files are cached for perf. Did you use the refresh button to clear the cache? If not it’s about a 60s cache time from memory.

**Comment by paulgrime-sky** [comment]
Hi.  I'm not sure where such a refresh button is.  Also, I have waited longer than 60s and the settings do not get refreshed.

```
IntelliJ IDEA 2023.3.1 (Ultimate Edition)
Build #IU-233.11799.300, built on December 12, 2023
Licensed to XXX
Expiration date: XXX
Runtime version: 17.0.9+7-b1087.7 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins:
  CheckStyle-IDEA (5.87.0)
  com.thoughtworks.gauge (233.11799.196)
  org.intellij.scala (2023.3.19)
Kotlin: 233.11799.300-IJ
```

![image](https://github.com/jshiell/checkstyle-idea/assets/94377836/23945276-e25d-486c-8391-d5401cf9e2a2)

![image](https://github.com/jshiell/checkstyle-idea/assets/94377836/f28208b1-84ae-4c8e-9284-79701cd34c79)

**Comment by paulgrime-sky** [comment]
If this is the refresh button (circled) then it seems to have no effect.

![image](https://github.com/jshiell/checkstyle-idea/assets/94377836/46afe854-9111-4569-a162-4ca13c2d3f1d)

**Comment by paulgrime-sky** [comment]
Refresh button works. Thanks.
