### ISSUE TITLE
Generate CheckStyle configuration from IntelliJ Code Style Settings

### ISSUE THREAD

**Issue by kLeZ** [jshiell/checkstyle-idea#639]
Hi! I'm struggling to find some tools able to convert or generate checkstyle configuration starting from the IDE Code Style Settings (I tried either IDEA, Eclipse and VSCode without luck).

It would be useful to add such a feature to this plugin, and it would help bootstrap a checkstyle config from something you surely have already configured (and for which an GUI exists).

**Comment by jshiell** [comment]
Hey - you're not the first to suggest it, so there's clearly demand for this, but it's not something I'm willing to consider for this plugin as there's very little overlap in terms of the code required. But I do think it would make a great plugin by itself and would be a great companion to this plugin (alas, not on my roadmap at present).
