### ISSUE TITLE
Support for intellij code formatting using checkstyle scheme with suppressions?

### ISSUE THREAD

**Issue by derekobrien27** [jshiell/checkstyle-idea#640]
I have the checkstyle plugin setup and working well for checks _and_ can successfully import the scheme when formatting code.

However, the formatter does not respect the associated suppressions file, which is located alongside the `checkstyle.xml`. Suppressions are respected when doing checks, but I can't get the formatter to play along.

Am I doing something wrong or is this just not supported? If the latter, could this be implemented? Thanks in advance.

**Comment by jshiell** [comment]
It's not supported I fear, and I don't believe it's something we can implement.

All the format importer does is convert the Checkstyle rules to IDEA rules; once that's done, we have no further control - IDEA's formatting engine takes over and controls where and when it's run. Sorry.
