### ISSUE TITLE
Add a suppression file to a configuration file

### ISSUE THREAD

**Issue by NilsRenaud** [jshiell/checkstyle-idea#641]
I would like to add a custom suppression file to a specific configuration file in order to skip some checkstyle rules.

[This is possible in maven](https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/suppressions-filter.html) with: 
```xml
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <version>3.3.1</version>
        <configuration>
          <configLocation>checkstyle.xml</configLocation>
          <suppressionsLocation>checkstyle-suppressions.xml</suppressionsLocation>
        </configuration>
      </plugin>
```

**Comment by jshiell** [comment]
Suppression files are [built into base Checkstyle](https://checkstyle.org/filters/suppressionfilter.html), and supproted by the plugin via that approach.

**Comment by NilsRenaud** [comment]
For sure it's possible to have this in checkstyle, but it's really static (ie: you can't add a suppression file to an existing checkstyle set of rules) and the option offered with maven is interesting since you can reuse a checkstyle configuration file  (and follow its changes in time) with your project specific suppressions.

It would be a nice feature, though I understand you don't want to go this way.

**Comment by NilsRenaud** [comment]
Thanks I haven't seen this `optional` field in SuppressionFilter ! I need to experiment with this but it looks like it's what I really want
