### ISSUE TITLE
Filter files from results tree

### ISSUE THREAD

**Issue by delanym** [jshiell/checkstyle-idea#644]
In version 5.92.0 I ran a scan on the entire project, which returned around 3000 issues. Only a handful are error level, so I make sure "Display Errors" is selected and none of the others.

![image](https://github.com/jshiell/checkstyle-idea/assets/5310238/3028acfa-cf2a-4e27-ac10-ac3e674301dd)

This only has the effect of filtering the violation line, and not the file that violations were found in.
You can see in the image I need to find the angle bracket to actually locate the violation.

If there are no violations within the filter scope, the file should not be displayed in the tree.

I see now I can unfold the nodes, but still, why show me the file. If I click the violation it opens the file, and that's all I need to see.
Perhaps add a button to determine whether files are shown at all?

**Comment by jshiell** [comment]
Yeah, that definitely seems like a silly thing to show in the circumstances. I'll have a look when I get a tick - thanks!

**Comment by jshiell** [comment]
Basic fix is now in main; however, the trailing "x item(s)" text is incorrect and will need some further love (hence not closing this yet).

**Comment by jshiell** [comment]
Will be in the next release. Thanks for the tip!
