### ISSUE TITLE
Error importing code style scheme from checkstyle configuration

### ISSUE THREAD

**Issue by donalmurtagh** [jshiell/checkstyle-idea#652]
I'm using the latest IntelliJ and Checkstyle plugin versions

- IntelliJ IDEA 2024.2.1 
- CheckStyle-IDEA 5.94.1

When I try to [import my Checkstyle configuration as a code style scheme](https://share.getcloudapp.com/ApuG1AOw) I get the following error:

> Checkstyle configuration import failed with error message:
> org.infernus.idea.checkstyle.exception.CheckstyleToolException: unable to parse configuration stream

I haven't made a change to the Checkstyle config file since I last imported it successfully, so I suspect this failure was introduced by a recent update either to the IDE or the plugin. I've attached my Checkstyle config file (I had to add a .txt extension because GitHub doesn't allow .xml files to be uploaded).

The cause of the problem appears to be this element - specifically the usage of the `config_loc` variable - because if I remove it, the file imports without error.

```xml
<module name="SuppressionFilter">
    <property name="file" value="${config_loc}/suppressions.xml"/>
    <property name="optional" value="true"/>
</module>
```
This issue appears to be a duplicate of #651

[checkstyle.xml.txt](https://github.com/user-attachments/files/16963415/checkstyle.xml.txt)

**Comment by donalmurtagh** [comment]
It looks like this issue is a duplicate of #651

**Comment by jshiell** [comment]
Thanks for the report - dup of #651.
