### ISSUE TITLE
Show inline size violations

### ISSUE THREAD

**Issue by cub-uanic** [jshiell/checkstyle-idea#654]
It would be nice to show size violations and explanation as inline hints, as it's done by CodeMetrics plugin (https://plugins.jetbrains.com/plugin/12159-codemetrics).

As for now I have to use both CheckStyle-IDEA and CodeMetrics, but they use different configs and this really annoying.
Unfortunately, it seems that CodeMetrics is not in active development anymore and has no new commits for ~5 years.

Might be CheckStyle-IDEA could reuse some ideas (and even code?) from CodeMetrics?
It's on MIT license and so I hope this shouldn't be an issue.

**Comment by jshiell** [comment]
The goal of this plugin is purely to allow use of Checkstyle within IDEA, so I think this would be a better request for the core Checkstyle project: https://github.com/checkstyle/checkstyle

I'd certainly be keen to expose this data if it was provided by Checkstyle itself.
