### ISSUE TITLE
CheckStyle was not installed

### ISSUE THREAD

**Issue by Ylhello** [jshiell/checkstyle-idea#656]
![image](https://github.com/user-attachments/assets/cf7df84d-2052-4b7d-8861-f0aeeeafbac7) 
Hello.  I would like to ask for help. I would like to install CheckStyle, but I have this glitch.
I can't install it from the website also
![image](https://github.com/user-attachments/assets/c5b9d8b6-d9fe-4ac1-a42b-0a92d7eaa767)

**Comment by jshiell** [comment]
It looks like Jetbrains is blocking your IP due to export restrictions. That's not something I can influence - you should contact Jetbrains support if it's incorrect.

You can also download the plugin JAR from the GitHub releases, and install that via the "install from disk" option.
